#!/usr/bin/env python3
"""Embeds assets/icon0.png as a C array (src/icon_png.h). Developed by X-F1REBALL-X."""
import sys
src, dst = sys.argv[1], sys.argv[2]
b = open(src, "rb").read()
rows = [", ".join("0x%02x" % c for c in b[i:i + 16]) for i in range(0, len(b), 16)]
open(dst, "w").write(
    "/* Generated by scripts/gen_icon.py from assets/icon0.png. Do not edit. */\n"
    "#ifndef HB_ICON_PNG_H\n#define HB_ICON_PNG_H\n\n"
    "static const unsigned char hb_icon_png[%d] = {\n    %s\n};\n\n#endif\n"
    % (len(b), ",\n    ".join(rows)))
