#!/usr/bin/env python3
"""Embeds assets/fonts/inter-latin.woff2 (the page font) as a C array
(src/font_woff2.h). The woff2 is Inter (SIL OFL 1.1, assets/fonts/OFL.txt),
opsz 14, weights 400-900, Latin subset. Developed by X-F1REBALL-X."""
import sys
src, dst = sys.argv[1], sys.argv[2]
b = open(src, "rb").read()
rows = [", ".join("0x%02x" % c for c in b[i:i + 16]) for i in range(0, len(b), 16)]
open(dst, "w").write(
    "/* Generated by scripts/gen_font.py from assets/fonts/inter-latin.woff2. Do not edit.\n"
    " * Inter, SIL Open Font License 1.1 (assets/fonts/OFL.txt). */\n"
    "#ifndef HB_FONT_WOFF2_H\n#define HB_FONT_WOFF2_H\n\n"
    "static const unsigned char hb_font_woff2[%d] = {\n    %s\n};\n\n#endif\n"
    % (len(b), ",\n    ".join(rows)))
