#!/usr/bin/env python3
"""Embeds src/web/start.html (tile fallback page) as src/start_html.h. Developed by X-F1REBALL-X."""
import sys
b = open(sys.argv[1], "rb").read()
n = len(b)
b += b"\0"            # NUL-terminated so it can be searched as text
rows = [", ".join("0x%02x" % c for c in b[i:i + 16]) for i in range(0, len(b), 16)]
open(sys.argv[2], "w").write(
    "/* Generated by scripts/gen_start.py from src/web/start.html. Do not edit. */\n"
    "#ifndef HB_START_HTML_H\n#define HB_START_HTML_H\n\n"
    "#define HB_START_HTML_LEN %d\n"
    "static const unsigned char hb_start_html[%d] = {\n    %s\n};\n\n#endif\n"
    % (n, len(b), ",\n    ".join(rows)))
