#!/usr/bin/env python3
"""Embeds the Hebrew font subsets (assets/fonts/he-*.woff, Heebo, OFL) as src/font_he.h.
A clean console has no Hebrew glyphs, so the page brings its own.
Subsets were made with:
  pyftsubset Heebo-<w>.ttf --unicodes=U+0590-05FF,U+FB1D-FB4F,U+20AA --flavor=woff \\
    --layout-features='*' --no-hinting --desubroutinize"""
import sys
src = sys.argv[1] if len(sys.argv) > 1 else "assets/fonts"
dst = sys.argv[2] if len(sys.argv) > 2 else "src/font_he.h"
out = ["/* Generated by scripts/gen_font.py from assets/fonts. Do not edit. */",
       "#ifndef HB_FONT_HE_H", "#define HB_FONT_HE_H", ""]
for w in ("400", "700"):
    b = open("%s/he-%s.woff" % (src, w), "rb").read()
    rows = [", ".join("0x%02x" % c for c in b[i:i + 16]) for i in range(0, len(b), 16)]
    out.append("static const unsigned char hb_font_he_%s[%d] = {\n    %s\n};\n" % (w, len(b), ",\n    ".join(rows)))
out += ["#endif", ""]
open(dst, "w").write("\n".join(out))
