/* Generated from src/web/index.html + i18n.json by scripts/gen_webpage.py. */
#ifndef HEARBRIDGE_WEBPAGE_H
#define HEARBRIDGE_WEBPAGE_H

static const char HB_WEBPAGE[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<meta name=\"color-scheme\" content=\"dark\">\n"
    "<title>HearBridge PS5</title>\n"
    "<style>\n"
    ":root{--ink:#f4efe6;--mute:#9a948a;--void:#0c0b0f;--deck:#15131a;--card:#1c1922;--edge:#2c2833;\n"
    "--lime:#c8ff3d;--ember:#ff6a2b;--warn:#ffb23d;--bad:#ff3d5a;--glow:0 0 0 3px var(--lime)}\n"
    "*{box-sizing:border-box}\n"
    "html{background:var(--void)}\n"
    "body{margin:0;min-height:100vh;color:var(--ink);font:19px/1.45 \"Bahnschrift\",\"DIN Alternate\",\"Segoe UI\",system-ui,sans-serif;\n"
    "background:repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 2px,transparent 2px 14px),\n"
    "radial-gradient(900px 500px at 100% 0,rgba(255,106,43,.14),transparent 60%),\n"
    "radial-gradient(700px 500px at 0 100%,rgba(200,255,61,.07),transparent 60%),var(--void)}\n"
    ".wrap{max-width:1100px;margin:0 auto;padding:18px 24px 40px}\n"
    ".bar{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;padding:6px 0 16px;border-bottom:2px solid var(--edge);margin-bottom:20px}\n"
    ".brand h1{margin:0;font-size:28px;font-weight:900;letter-spacing:4px;text-transform:uppercase;line-height:1.1}\n"
    ".brand h1 b{color:var(--lime)}\n"
    ".ver{display:inline-block;color:var(--void);background:var(--ember);font-size:13px;font-weight:800;padding:0 8px;margin:6px 8px 0 0;letter-spacing:1px;\n"
    "clip-path:polygon(6px 0,100% 0,calc(100% - 6px) 100%,0 100%)}\n"
    ".by{color:var(--mute);font-size:14px;direction:ltr;unicode-bidi:isolate}\n"
    ".live{display:flex;align-items:center;padding:10px 18px;background:var(--deck);border:2px solid var(--edge);font-size:16px;font-weight:800;\n"
    "text-transform:uppercase;letter-spacing:1.5px;clip-path:polygon(10px 0,100% 0,calc(100% - 10px) 100%,0 100%)}\n"
    ".live i{width:13px;height:13px;margin:0 10px 0 0;background:var(--mute);transform:rotate(45deg)}\n"
    ".live.ok i{background:var(--lime);box-shadow:0 0 10px var(--lime)}\n"
    ".live.wait i{background:var(--warn);animation:blink 1s infinite}\n"
    ".live.bad i{background:var(--bad)}\n"
    "@keyframes blink{50%{opacity:.25}}\n"
    ".grid{display:grid;grid-template-columns:1fr 1fr;grid-gap:20px;align-items:start}\n"
    "@media(max-width:820px){.grid{grid-template-columns:1fr}}\n"
    ".panel{background:var(--deck);border:2px solid var(--edge);border-left:5px solid var(--ember);padding:18px 22px;margin-bottom:20px}\n"
    ".label{margin:0 0 12px;font-size:13px;font-weight:800;letter-spacing:3px;text-transform:uppercase;color:var(--ember)}\n"
    ".row{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid var(--edge)}\n"
    ".row:last-child{border-bottom:0}\n"
    ".k{color:var(--mute)}\n"
    ".v{font-weight:800;text-align:end;direction:ltr;unicode-bidi:isolate}\n"
    ".dev{font-size:24px;font-weight:900;margin:0 0 8px;direction:ltr;unicode-bidi:isolate}\n"
    ".meter{height:14px;background:var(--void);overflow:hidden;margin:2px 0 12px}\n"
    ".meter div{height:100%;width:0;background:linear-gradient(90deg,var(--lime),var(--warn))}\n"
    ".big{font-size:26px;font-weight:900;color:var(--lime);direction:ltr;unicode-bidi:isolate}\n"
    "input[type=range]{width:100%;height:52px;margin:4px 0 12px;accent-color:var(--lime)}\n"
    ".btns{display:flex;flex-wrap:wrap;gap:12px}\n"
    "button{flex:1;min-width:170px;min-height:66px;font:inherit;font-size:20px;font-weight:800;letter-spacing:1px;color:var(--ink);background:var(--card);\n"
    "border:2px solid var(--edge);cursor:pointer;clip-path:polygon(10px 0,100% 0,calc(100% - 10px) 100%,0 100%)}\n"
    "button:hover,button:focus,input:focus{outline:none;border-color:var(--lime);box-shadow:var(--glow)}\n"
    "button.act{background:var(--lime);color:var(--void);border-color:var(--lime)}\n"
    "button.ember{background:var(--ember);color:var(--void);border-color:var(--ember)}\n"
    "button.red{background:var(--card);color:var(--bad);border-color:var(--bad);clip-path:none}\n"
    "#langbox{position:relative;z-index:40}\n"
    "#langbtn{display:flex;align-items:center;flex:0 0 auto;min-width:0;min-height:52px;padding:0 16px;font-size:15px;text-transform:uppercase;\n"
    "letter-spacing:1px;background:var(--deck);clip-path:none}\n"
    "#langlist{display:none;position:absolute;right:0;top:calc(100% + 8px);z-index:60;width:440px;max-width:calc(100vw - 40px);padding:10px;\n"
    "grid-template-columns:1fr 1fr;grid-gap:6px;background:var(--deck);border:2px solid var(--lime);box-shadow:0 18px 40px rgba(0,0,0,.7)}\n"
    "#langlist.show{display:grid}\n"
    ".langopt{display:flex;align-items:center;width:100%;min-width:0;min-height:54px;padding:0 12px;font-size:17px;font-weight:700;\n"
    "text-align:start;text-transform:none;letter-spacing:0;background:var(--void);clip-path:none}\n"
    ".langopt.on{background:var(--lime);color:var(--void);border-color:transparent}\n"
    ".dl{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--edge)}\n"
    ".dl b{font-size:21px;direction:ltr;unicode-bidi:isolate}.dl button{flex:0 0 auto;min-width:150px}\n"
    ".msg{color:var(--bad);font-weight:800;min-height:1.5em}\n"
    "footer{color:var(--mute);font-size:15px;border-top:2px solid var(--edge);padding-top:14px}\n"
    "[dir=rtl] .live i{margin:0 0 0 10px}\n"
    "[dir=rtl] .panel{border-left:2px solid var(--edge);border-right:5px solid var(--ember)}\n"
    "[dir=rtl] #langlist{right:auto;left:0}\n"
    "[dir=rtl] .ver{margin:6px 0 0 8px}\n"
    "[dir=rtl] .label,[dir=rtl] .live,[dir=rtl] button,html[lang=ja] .label,html[lang=zh] .label{letter-spacing:0}\n"
    ".hero{border-left-color:var(--lime);padding:22px 26px}\n"
    "button.xl{min-height:96px;font-size:26px}\n"
    ".hint{margin:14px 0 4px}\n"
    ".sub{margin:22px 0 6px;font-size:14px;font-weight:800;letter-spacing:2px;text-transform:uppercase;color:var(--lime)}\n"
    ".dl .ico{width:48px;text-align:center;flex:0 0 auto;color:var(--lime)}\n"
    ".dl .nm{flex:1;min-width:0}.dl .nm b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
    ".dl .acts{display:flex;gap:10px;flex:0 0 auto}.dl .acts button{min-width:140px;min-height:62px}\n"
    ".badge{display:inline-block;background:var(--lime);color:var(--void);font-size:13px;font-weight:900;padding:0 8px;margin:0 8px}\n"
    ".badge.warn{background:var(--warn);animation:blink 1.2s infinite}.badge.off{background:var(--edge);color:var(--ink)}\n"
    ".bars{display:inline-flex;align-items:flex-end;gap:2px;height:16px;vertical-align:middle;margin:0 6px}\n"
    ".bars i{width:4px;background:var(--edge)}.bars i.on{background:var(--lime)}\n"
    ".spin{display:inline-block;width:14px;height:14px;border:3px solid var(--lime);border-right-color:transparent;border-radius:50%;animation:rot 1s linear infinite;vertical-align:middle}\n"
    "@keyframes rot{to{transform:rotate(360deg)}}\n"
    "[dir=rtl] .sub{letter-spacing:0}\n"
    "/* Tighter sizes so the page fits one 1080p screen (same layout) */\n"
    "body{font-size:15px;line-height:1.3}\n"
    ".wrap{padding:8px 20px 8px}\n"
    ".bar{padding:2px 0 8px;margin-bottom:8px;gap:10px}\n"
    ".brand h1{font-size:22px}\n"
    ".ver{font-size:12px;margin-top:3px}\n"
    ".by{font-size:12px}\n"
    ".live{padding:6px 14px;font-size:14px}\n"
    ".live i{width:11px;height:11px}\n"
    ".grid{grid-gap:12px}\n"
    ".panel{padding:10px 16px;margin-bottom:10px}\n"
    ".hero{padding:10px 16px}\n"
    ".label{margin:0 0 6px;font-size:12px}\n"
    ".row{padding:3px 0}\n"
    ".dev{font-size:19px;margin:0 0 4px}\n"
    ".meter{height:9px;margin:1px 0 5px}\n"
    ".big{font-size:19px}\n"
    "input[type=range]{height:34px;margin:0 0 4px}\n"
    ".btns{gap:8px}\n"
    "button{min-height:44px;min-width:130px;font-size:16px}\n"
    "button.xl{min-height:52px;font-size:19px}\n"
    ".hint{margin:6px 0 2px;font-size:13px}\n"
    ".sub{margin:10px 0 2px;font-size:12px}\n"
    ".dl{padding:4px 0;gap:10px}\n"
    ".dl b{font-size:17px}\n"
    ".dl .ico{width:34px}\n"
    ".dl .acts{gap:8px}.dl .acts button{min-width:110px;min-height:40px}\n"
    ".dl button{min-width:110px}\n"
    ".msg{min-height:0}\n"
    ".msg:empty{display:none}\n"
    "footer{font-size:12px;padding-top:6px}\n"
    "#langbtn{min-height:40px;font-size:13px}\n"
    ".langopt{min-height:44px;font-size:15px}\n"
    "#savedlist,#devlist{max-height:22vh;overflow-y:auto}\n"
    "/* Full-width on TV screens (same order, just wider) */\n"
    ".wrap{max-width:96vw;padding:8px 2vw 4px}\n"
    "@media(min-width:1400px){\n"
    "body{font-size:16px}\n"
    ".grid{grid-gap:1.4vw}\n"
    ".panel{padding:12px 1.3vw;margin-bottom:1.1vw}\n"
    ".hero{padding:12px 1.3vw}\n"
    ".bar{margin-bottom:10px}\n"
    ".brand h1{font-size:25px}\n"
    ".dev,.big{font-size:21px}\n"
    ".dl b{font-size:18px}\n"
    "#savedlist{max-height:19vh}#devlist{max-height:15vh}\n"
    ".dl{padding:3px 0}\n"
    ".hint{margin:4px 0 0}\n"
    ".sub{margin:6px 0 2px}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body><div class=\"wrap\">\n"
    "<div class=\"bar\">\n"
    "<div class=\"brand\"><h1>Hear<b>Bridge</b> PS5</h1><span class=\"ver\" id=\"ver\">-</span><span class=\"by\">Developed by X-F1REBALL-X</span></div>\n"
    "<div class=\"live\" id=\"live\"><i></i><span id=\"state\">-</span></div>\n"
    "<div id=\"langbox\"><button type=\"button\" id=\"langbtn\" aria-haspopup=\"true\"><span data-i18n=\"language\">Language</span></button><div id=\"langlist\" role=\"menu\"></div></div>\n"
    "</div>\n"
    "<div class=\"msg\" id=\"msg\"></div>\n"
    "<div class=\"panel hero\" id=\"devpanel\"><p class=\"label\" data-i18n=\"devices\">Devices</p>\n"
    "<div class=\"btns\"><button id=\"scan\" class=\"act xl\" data-i18n=\"scan\">Scan for devices</button></div>\n"
    "<p class=\"k hint\" data-i18n=\"scanHint\">Put the headphones in pairing mode, then press Scan.</p>\n"
    "<p class=\"sub\" data-i18n=\"saved\">Saved headphones</p><div id=\"savedlist\"></div>\n"
    "<p class=\"sub\"><span data-i18n=\"found\">Found nearby</span> <span id=\"scanning\" class=\"spin\" style=\"display:none\"></span></p><div id=\"devlist\"></div>\n"
    "</div>\n"
    "<div class=\"grid\">\n"
    "<div>\n"
    "<div class=\"panel\"><p class=\"label\" data-i18n=\"status\">Status</p>\n"
    "<p class=\"dev\" id=\"dev\">-</p>\n"
    "<div id=\"stats\" style=\"display:none\">\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"packets\">Packets / SBC frames</span><span class=\"v\" id=\"pk\">-</span></div>\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"format\">Format</span><span class=\"v\" id=\"fmt\">-</span></div>\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"avrcp\">AVRCP</span><span class=\"v\" id=\"av\">-</span></div>\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"capPeak\">Capture peak</span><span class=\"v\" id=\"pkv\">-</span></div>\n"
    "<div class=\"meter\"><div id=\"m1\"></div></div>\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"outPeak\">Output peak</span><span class=\"v\" id=\"opv\">-</span></div>\n"
    "<div class=\"meter\"><div id=\"m2\"></div></div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"panel\"><p class=\"label\" data-i18n=\"connection\">Connection</p>\n"
    "<div class=\"btns\"><button id=\"stop\" class=\"red\" data-i18n=\"stop\">Stop HearBridge</button></div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"panel\"><p class=\"label\" data-i18n=\"volume\">Volume</p>\n"
    "<div class=\"row\"><span data-i18n=\"boost\">Boost (software gain)</span><span class=\"big\" id=\"gv\">-</span></div>\n"
    "<input type=\"range\" id=\"gain\" min=\"0\" max=\"500\" step=\"10\">\n"
    "<div class=\"row\"><span data-i18n=\"headset\">Headset volume (AVRCP)</span><span class=\"big\" id=\"hv\">-</span></div>\n"
    "<input type=\"range\" id=\"hs\" min=\"0\" max=\"127\" step=\"1\">\n"
    "<div class=\"btns\"><button id=\"mute\" data-i18n=\"mute\">Mute</button><button id=\"tone\" data-i18n=\"tone\">Test tone</button></div>\n"
    "</div>\n"
    "</div>\n"
    "<footer data-i18n=\"footer\">Closing this page leaves HearBridge running.</footer>\n"
    "</div>\n"
    "<script>\n"
    "var I18N={\"langs\":[{\"code\":\"en\",\"name\":\"English\",\"rtl\":false},{\"code\":\"ar\",\"name\":\"العربية\",\"rtl\":true},{\"code\":\"es\",\"name\":\"Español\",\"rtl\":false},{\"code\":\"fr\",\"name\":\"Français\",\"rtl\":false},{\"code\":\"de\",\"name\":\"Deutsch\",\"rtl\":false},{\"code\":\"pt\",\"name\":\"Português\",\"rtl\":false},{\"code\":\"ru\",\"name\":\"Русский\",\"rtl\":false},{\"code\":\"ja\",\"name\":\"日本語\",\"rtl\":false},{\"code\":\"zh\",\"name\":\"中文\",\"rtl\":false},{\"code\":\"it\",\"name\":\"Italiano\",\"rtl\":false},{\"code\":\"he\",\"name\":\"עברית\",\"rtl\":true}],\"strings\":{\"en\":{\"language\":\"Language\",\"status\":\"Status\",\"starting\":\"Starting\",\"connecting\":\"Connecting\",\"streaming\":\"Streaming\",\"reconnecting\":\"Reconnecting\",\"paused\":\"Not connected\",\"device\":\"Device\",\"packets\":\"Packets / SBC frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"not connected\",\"avrcpConn\":\"connected\",\"avrcpAbs\":\"absolute volume\",\"notif\":\"notifications\",\"capPeak\":\"Capture peak\",\"outPeak\":\"Output peak\",\"volume\":\"Volume\",\"boost\":\"Boost (software gain)\",\"headset\":\"Headset volume (AVRCP)\",\"mute\":\"Mute\",\"unmute\":\"Unmute\",\"tone\":\"Test tone\",\"toneOn\":\"Tone on\",\"connection\":\"Connection\",\"connect\":\"Connect\",\"disconnect\":\"Disconnect\",\"stop\":\"Stop HearBridge\",\"stopConfirm\":\"Stop HearBridge?\",\"unreachable\":\"Not reachable - is HearBridge running?\",\"queue\":\"queue\",\"footer\":\"Closing this page leaves HearBridge running. Use Stop before loading the ELF again.\",\"devices\":\"Devices\",\"scanning\":\"Scanning\",\"waiting-selection\":\"Choose your headphones\",\"pairing\":\"Pairing\",\"choose\":\"Choose\",\"noDevices\":\"No audio devices found yet.\",\"pairHint\":\"Press Scan again to refresh the list.\",\"error\":\"Error\",\"connected\":\"Connected\",\"scan\":\"Scan for devices\",\"reconnect\":\"Reconnect\",\"saved\":\"Saved headphones\",\"noSaved\":\"No saved headphones yet.\",\"found\":\"Found nearby\",\"forget\":\"Forget\",\"forgetConfirm\":\"Forget this device?\",\"current\":\"In use\",\"connectTo\":\"Connect\",\"scanHint\":\"Put the headphones in pairing mode and press Scan. The scan takes about 20 seconds.\",\"signal\":\"Signal\",\"perPkt\":\"frames/packet\",\"notConnected\":\"Not connected\",\"disconnected\":\"Not connected\"},\"ar\":{\"language\":\"اللغة\",\"status\":\"الحالة\",\"starting\":\"جارٍ البدء\",\"connecting\":\"جارٍ الاتصال\",\"streaming\":\"يتم البث\",\"reconnecting\":\"إعادة الاتصال\",\"paused\":\"غير متصل\",\"device\":\"الجهاز\",\"packets\":\"الحزم / إطارات SBC\",\"format\":\"التنسيق\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"غير متصل\",\"avrcpConn\":\"متصل\",\"avrcpAbs\":\"مستوى صوت مطلق\",\"notif\":\"إشعارات\",\"capPeak\":\"ذروة الالتقاط\",\"outPeak\":\"ذروة الإخراج\",\"volume\":\"مستوى الصوت\",\"boost\":\"تعزيز (كسب برمجي)\",\"headset\":\"صوت السماعة (AVRCP)\",\"mute\":\"كتم\",\"unmute\":\"إلغاء الكتم\",\"tone\":\"نغمة اختبار\",\"toneOn\":\"النغمة تعمل\",\"connection\":\"الاتصال\",\"connect\":\"اتصال\",\"disconnect\":\"قطع الاتصال\",\"stop\":\"إيقاف HearBridge\",\"stopConfirm\":\"إيقاف HearBridge؟\",\"unreachable\":\"تعذّر الوصول - هل HearBridge يعمل؟\",\"queue\":\"قائمة الانتظار\",\"footer\":\"إغلاق هذه الصفحة يُبقي HearBridge قيد التشغيل. استخدم «إيقاف» قبل تحميل ملف ELF مرة أخرى.\",\"devices\":\"الأجهزة\",\"scanning\":\"جارٍ البحث\",\"waiting-selection\":\"اختر سماعاتك\",\"pairing\":\"جارٍ الإقران\",\"choose\":\"اختيار\",\"noDevices\":\"لم يُعثر على أجهزة صوت بعد.\",\"pairHint\":\"اضغط «البحث» مرة أخرى لتحديث القائمة.\",\"error\":\"خطأ\",\"connected\":\"متصل\",\"scan\":\"البحث عن أجهزة\",\"reconnect\":\"إعادة الاتصال\",\"saved\":\"السماعات المحفوظة\",\"noSaved\":\"لا توجد سماعات محفوظة بعد.\",\"found\":\"أجهزة قريبة\",\"forget\":\"نسيان\",\"forgetConfirm\":\"هل تريد نسيان هذا الجهاز؟\",\"current\":\"قيد الاستخدام\",\"connectTo\":\"اتصال\",\"scanHint\":\"ضع السماعات في وضع الإقران واضغط «البحث». يستغرق البحث نحو 20 ثانية.\",\"signal\":\"الإشارة\",\"perPkt\":\"إطار/حزمة\",\"notConnected\":\"غير متصل\",\"disconnected\":\"غير متصل\"},\"es\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitiendo\",\"reconnecting\":\"Reconectando\",\"paused\":\"No conectado\",\"device\":\"Dispositivo\",\"packets\":\"Paquetes / tramas SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"no conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volumen absoluto\",\"notif\":\"notificaciones\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de salida\",\"volume\":\"Volumen\",\"boost\":\"Refuerzo (ganancia por software)\",\"headset\":\"Volumen de los auriculares (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Activar sonido\",\"tone\":\"Tono de prueba\",\"toneOn\":\"Tono activo\",\"connection\":\"Conexión\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Detener HearBridge\",\"stopConfirm\":\"¿Detener HearBridge?\",\"unreachable\":\"Sin respuesta: ¿está HearBridge en ejecución?\",\"queue\":\"cola\",\"footer\":\"Cerrar esta página deja HearBridge en marcha. Usa Detener antes de volver a cargar el ELF.\",\"devices\":\"Dispositivos\",\"scanning\":\"Buscando\",\"waiting-selection\":\"Elige tus auriculares\",\"pairing\":\"Emparejando\",\"choose\":\"Elegir\",\"noDevices\":\"Aún no se encontraron dispositivos de audio.\",\"pairHint\":\"Pulsa Buscar de nuevo para actualizar la lista.\",\"error\":\"Error\",\"connected\":\"Conectado\",\"scan\":\"Buscar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Auriculares guardados\",\"noSaved\":\"Aún no hay auriculares guardados.\",\"found\":\"Encontrados cerca\",\"forget\":\"Olvidar\",\"forgetConfirm\":\"¿Olvidar este dispositivo?\",\"current\":\"En uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Pon los auriculares en modo de emparejamiento y pulsa Buscar. La búsqueda dura unos 20 segundos.\",\"signal\":\"Señal\",\"perPkt\":\"tramas/paquete\",\"notConnected\":\"No conectado\",\"disconnected\":\"No conectado\"},\"fr\":{\"language\":\"Langue\",\"status\":\"État\",\"starting\":\"Démarrage\",\"connecting\":\"Connexion\",\"streaming\":\"Diffusion\",\"reconnecting\":\"Reconnexion\",\"paused\":\"Non connecté\",\"device\":\"Appareil\",\"packets\":\"Paquets / trames SBC\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connecté\",\"avrcpConn\":\"connecté\",\"avrcpAbs\":\"volume absolu\",\"notif\":\"notifications\",\"capPeak\":\"Crête de capture\",\"outPeak\":\"Crête de sortie\",\"volume\":\"Volume\",\"boost\":\"Amplification (gain logiciel)\",\"headset\":\"Volume du casque (AVRCP)\",\"mute\":\"Couper le son\",\"unmute\":\"Rétablir le son\",\"tone\":\"Son de test\",\"toneOn\":\"Son actif\",\"connection\":\"Connexion\",\"connect\":\"Connecter\",\"disconnect\":\"Déconnecter\",\"stop\":\"Arrêter HearBridge\",\"stopConfirm\":\"Arrêter HearBridge ?\",\"unreachable\":\"Injoignable : HearBridge est-il lancé ?\",\"queue\":\"file\",\"footer\":\"Fermer cette page laisse HearBridge actif. Utilisez Arrêter avant de recharger l'ELF.\",\"devices\":\"Appareils\",\"scanning\":\"Recherche\",\"waiting-selection\":\"Choisissez votre casque\",\"pairing\":\"Appairage\",\"choose\":\"Choisir\",\"noDevices\":\"Aucun appareil audio trouvé pour l'instant.\",\"pairHint\":\"Appuyez à nouveau sur Rechercher pour actualiser la liste.\",\"error\":\"Erreur\",\"connected\":\"Connecté\",\"scan\":\"Rechercher des appareils\",\"reconnect\":\"Reconnecter\",\"saved\":\"Casques enregistrés\",\"noSaved\":\"Aucun casque enregistré pour l'instant.\",\"found\":\"Trouvés à proximité\",\"forget\":\"Oublier\",\"forgetConfirm\":\"Oublier cet appareil ?\",\"current\":\"Utilisé\",\"connectTo\":\"Connecter\",\"scanHint\":\"Mettez le casque en mode appairage et appuyez sur Rechercher. La recherche dure environ 20 secondes.\",\"signal\":\"Signal\",\"perPkt\":\"trames/paquet\",\"notConnected\":\"Non connecté\",\"disconnected\":\"Non connecté\"},\"de\":{\"language\":\"Sprache\",\"status\":\"Status\",\"starting\":\"Startet\",\"connecting\":\"Verbinde\",\"streaming\":\"Überträgt\",\"reconnecting\":\"Verbinde neu\",\"paused\":\"Nicht verbunden\",\"device\":\"Gerät\",\"packets\":\"Pakete / SBC-Frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"nicht verbunden\",\"avrcpConn\":\"verbunden\",\"avrcpAbs\":\"absolute Lautstärke\",\"notif\":\"Benachrichtigungen\",\"capPeak\":\"Aufnahme-Spitze\",\"outPeak\":\"Ausgabe-Spitze\",\"volume\":\"Lautstärke\",\"boost\":\"Verstärkung (Software)\",\"headset\":\"Kopfhörer-Lautstärke (AVRCP)\",\"mute\":\"Stumm\",\"unmute\":\"Ton an\",\"tone\":\"Testton\",\"toneOn\":\"Ton läuft\",\"connection\":\"Verbindung\",\"connect\":\"Verbinden\",\"disconnect\":\"Trennen\",\"stop\":\"HearBridge beenden\",\"stopConfirm\":\"HearBridge beenden?\",\"unreachable\":\"Nicht erreichbar – läuft HearBridge?\",\"queue\":\"Warteschlange\",\"footer\":\"Diese Seite zu schließen lässt HearBridge weiterlaufen. Vor dem erneuten Laden der ELF „Beenden“ verwenden.\",\"devices\":\"Geräte\",\"scanning\":\"Suche\",\"waiting-selection\":\"Kopfhörer auswählen\",\"pairing\":\"Kopplung\",\"choose\":\"Auswählen\",\"noDevices\":\"Noch keine Audiogeräte gefunden.\",\"pairHint\":\"Drücke erneut Suchen, um die Liste zu aktualisieren.\",\"error\":\"Fehler\",\"connected\":\"Verbunden\",\"scan\":\"Nach Geräten suchen\",\"reconnect\":\"Neu verbinden\",\"saved\":\"Gespeicherte Kopfhörer\",\"noSaved\":\"Noch keine gespeicherten Kopfhörer.\",\"found\":\"In der Nähe gefunden\",\"forget\":\"Entfernen\",\"forgetConfirm\":\"Dieses Gerät entfernen?\",\"current\":\"In Verwendung\",\"connectTo\":\"Verbinden\",\"scanHint\":\"Versetze die Kopfhörer in den Kopplungsmodus und drücke Suchen. Die Suche dauert etwa 20 Sekunden.\",\"signal\":\"Signal\",\"perPkt\":\"Frames/Paket\",\"notConnected\":\"Nicht verbunden\",\"disconnected\":\"Nicht verbunden\"},\"pt\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitindo\",\"reconnecting\":\"Reconectando\",\"paused\":\"Não conectado\",\"device\":\"Dispositivo\",\"packets\":\"Pacotes / quadros SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"não conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volume absoluto\",\"notif\":\"notificações\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de saída\",\"volume\":\"Volume\",\"boost\":\"Reforço (ganho por software)\",\"headset\":\"Volume do fone (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Reativar som\",\"tone\":\"Tom de teste\",\"toneOn\":\"Tom ligado\",\"connection\":\"Conexão\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Parar o HearBridge\",\"stopConfirm\":\"Parar o HearBridge?\",\"unreachable\":\"Sem resposta: o HearBridge está em execução?\",\"queue\":\"fila\",\"footer\":\"Fechar esta página mantém o HearBridge em execução. Use Parar antes de carregar o ELF novamente.\",\"devices\":\"Dispositivos\",\"scanning\":\"Procurando\",\"waiting-selection\":\"Escolha seus fones\",\"pairing\":\"Pareando\",\"choose\":\"Escolher\",\"noDevices\":\"Nenhum dispositivo de áudio encontrado ainda.\",\"pairHint\":\"Toque em Procurar novamente para atualizar a lista.\",\"error\":\"Erro\",\"connected\":\"Conectado\",\"scan\":\"Procurar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Fones salvos\",\"noSaved\":\"Ainda não há fones salvos.\",\"found\":\"Encontrados por perto\",\"forget\":\"Esquecer\",\"forgetConfirm\":\"Esquecer este dispositivo?\",\"current\":\"Em uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Coloque os fones no modo de pareamento e toque em Procurar. A busca leva cerca de 20 segundos.\",\"signal\":\"Sinal\",\"perPkt\":\"quadros/pacote\",\"notConnected\":\"Não conectado\",\"disconnected\":\"Não conectado\"},\"ru\":{\"language\":\"Язык\",\"status\":\"Состояние\",\"starting\":\"Запуск\",\"connecting\":\"Подключение\",\"streaming\":\"Передача\",\"reconnecting\":\"Переподключение\",\"paused\":\"Не подключено\",\"device\":\"Устройство\",\"packets\":\"Пакеты / кадры SBC\",\"format\":\"Формат\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"не подключено\",\"avrcpConn\":\"подключено\",\"avrcpAbs\":\"абсолютная громкость\",\"notif\":\"уведомления\",\"capPeak\":\"Пик захвата\",\"outPeak\":\"Пик вывода\",\"volume\":\"Громкость\",\"boost\":\"Усиление (программное)\",\"headset\":\"Громкость наушников (AVRCP)\",\"mute\":\"Без звука\",\"unmute\":\"Включить звук\",\"tone\":\"Тестовый тон\",\"toneOn\":\"Тон включён\",\"connection\":\"Подключение\",\"connect\":\"Подключить\",\"disconnect\":\"Отключить\",\"stop\":\"Остановить HearBridge\",\"stopConfirm\":\"Остановить HearBridge?\",\"unreachable\":\"Нет ответа — HearBridge запущен?\",\"queue\":\"очередь\",\"footer\":\"Если закрыть страницу, HearBridge продолжит работу. Перед повторной загрузкой ELF нажмите «Остановить».\",\"devices\":\"Устройства\",\"scanning\":\"Поиск\",\"waiting-selection\":\"Выберите наушники\",\"pairing\":\"Сопряжение\",\"choose\":\"Выбрать\",\"noDevices\":\"Аудиоустройства пока не найдены.\",\"pairHint\":\"Нажмите «Искать» ещё раз, чтобы обновить список.\",\"error\":\"Ошибка\",\"connected\":\"Подключено\",\"scan\":\"Искать устройства\",\"reconnect\":\"Переподключить\",\"saved\":\"Сохранённые наушники\",\"noSaved\":\"Сохранённых наушников пока нет.\",\"found\":\"Найдены поблизости\",\"forget\":\"Забыть\",\"forgetConfirm\":\"Забыть это устройство?\",\"current\":\"Используется\",\"connectTo\":\"Подключить\",\"scanHint\":\"Переведите наушники в режим сопряжения и нажмите «Искать». Поиск занимает около 20 секунд.\",\"signal\":\"Сигнал\",\"perPkt\":\"кадров/пакет\",\"notConnected\":\"Не подключено\",\"disconnected\":\"Не подключено\"},\"ja\":{\"language\":\"言語\",\"status\":\"状態\",\"starting\":\"起動中\",\"connecting\":\"接続中\",\"streaming\":\"ストリーミング中\",\"reconnecting\":\"再接続中\",\"paused\":\"未接続\",\"device\":\"デバイス\",\"packets\":\"パケット / SBCフレーム\",\"format\":\"形式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未接続\",\"avrcpConn\":\"接続済み\",\"avrcpAbs\":\"絶対音量\",\"notif\":\"通知\",\"capPeak\":\"キャプチャのピーク\",\"outPeak\":\"出力のピーク\",\"volume\":\"音量\",\"boost\":\"ブースト（ソフトウェアゲイン）\",\"headset\":\"ヘッドホンの音量（AVRCP）\",\"mute\":\"ミュート\",\"unmute\":\"ミュート解除\",\"tone\":\"テストトーン\",\"toneOn\":\"トーン再生中\",\"connection\":\"接続\",\"connect\":\"接続\",\"disconnect\":\"切断\",\"stop\":\"HearBridge を停止\",\"stopConfirm\":\"HearBridge を停止しますか？\",\"unreachable\":\"応答なし - HearBridge は動作中ですか？\",\"queue\":\"キュー\",\"footer\":\"このページを閉じても HearBridge は動作を続けます。ELF を再読み込みする前に「停止」を使ってください。\",\"devices\":\"デバイス\",\"scanning\":\"検索中\",\"waiting-selection\":\"ヘッドホンを選択\",\"pairing\":\"ペアリング中\",\"choose\":\"選択\",\"noDevices\":\"オーディオデバイスはまだ見つかっていません。\",\"pairHint\":\"リストを更新するには、もう一度「検索」を押してください。\",\"error\":\"エラー\",\"connected\":\"接続済み\",\"scan\":\"デバイスを検索\",\"reconnect\":\"再接続\",\"saved\":\"保存したヘッドホン\",\"noSaved\":\"保存したヘッドホンはまだありません。\",\"found\":\"近くで見つかったデバイス\",\"forget\":\"削除\",\"forgetConfirm\":\"このデバイスを削除しますか？\",\"current\":\"使用中\",\"connectTo\":\"接続\",\"scanHint\":\"ヘッドホンをペアリングモードにして「検索」を押してください。検索には約20秒かかります。\",\"signal\":\"信号\",\"perPkt\":\"フレーム/パケット\",\"notConnected\":\"未接続\",\"disconnected\":\"未接続\"},\"zh\":{\"language\":\"语言\",\"status\":\"状态\",\"starting\":\"正在启动\",\"connecting\":\"正在连接\",\"streaming\":\"正在传输\",\"reconnecting\":\"正在重新连接\",\"paused\":\"未连接\",\"device\":\"设备\",\"packets\":\"数据包 / SBC 帧\",\"format\":\"格式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未连接\",\"avrcpConn\":\"已连接\",\"avrcpAbs\":\"绝对音量\",\"notif\":\"通知\",\"capPeak\":\"采集峰值\",\"outPeak\":\"输出峰值\",\"volume\":\"音量\",\"boost\":\"增益（软件放大）\",\"headset\":\"耳机音量（AVRCP）\",\"mute\":\"静音\",\"unmute\":\"取消静音\",\"tone\":\"测试音\",\"toneOn\":\"测试音开启\",\"connection\":\"连接\",\"connect\":\"连接\",\"disconnect\":\"断开\",\"stop\":\"停止 HearBridge\",\"stopConfirm\":\"停止 HearBridge？\",\"unreachable\":\"无法访问——HearBridge 是否在运行？\",\"queue\":\"队列\",\"footer\":\"关闭此页面后 HearBridge 仍会运行。再次加载 ELF 前请先点“停止”。\",\"devices\":\"设备\",\"scanning\":\"正在搜索\",\"waiting-selection\":\"选择你的耳机\",\"pairing\":\"正在配对\",\"choose\":\"选择\",\"noDevices\":\"尚未找到音频设备。\",\"pairHint\":\"再次按“搜索”即可刷新列表。\",\"error\":\"错误\",\"connected\":\"已连接\",\"scan\":\"搜索设备\",\"reconnect\":\"重新连接\",\"saved\":\"已保存的耳机\",\"noSaved\":\"还没有已保存的耳机。\",\"found\":\"附近找到的设备\",\"forget\":\"忘记\",\"forgetConfirm\":\"忘记此设备？\",\"current\":\"使用中\",\"connectTo\":\"连接\",\"scanHint\":\"让耳机进入配对模式，然后按“搜索”。搜索大约需要 20 秒。\",\"signal\":\"信号\",\"perPkt\":\"帧/包\",\"notConnected\":\"未连接\",\"disconnected\":\"未连接\"},\"it\":{\"language\":\"Lingua\",\"status\":\"Stato\",\"starting\":\"Avvio\",\"connecting\":\"Connessione\",\"streaming\":\"In streaming\",\"reconnecting\":\"Riconnessione\",\"paused\":\"Non connesso\",\"device\":\"Dispositivo\",\"packets\":\"Pacchetti / frame SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connesso\",\"avrcpConn\":\"connesso\",\"avrcpAbs\":\"volume assoluto\",\"notif\":\"notifiche\",\"capPeak\":\"Picco di cattura\",\"outPeak\":\"Picco di uscita\",\"volume\":\"Volume\",\"boost\":\"Amplificazione (guadagno software)\",\"headset\":\"Volume cuffie (AVRCP)\",\"mute\":\"Muto\",\"unmute\":\"Riattiva audio\",\"tone\":\"Tono di prova\",\"toneOn\":\"Tono attivo\",\"connection\":\"Connessione\",\"connect\":\"Connetti\",\"disconnect\":\"Disconnetti\",\"stop\":\"Arresta HearBridge\",\"stopConfirm\":\"Arrestare HearBridge?\",\"unreachable\":\"Non raggiungibile: HearBridge è in esecuzione?\",\"queue\":\"coda\",\"footer\":\"Chiudere questa pagina lascia HearBridge attivo. Usa Arresta prima di ricaricare l'ELF.\",\"devices\":\"Dispositivi\",\"scanning\":\"Ricerca\",\"waiting-selection\":\"Scegli le cuffie\",\"pairing\":\"Abbinamento\",\"choose\":\"Scegli\",\"noDevices\":\"Nessun dispositivo audio trovato finora.\",\"pairHint\":\"Premi di nuovo Cerca per aggiornare l'elenco.\",\"error\":\"Errore\",\"connected\":\"Connesso\",\"scan\":\"Cerca dispositivi\",\"reconnect\":\"Riconnetti\",\"saved\":\"Cuffie salvate\",\"noSaved\":\"Nessuna cuffia salvata.\",\"found\":\"Trovati nelle vicinanze\",\"forget\":\"Dimentica\",\"forgetConfirm\":\"Dimenticare questo dispositivo?\",\"current\":\"In uso\",\"connectTo\":\"Connetti\",\"scanHint\":\"Metti le cuffie in modalità di abbinamento e premi Cerca. La ricerca dura circa 20 secondi.\",\"signal\":\"Segnale\",\"perPkt\":\"frame/pacchetto\",\"notConnected\":\"Non connesso\",\"disconnected\":\"Non connesso\"},\"he\":{\"language\":\"שפה\",\"status\":\"מצב\",\"starting\":\"מתחיל\",\"connecting\":\"מתחבר\",\"streaming\":\"משדר\",\"reconnecting\":\"מתחבר מחדש\",\"paused\":\"לא מחובר\",\"device\":\"מכשיר\",\"packets\":\"חבילות / מסגרות SBC\",\"format\":\"פורמט\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"לא מחובר\",\"avrcpConn\":\"מחובר\",\"avrcpAbs\":\"עוצמה מוחלטת\",\"notif\":\"התראות\",\"capPeak\":\"שיא לכידה\",\"outPeak\":\"שיא יציאה\",\"volume\":\"עוצמת שמע\",\"boost\":\"הגברה (תוכנה)\",\"headset\":\"עוצמת האוזניות (AVRCP)\",\"mute\":\"השתק\",\"unmute\":\"בטל השתקה\",\"tone\":\"צליל בדיקה\",\"toneOn\":\"צליל פועל\",\"connection\":\"חיבור\",\"connect\":\"התחבר\",\"disconnect\":\"התנתק\",\"stop\":\"עצור את HearBridge\",\"stopConfirm\":\"לעצור את HearBridge?\",\"unreachable\":\"אין תגובה - האם HearBridge פועל?\",\"queue\":\"תור\",\"footer\":\"סגירת הדף משאירה את HearBridge פועל. לחצו על עצירה לפני טעינת ה-ELF מחדש.\",\"devices\":\"מכשירים\",\"scanning\":\"סורק\",\"waiting-selection\":\"בחרו את האוזניות\",\"pairing\":\"מבצע צימוד\",\"choose\":\"בחר\",\"noDevices\":\"עדיין לא נמצאו מכשירי שמע.\",\"pairHint\":\"לחצו שוב על חיפוש כדי לרענן את הרשימה.\",\"error\":\"שגיאה\",\"connected\":\"מחובר\",\"scan\":\"חיפוש מכשירים\",\"reconnect\":\"התחברות מחדש\",\"saved\":\"אוזניות שמורות\",\"noSaved\":\"אין עדיין אוזניות שמורות.\",\"found\":\"נמצאו בקרבת מקום\",\"forget\":\"שכח\",\"forgetConfirm\":\"לשכוח את המכשיר הזה?\",\"current\":\"בשימוש\",\"connectTo\":\"התחבר\",\"scanHint\":\"העבירו את האוזניות למצב צימוד ולחצו על חיפוש. החיפוש נמשך כ-20 שניות.\",\"signal\":\"אות\",\"perPkt\":\"מסגרות/מנה\",\"notConnected\":\"לא מחובר\",\"disconnected\":\"לא מחובר\"}}};\n"
    "var S=null,busyG=0,busyH=0,LANG='en';\n"
    "function $(i){return document.getElementById(i)}\n"
    "function t(k){var d=I18N.strings[LANG]||I18N.strings.en;return d[k]||I18N.strings.en[k]||k}\n"
    "function info(c){for(var i=0;i<I18N.langs.length;i++)if(I18N.langs[i].code==c)return I18N.langs[i];return I18N.langs[0]}\n"
    "function setLang(c){var L=info(c);LANG=L.code;try{localStorage.setItem('hb_lang',LANG)}catch(e){}\n"
    "document.documentElement.lang=LANG;document.documentElement.dir=L.rtl?'rtl':'ltr';\n"
    "var n=document.querySelectorAll('[data-i18n]');for(var i=0;i<n.length;i++)n[i].textContent=t(n[i].getAttribute('data-i18n'));\n"
    "var o=$('langlist').getElementsByTagName('button');for(var i2=0;i2<o.length;i2++)o[i2].className='langopt'+(o[i2].getAttribute('data-code')==LANG?' on':'');$('langlist').className='';if(S)draw()}\n"
    "function buildLangs(){var h='',i,L;for(i=0;i<I18N.langs.length;i++){L=I18N.langs[i];\n"
    "h+='<button type=\"button\" class=\"langopt\" role=\"menuitem\" data-code=\"'+L.code+'\"'+(L.rtl?' dir=\"rtl\"':'')+'><span>'+L.name+'</span></button>'}\n"
    "$('langlist').innerHTML=h;var b=$('langlist').getElementsByTagName('button');\n"
    "for(i=0;i<b.length;i++)b[i].onclick=function(){setLang(this.getAttribute('data-code'))};\n"
    "$('langbtn').onclick=function(){$('langlist').className=$('langlist').className?'':'show'}}\n"
    "function req(p,cb){var x=new XMLHttpRequest();x.open('GET',p,true);x.timeout=4000;\n"
    "x.onload=function(){if(x.status==200){try{S=JSON.parse(x.responseText);draw()}catch(e){}}if(cb)cb()};\n"
    "x.onerror=x.ontimeout=function(){$('msg').textContent=t('unreachable');$('live').className='live bad';if(cb)cb()};\n"
    "x.send()}\n"
    "var devT=0;\n"
    "function esc(x){return String(x).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}\n"
    "var ICON={\n"
    "head:'<path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/>',\n"
    "spk:'<path d=\"M3 9h4l6-5v16l-6-5H3z\" fill=\"currentColor\"/><path d=\"M16 8a5 5 0 0 1 0 8M18.5 5a9 9 0 0 1 0 14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "tv:'<rect x=\"2\" y=\"4\" width=\"20\" height=\"13\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><path d=\"M8 21h8\" stroke=\"currentColor\" stroke-width=\"2.2\"/>',\n"
    "car:'<path d=\"M3 15l2-6h14l2 6v4H3z\" fill=\"currentColor\"/><circle cx=\"7\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/><circle cx=\"17\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/>',\n"
    "mic:'<rect x=\"9\" y=\"2\" width=\"6\" height=\"12\" rx=\"3\" fill=\"currentColor\"/><path d=\"M5 11a7 7 0 0 0 14 0M12 18v4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "note:'<path d=\"M9 17V5l11-2v12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><circle cx=\"6.5\" cy=\"17.5\" r=\"3\" fill=\"currentColor\"/><circle cx=\"17.5\" cy=\"15.5\" r=\"3\" fill=\"currentColor\"/>'};\n"
    "var KIND={headphones:'head',headset:'head',speaker:'spk',portable:'spk',hifi:'spk',car:'car',handsfree:'mic',tv:'tv',av:'tv',audio:'note'};\n"
    "function icon(k){return '<svg viewBox=\"0 0 24 24\" width=\"34\" height=\"34\" aria-hidden=\"true\">'+ICON[KIND[k]||'note']+'</svg>'}\n"
    "function kindOf(cod){var c=parseInt(cod,16)||0,maj=(c>>8)&31,min=(c>>2)&63;if(maj!=4)return 'audio';\n"
    "return {6:'headphones',1:'headset',5:'speaker',7:'portable',10:'hifi',8:'car',2:'handsfree',9:'tv',14:'tv',15:'tv'}[min]||'av'}\n"
    "function bars(r){if(r==null)return '';var n=r>-60?4:r>-70?3:r>-80?2:1,h='<span class=\"bars\" title=\"'+r+' dBm\">';\n"
    "for(var i=1;i<=4;i++)h+='<i class=\"'+(i<=n?'on':'')+'\" style=\"height:'+(i*4)+'px\"></i>';return h+'</span>'}\n"
    "function getj(p,cb){var x=new XMLHttpRequest();x.open('GET',p,true);x.timeout=4000;x.onload=function(){try{cb(JSON.parse(x.responseText))}catch(e){}};x.send()}\n"
    "function row(icon,name,meta,btns){return '<div class=\"dl\"><span class=\"ico\">'+icon+'</span><span class=\"nm\"><b>'+esc(name)+'</b><span class=\"k\" dir=\"ltr\">'+meta+'</span></span><span class=\"acts\">'+btns+'</span></div>'}\n"
    "function wire(id){var b=$(id).getElementsByTagName('button');for(var i=0;i<b.length;i++)b[i].onclick=function(){\n"
    "var a=this.getAttribute('data-addr'),f=this.getAttribute('data-forget');\n"
    "if(this.getAttribute('data-disc')){req('/api/disconnect');return}\n"
    "if(f){if(confirm(t('forgetConfirm')))req('/api/forget?addr='+a,saved);return}\n"
    "req('/api/select?addr='+a);this.textContent=t('connecting')+'…'}}\n"
    "var SAVL=null;\n"
    "function stOf(){return S?(S.paused?'paused':S.state):''}\n"
    "function linked(){var st=stOf();return st=='streaming'||st=='connected'}\n"
    "function badge(cur){var st=stOf();\n"
    "if(!cur)return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(linked())return '<span class=\"badge\">'+esc(t('connected'))+'</span>';\n"
    "if(st=='paused')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='disconnected')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='connecting'||st=='pairing')return '<span class=\"badge warn\">'+esc(t('connecting'))+'</span>';\n"
    "return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>'}\n"
    "function drawSaved(){if(!SAVL)return;var h='',i,d,on=linked(),st=stOf(),busy=st=='connecting'||st=='pairing';\n"
    "for(i=0;i<SAVL.length;i++){d=SAVL[i];\n"
    "h+=row(icon(d.kind),d.name||d.addr,esc(d.addr)+badge(d.current),\n"
    "(d.current&&on?'<button type=\"button\" data-disc=\"1\">'+esc(t('disconnect'))+'</button>'\n"
    ":d.current&&busy?'':'<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('connect'))+'</button>')\n"
    "+'<button type=\"button\" class=\"red\" data-forget=\"1\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('forget'))+'</button>')}\n"
    "var k=h+'|'+LANG;if(k==drawSaved.last)return;drawSaved.last=k;\n"
    "$('savedlist').innerHTML=h||'<p class=\"k\">'+esc(t('noSaved'))+'</p>';wire('savedlist')}\n"
    "function saved(){getj('/api/saved',function(j){var i;SAVL=j.devices;SAV={};for(i=0;i<SAVL.length;i++)SAV[SAVL[i].addr]=1;drawSaved()})}\n"
    "var SAV={},SHOW={headphones:1,headset:1,speaker:1,portable:1,hifi:1,handsfree:1},HEAD={headphones:1,headset:1};\n"
    "function devices(){getj('/api/devices',function(j){var h='',i,d,k;\n"
    "for(i=0;i<j.devices.length;i++){d=j.devices[i];if(SAV[d.addr])continue;k=d.kind||kindOf(d.cod);if(!SHOW[k]||(!d.name&&!HEAD[k]))continue;\n"
    "h+=row(icon(k),d.name||d.addr,esc(d.addr)+bars(d.rssi),'<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('connectTo'))+'</button>')}\n"
    "$('devlist').innerHTML=h||'<p class=\"k\">'+esc(t('noDevices'))+'</p>';wire('devlist')})}\n"
    "function pct(v){return Math.round(v)+'%'}\n"
    "function draw(){\n"
    "$('msg').textContent='';\n"
    "$('ver').textContent=S.version;\n"
    "var st=S.paused?'paused':S.state;\n"
    "$('state').textContent={reconnecting:1,disconnected:1,paused:1,error:1,idle:1,'waiting-selection':1}[st]?t('notConnected')+(st=='error'&&S.detail?' ('+S.detail.replace(/^error\\s*/,'')+')':''):(t(st)==st?st:t(st));\n"
    "$('live').className='live '+(st=='streaming'||st=='connected'?'ok':(st=='paused'||st=='disconnected'||st=='error'?'bad':'wait'));\n"
    "var on=!!S.connected,link=on||((st=='connecting'||st=='pairing')&&S.device);\n"
    "$('dev').textContent=link?(S.device||'-'):t('notConnected');$('stats').style.display=on?'':'none';\n"
    "if(!on){S.pkts=S.frames=S.backlog=S.sample_rate=0;S.peak=S.out_peak=0;S.avrcp={}}\n"
    "$('scanning').style.display=st=='scanning'?'':'none';\n"
    "if(Date.now()-devT>3000){devT=Date.now();devices();saved()}\n"
    "drawSaved();\n"
    "$('pk').textContent=S.pkts+' / '+S.frames+(S.backlog?' ('+t('queue')+' '+S.backlog+')':'');\n"
    "\n"
    "$('fmt').textContent=S.sample_rate?('SBC '+S.sample_rate+' Hz, bitpool '+S.bitpool+(S.bitpool_max>S.bitpool_min?' ('+S.bitpool_min+'–'+S.bitpool_max+')':'')+', '+S.per_packet+' '+t('perPkt')):'-';\n"
    "$('av').textContent=!S.avrcp.connected?t('avrcpNone'):(S.avrcp.absolute_volume?t('avrcpAbs'):t('avrcpConn'))+(S.avrcp.notifications?', '+t('notif'):'');\n"
    "$('pkv').textContent=S.peak.toFixed(3);$('m1').style.width=Math.min(100,S.peak*100)+'%';\n"
    "$('opv').textContent=S.out_peak.toFixed(3);$('m2').style.width=Math.min(100,S.out_peak*100)+'%';\n"
    "if(!busyG)$('gain').value=S.gain_pct;$('gv').textContent=pct(S.gain_pct);\n"
    "if(!busyH&&S.headset_volume>=0)$('hs').value=S.headset_volume;\n"
    "$('hv').textContent=S.headset_volume<0?'-':pct(S.headset_volume*100/127);\n"
    "\n"
    "$('mute').className=S.muted?'ember':'';$('mute').textContent=t(S.muted?'unmute':'mute');\n"
    "$('tone').className=S.tone?'act':'';$('tone').textContent=t(S.tone?'toneOn':'tone')}\n"
    "$('gain').oninput=function(){busyG=1;$('gv').textContent=pct(this.value)};\n"
    "$('gain').onchange=function(){req('/api/volume?pct='+this.value,function(){busyG=0})};\n"
    "$('hs').oninput=function(){busyH=1;$('hv').textContent=pct(this.value*100/127)};\n"
    "$('hs').onchange=function(){req('/api/headset?vol='+this.value,function(){busyH=0})};\n"
    "$('mute').onclick=function(){req('/api/mute?on='+(S&&S.muted?0:1))};\n"
    "$('tone').onclick=function(){req('/api/tone?on='+(S&&S.tone?0:1))};\n"
    "$('scan').onclick=function(){req('/api/scan');$('scanning').style.display=''};\n"
    "$('stop').onclick=function(){if(confirm(t('stopConfirm')))req('/api/stop')};\n"
    "buildLangs();\n"
    "(function(){var c=null,m=/[?&]lang=([a-z]{2})/.exec(location.search);if(m)c=m[1];else try{c=localStorage.getItem('hb_lang')}catch(e){}\n"
    "if(!c){var n=(navigator.language||'en').slice(0,2).toLowerCase();c=info(n).code==n?n:'en'}setLang(c)})();\n"
    "req('/api/status');setInterval(function(){req('/api/status')},1000);\n"
    "</script></body></html>\n";

#endif
