/* Generated from src/web/index.html + i18n.json by scripts/gen_webpage.py. */
#ifndef HEARBRIDGE_WEBPAGE_H
#define HEARBRIDGE_WEBPAGE_H

static const char HB_WEBPAGE[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<meta name=\"color-scheme\" content=\"dark\">\n"
    "<title>HearBridge PS5</title>\n"
    "<style>\n"
    ":root{--ink:#f4efe6;--mute:#9a948a;--void:#0c0b0f;--deck:#15131a;--card:#1f1b26;--edge:#2c2833;--edge2:#3a3543;\n"
    "--lime:#c8ff3d;--ember:#ff6a2b;--warn:#ffb23d;--bad:#ff3d5a;--gap:1rem;--sk:-12deg}\n"
    "*{box-sizing:border-box}\n"
    "html{background:var(--void);font-size:15px}\n"
    "body{margin:0;color:var(--ink);font:1rem/1.35 \"Bahnschrift\",\"DIN Alternate\",\"Segoe UI\",system-ui,sans-serif;\n"
    "background:repeating-linear-gradient(135deg,rgba(255,255,255,.016) 0 2px,transparent 2px 14px),\n"
    "radial-gradient(60vw 50vh at 100% 0,rgba(255,106,43,.13),transparent 60%),\n"
    "radial-gradient(50vw 50vh at 0 100%,rgba(200,255,61,.06),transparent 60%),var(--void);background-attachment:fixed}\n"
    "[dir=rtl]{--sk:12deg}\n"
    ".wrap{display:flex;flex-direction:column;padding:.9rem 1.2rem}\n"
    "/* header */\n"
    ".bar{display:flex;align-items:center;justify-content:space-between;padding:0 0 .8rem;margin-bottom:var(--gap);border-bottom:2px solid var(--edge)}\n"
    ".brand{display:flex;align-items:center;min-width:0}\n"
    ".logo{flex:0 0 auto;width:2.6rem;height:2.6rem;margin-inline-end:.8rem;display:flex;align-items:center;justify-content:center;color:var(--void);\n"
    "background:var(--lime);transform:skewX(var(--sk));box-shadow:0 0 1.2rem rgba(200,255,61,.25)}\n"
    ".logo svg{width:1.6rem;height:1.6rem;transform:skewX(calc(var(--sk)*-1))}\n"
    ".brand h1{margin:0;font-size:1.55rem;font-weight:900;letter-spacing:.22em;text-transform:uppercase;line-height:1.05;white-space:nowrap}\n"
    ".brand h1 b{color:var(--lime)}\n"
    ".meta{display:flex;align-items:center;margin-top:.2rem}\n"
    ".ver{color:var(--void);background:var(--ember);font-size:.72rem;font-weight:800;padding:0 .5em;margin-inline-end:.6em;letter-spacing:.06em;transform:skewX(var(--sk))}\n"
    ".by{color:var(--mute);font-size:.75rem;direction:ltr;unicode-bidi:isolate;white-space:nowrap}\n"
    ".live{display:flex;align-items:center;padding:.45rem 1.1rem;background:var(--deck);border:2px solid var(--edge);font-size:.9rem;font-weight:800;\n"
    "text-transform:uppercase;letter-spacing:.1em;white-space:nowrap;transform:skewX(var(--sk))}\n"
    ".live i,.live span{transform:skewX(calc(var(--sk)*-1))}\n"
    ".live i{width:.7rem;height:.7rem;margin-inline-end:.65rem;background:var(--mute);transform:rotate(45deg)}\n"
    ".live.ok{border-color:rgba(200,255,61,.45)}.live.ok i{background:var(--lime);box-shadow:0 0 .6rem var(--lime)}\n"
    ".live.wait{border-color:rgba(255,178,61,.45)}.live.wait i{background:var(--warn);animation:blink 1s infinite}\n"
    ".live.bad{border-color:rgba(255,61,90,.5)}.live.bad i{background:var(--bad)}\n"
    "@keyframes blink{50%{opacity:.25}}\n"
    "/* toast for errors: never pushes the layout */\n"
    ".msg{position:fixed;z-index:80;top:4.2rem;left:50%;transform:translateX(-50%);max-width:90vw;padding:.5rem 1.2rem;background:var(--bad);color:var(--void);font-weight:800;box-shadow:0 .6rem 2rem rgba(0,0,0,.6)}\n"
    ".msg:empty{display:none}\n"
    "/* dashboard */\n"
    ".grid{display:grid;grid-template-columns:minmax(0,1fr);grid-gap:var(--gap)}\n"
    ".col{display:flex;flex-direction:column}.col>.panel+.panel{margin-top:var(--gap)}\n"
    ".panel{position:relative;display:flex;flex-direction:column;min-height:0;padding:1rem 1.2rem 1.1rem;\n"
    "background:linear-gradient(180deg,rgba(255,255,255,.03),rgba(255,255,255,0) 6rem),var(--deck);\n"
    "border:1px solid var(--edge);border-inline-start:4px solid var(--ember);\n"
    "clip-path:polygon(0 0,calc(100% - 1.1rem) 0,100% 1.1rem,100% 100%,0 100%)}\n"
    "[dir=rtl] .panel{clip-path:polygon(1.1rem 0,100% 0,100% 100%,0 100%,0 1.1rem)}\n"
    ".hero{border-inline-start-color:var(--lime)}\n"
    ".label{display:flex;align-items:center;margin:0 0 .8rem;font-size:.78rem;font-weight:800;letter-spacing:.24em;text-transform:uppercase;color:var(--ember)}\n"
    ".label:after{content:\"\";flex:1;height:1px;margin-inline-start:.8rem;background:linear-gradient(90deg,var(--edge2),transparent)}\n"
    "[dir=rtl] .label:after{background:linear-gradient(270deg,var(--edge2),transparent)}\n"
    ".hero .label{color:var(--lime)}\n"
    ".k{color:var(--mute)}\n"
    ".v{font-weight:800;direction:ltr;unicode-bidi:isolate}\n"
    "/* buttons: skewed plate drawn by ::before so focus glow is never clipped */\n"
    "button{position:relative;z-index:0;min-height:2.9rem;padding:.3rem 1.2rem;font:inherit;font-size:1rem;font-weight:800;letter-spacing:.04em;\n"
    "color:var(--ink);background:none;border:0;cursor:pointer;white-space:nowrap;outline:none}\n"
    "button:before{content:\"\";position:absolute;z-index:-1;top:0;bottom:0;left:.35em;right:.35em;background:var(--card);border:2px solid var(--edge2);\n"
    "transform:skewX(var(--sk));transition:box-shadow .12s,border-color .12s,background .12s}\n"
    "button:hover:before,button:focus:before{border-color:var(--lime);box-shadow:0 0 0 3px rgba(200,255,61,.35),0 0 1rem rgba(200,255,61,.35)}\n"
    "button:focus{transform:scale(1.03);z-index:2}\n"
    "button.act{color:var(--void)}button.act:before{background:var(--lime);border-color:var(--lime)}\n"
    "button.act:focus:before{border-color:#fff;box-shadow:0 0 0 3px #fff,0 0 1rem rgba(200,255,61,.7)}\n"
    "button.ember{color:var(--void)}button.ember:before{background:var(--ember);border-color:var(--ember)}\n"
    "button.red{color:var(--bad)}button.red:before{border-color:rgba(255,61,90,.7)}\n"
    "button.red:hover:before,button.red:focus:before{border-color:var(--bad);background:rgba(255,61,90,.12);box-shadow:0 0 0 3px rgba(255,61,90,.35),0 0 1.4rem rgba(255,61,90,.35)}\n"
    ".btns{display:grid;grid-template-columns:1fr 1fr;grid-gap:.6rem}\n"
    "button.xl{width:100%;min-height:3.6rem;font-size:1.3rem;letter-spacing:.06em}\n"
    "[dir=rtl] .label,[dir=rtl] .live,[dir=rtl] button,html[lang=ja] .label,html[lang=zh] .label{letter-spacing:0}\n"
    "/* language menu */\n"
    "#langbox{position:relative;z-index:40}\n"
    "#langbtn{min-height:2.5rem;font-size:.85rem;text-transform:uppercase}\n"
    "#langbtn:before{background:var(--deck)}\n"
    "#langlist{display:none;position:absolute;right:0;top:calc(100% + .5rem);z-index:60;width:28rem;max-width:calc(100vw - 2rem);padding:.6rem;\n"
    "grid-template-columns:1fr 1fr;grid-gap:.3rem;background:var(--deck);border:2px solid var(--lime);box-shadow:0 1.2rem 2.5rem rgba(0,0,0,.75)}\n"
    "[dir=rtl] #langlist{right:auto;left:0}\n"
    "#langlist.show{display:grid}\n"
    ".langopt{width:100%;min-height:2.6rem;font-size:.95rem;font-weight:700;text-align:start;letter-spacing:0}\n"
    ".langopt:before{left:0;right:0;transform:none;background:var(--void);border-color:var(--edge)}\n"
    ".langopt.on{color:var(--void)}.langopt.on:before{background:var(--lime);border-color:var(--lime)}\n"
    "/* devices */\n"
    ".hint{margin:.55rem 0 0;font-size:.85rem}\n"
    ".sub{display:flex;align-items:center;margin:.9rem 0 .3rem;font-size:.74rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--lime)}\n"
    ".sub .spin{margin-inline-start:.6rem}\n"
    "[dir=rtl] .sub{letter-spacing:0}\n"
    ".list{overflow-y:auto;overflow-x:hidden;scrollbar-width:thin;scrollbar-color:#5a5466 rgba(255,255,255,.04)}\n"
    ".list::-webkit-scrollbar{width:6px}.list::-webkit-scrollbar-track{background:rgba(255,255,255,.04)}.list::-webkit-scrollbar-thumb{background:#5a5466}.list::-webkit-scrollbar-thumb:hover{background:var(--lime)}\n"
    ".list>p{margin:.4rem 0;font-size:.85rem}\n"
    ".dl{display:grid;grid-template-columns:auto minmax(0,1fr) auto;grid-gap:.75rem;align-items:center;min-height:3.4rem;padding:.3rem .6rem;border-bottom:1px solid var(--edge)}\n"
    ".dl:last-child{border-bottom:0}\n"
    ".dl .ico{display:flex;color:var(--lime)}.dl .ico svg{width:1.7rem;height:1.7rem}\n"
    ".dl .nm b{display:block;font-size:1.05rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;direction:ltr;unicode-bidi:isolate}\n"
    "[dir=rtl] .dl .nm b{text-align:right}\n"
    ".dl .nm .k{display:block;font-size:.8rem;white-space:nowrap;overflow:hidden;font-variant-numeric:tabular-nums}\n"
    "[dir=rtl] .dl .nm .k{text-align:right}\n"
    ".dl .acts{display:grid;grid-auto-flow:column;grid-gap:.4rem}\n"
    ".dl button{min-width:7.2rem;min-height:2.5rem;font-size:.9rem}\n"
    ".badge{display:inline-block;background:var(--lime);color:var(--void);font-size:.68rem;font-weight:900;padding:0 .45em;margin:0 .5em;vertical-align:.08em}\n"
    ".badge.warn{background:var(--warn);animation:blink 1.2s infinite}.badge.off{background:var(--edge2);color:var(--ink)}\n"
    ".bars{display:inline-flex;align-items:flex-end;height:.9rem;vertical-align:-.1em;margin:0 .45em}\n"
    ".bars i{width:.22rem;margin-right:.12rem;background:var(--edge2)}.bars i.on{background:var(--lime)}\n"
    ".bars i:nth-child(1){height:25%!important}.bars i:nth-child(2){height:50%!important}.bars i:nth-child(3){height:75%!important}.bars i:nth-child(4){height:100%!important}\n"
    ".spin{display:inline-block;width:.8rem;height:.8rem;border:2px solid var(--lime);border-right-color:transparent;border-radius:50%;animation:rot 1s linear infinite}\n"
    "@keyframes rot{to{transform:rotate(360deg)}}\n"
    "/* volume */\n"
    ".ctl{padding:.7rem .9rem .5rem;margin-bottom:.7rem;background:rgba(0,0,0,.22);border:1px solid var(--edge)}\n"
    ".ctl:focus-within{border-color:var(--lime);box-shadow:0 0 0 3px rgba(200,255,61,.3),0 0 1.2rem rgba(200,255,61,.18)}\n"
    ".row{display:flex;justify-content:space-between;align-items:baseline}\n"
    ".row>span:first-child{min-width:0;margin-inline-end:.8rem}\n"
    ".big{font-size:2rem;font-weight:900;line-height:1;color:var(--lime);direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums}\n"
    "input[type=range]{display:block;width:100%;height:1.5rem;margin:.6rem 0 .3rem;background:none;accent-color:var(--lime);-webkit-appearance:none;appearance:none;overflow:hidden;outline:none;cursor:pointer}\n"
    "input[type=range]::-webkit-slider-runnable-track{height:1.5rem;background:repeating-linear-gradient(90deg,transparent 0 calc(10% - 2px),rgba(255,255,255,.07) calc(10% - 2px) 10%),var(--void)}\n"
    "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:.55rem;height:1.5rem;background:#fff;box-shadow:-100vw 0 0 100vw rgba(200,255,61,.85)}\n"
    "[dir=rtl] input[type=range]::-webkit-slider-thumb{box-shadow:100vw 0 0 100vw rgba(200,255,61,.85)}\n"
    "input[type=range]::-moz-range-track{height:1.5rem;background:var(--void)}\n"
    "input[type=range]::-moz-range-progress{height:1.5rem;background:var(--lime)}\n"
    "input[type=range]::-moz-range-thumb{width:.55rem;height:1.5rem;border:0;border-radius:0;background:#fff}\n"
    ".vol .btns{margin-top:auto}\n"
    ".vol .btns button{min-height:3rem}\n"
    ".conn .note{margin:.7rem 0 0;font-size:.82rem}\n"
    "#stop{width:100%}\n"
    "/* status */\n"
    ".dev{margin:0 0 .8rem;font-size:1.6rem;font-weight:900;line-height:1.15;overflow-wrap:anywhere;direction:ltr;unicode-bidi:isolate}\n"
    "[dir=rtl] .dev{text-align:right}\n"
    "#stats[style*=none]+.idle{display:flex}\n"
    ".idle{display:none;flex:1;align-items:center;justify-content:center;color:var(--edge)}.idle svg{width:45%;max-width:12rem;height:auto}\n"
    "#stats{display:flex;flex-direction:column;flex:1;min-height:0}\n"
    ".tiles{display:grid;grid-template-columns:1fr 1fr;grid-gap:.6rem}\n"
    ".tile{padding:.55rem .8rem;background:rgba(0,0,0,.22);border:1px solid var(--edge);border-inline-start:2px solid var(--edge2)}\n"
    ".tile.w{grid-column:1/-1}\n"
    ".tile .k{display:block;font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.2rem}\n"
    "[dir=rtl] .tile .k{letter-spacing:0}\n"
    ".tile .v{display:block;font-size:1rem;line-height:1.25;font-variant-numeric:tabular-nums}\n"
    "[dir=rtl] .tile .v{text-align:right}\n"
    ".meters{margin-top:auto;padding-top:.9rem}\n"
    ".meters .row{font-size:.9rem}.meters .v{font-variant-numeric:tabular-nums}\n"
    ".meter{position:relative;height:1rem;margin:.3rem 0 .7rem;background:var(--void);overflow:hidden}\n"
    ".meter:last-child{margin-bottom:0}\n"
    ".meter div{height:100%;width:0;background:linear-gradient(90deg,var(--lime),var(--lime) 60%,var(--warn) 85%,var(--bad));background-size:100vw 100%;transition:width .3s}\n"
    ".meter:after{content:\"\";position:absolute;top:0;bottom:0;left:0;right:0;background:repeating-linear-gradient(90deg,transparent 0 .5rem,var(--void) .5rem .65rem)}\n"
    "[dir=rtl] .meter div{margin-right:0;margin-left:auto}\n"
    "/* mid widths: two columns, page may scroll */\n"
    "@media(min-width:760px){.grid{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.hero{grid-column:1/-1}}\n"
    "/* TV: one screen, no page scroll. Everything is rem, rem follows the viewport. */\n"
    "@media(min-width:1180px) and (min-height:600px){\n"
    "html{font-size:13px;font-size:clamp(12px,min(1.04vw,1.9vh),26px)}\n"
    ".wrap{height:100vh}\n"
    ".grid{flex:1;min-height:0;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr) minmax(0,1fr);grid-template-rows:minmax(0,1fr)}\n"
    ".hero{grid-column:auto}\n"
    ".col,.panel{min-height:0}\n"
    ".vol{flex:1}\n"
    "#savedlist{flex:0 1 auto;max-height:34%}\n"
    "#devlist{flex:1 1 0;min-height:4rem}\n"
    ".vol .ctl{flex:1;display:flex;flex-direction:column;justify-content:center;padding:.8rem 1rem}\n"
    ".vol .big{font-size:3rem}\n"
    ".vol input[type=range],.vol input[type=range]::-webkit-slider-runnable-track,.vol input[type=range]::-webkit-slider-thumb{height:2.2rem}\n"
    ".vol .btns button{min-height:3.4rem;font-size:1.1rem}\n"
    ".dev{font-size:2rem}\n"
    ".tiles{flex:1;grid-template-columns:1fr;grid-template-rows:1fr 1fr 1fr}\n"
    ".tile .k{font-size:.8rem;margin-bottom:.35rem}\n"
    ".tile{display:flex;flex-direction:column;justify-content:center;padding:.7rem 1rem}\n"
    ".tile .v{font-size:1.25rem}\n"
    ".meters .row{font-size:1rem}.meters .v{font-size:1.25rem}\n"
    ".meter{height:1.5rem}\n"
    "}\n"
    "@media(max-width:759px){\n"
    ".bar{flex-wrap:wrap}.brand{width:100%;margin-bottom:.7rem}\n"
    ".live{margin-inline-start:.3rem}\n"
    "#savedlist .dl{grid-template-columns:auto minmax(0,1fr)}#savedlist .acts{grid-column:1/-1;grid-auto-columns:1fr}\n"
    ".dl button{min-width:0}\n"
    ".msg{top:.6rem}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body><div class=\"wrap\">\n"
    "<header class=\"bar\">\n"
    "<div class=\"brand\"><span class=\"logo\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.4\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg></span>\n"
    "<div><h1>Hear<b>Bridge</b> PS5</h1><div class=\"meta\"><span class=\"ver\" id=\"ver\">-</span><span class=\"by\">Developed by X-F1REBALL-X</span></div></div></div>\n"
    "<div class=\"live\" id=\"live\"><i></i><span id=\"state\">-</span></div>\n"
    "<div id=\"langbox\"><button type=\"button\" id=\"langbtn\" aria-haspopup=\"true\"><span data-i18n=\"language\">Language</span></button><div id=\"langlist\" role=\"menu\"></div></div>\n"
    "</header>\n"
    "<div class=\"msg\" id=\"msg\"></div>\n"
    "<main class=\"grid\">\n"
    "<section class=\"panel hero\" id=\"devpanel\"><p class=\"label\" data-i18n=\"devices\">Devices</p>\n"
    "<button id=\"scan\" class=\"act xl\" data-i18n=\"scan\">Scan for devices</button>\n"
    "<p class=\"k hint\" data-i18n=\"scanHint\">Put the headphones in pairing mode, then press Scan.</p>\n"
    "<p class=\"sub\" data-i18n=\"saved\">Saved headphones</p><div id=\"savedlist\" class=\"list\"></div>\n"
    "<p class=\"sub\"><span data-i18n=\"found\">Found nearby</span><span id=\"scanning\" class=\"spin\" style=\"display:none\"></span></p><div id=\"devlist\" class=\"list\"></div>\n"
    "</section>\n"
    "<div class=\"col\">\n"
    "<section class=\"panel vol\"><p class=\"label\" data-i18n=\"volume\">Volume</p>\n"
    "<div class=\"ctl\"><div class=\"row\"><span data-i18n=\"boost\">Boost (software gain)</span><span class=\"big\" id=\"gv\">-</span></div>\n"
    "<input type=\"range\" id=\"gain\" min=\"0\" max=\"500\" step=\"10\"></div>\n"
    "<div class=\"ctl\"><div class=\"row\"><span data-i18n=\"headset\">Headset volume (AVRCP)</span><span class=\"big\" id=\"hv\">-</span></div>\n"
    "<input type=\"range\" id=\"hs\" min=\"0\" max=\"127\" step=\"1\"></div>\n"
    "<div class=\"btns\"><button id=\"mute\" data-i18n=\"mute\">Mute</button><button id=\"tone\" data-i18n=\"tone\">Test tone</button></div>\n"
    "</section>\n"
    "<section class=\"panel conn\"><p class=\"label\" data-i18n=\"connection\">Connection</p>\n"
    "<button id=\"stop\" class=\"red\" data-i18n=\"stop\">Stop HearBridge</button>\n"
    "<p class=\"k note\" data-i18n=\"footer\">Closing this page leaves HearBridge running.</p>\n"
    "</section>\n"
    "</div>\n"
    "<section class=\"panel status\"><p class=\"label\" data-i18n=\"status\">Status</p>\n"
    "<p class=\"dev\" id=\"dev\">-</p>\n"
    "<div id=\"stats\" style=\"display:none\">\n"
    "<div class=\"tiles\">\n"
    "<div class=\"tile\"><span class=\"k\" data-i18n=\"packets\">Packets / SBC frames</span><span class=\"v\" id=\"pk\">-</span></div>\n"
    "<div class=\"tile\"><span class=\"k\" data-i18n=\"avrcp\">AVRCP</span><span class=\"v\" id=\"av\">-</span></div>\n"
    "<div class=\"tile w\"><span class=\"k\" data-i18n=\"format\">Format</span><span class=\"v\" id=\"fmt\">-</span></div>\n"
    "</div>\n"
    "<div class=\"meters\">\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"capPeak\">Capture peak</span><span class=\"v\" id=\"pkv\">-</span></div>\n"
    "<div class=\"meter\"><div id=\"m1\"></div></div>\n"
    "<div class=\"row\"><span class=\"k\" data-i18n=\"outPeak\">Output peak</span><span class=\"v\" id=\"opv\">-</span></div>\n"
    "<div class=\"meter\"><div id=\"m2\"></div></div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"idle\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg></div>\n"
    "</section>\n"
    "</main>\n"
    "</div>\n"
    "<script>\n"
    "var I18N={\"langs\":[{\"code\":\"en\",\"name\":\"English\",\"rtl\":false},{\"code\":\"ar\",\"name\":\"العربية\",\"rtl\":true},{\"code\":\"es\",\"name\":\"Español\",\"rtl\":false},{\"code\":\"fr\",\"name\":\"Français\",\"rtl\":false},{\"code\":\"de\",\"name\":\"Deutsch\",\"rtl\":false},{\"code\":\"pt\",\"name\":\"Português\",\"rtl\":false},{\"code\":\"ru\",\"name\":\"Русский\",\"rtl\":false},{\"code\":\"ja\",\"name\":\"日本語\",\"rtl\":false},{\"code\":\"zh\",\"name\":\"中文\",\"rtl\":false},{\"code\":\"it\",\"name\":\"Italiano\",\"rtl\":false},{\"code\":\"he\",\"name\":\"עברית\",\"rtl\":true}],\"strings\":{\"en\":{\"language\":\"Language\",\"status\":\"Status\",\"starting\":\"Starting\",\"connecting\":\"Connecting\",\"streaming\":\"Streaming\",\"reconnecting\":\"Reconnecting\",\"paused\":\"Not connected\",\"device\":\"Device\",\"packets\":\"Packets / SBC frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"not connected\",\"avrcpConn\":\"connected\",\"avrcpAbs\":\"absolute volume\",\"notif\":\"notifications\",\"capPeak\":\"Capture peak\",\"outPeak\":\"Output peak\",\"volume\":\"Volume\",\"boost\":\"Boost (software gain)\",\"headset\":\"Headset volume (AVRCP)\",\"mute\":\"Mute\",\"unmute\":\"Unmute\",\"tone\":\"Test tone\",\"toneOn\":\"Tone on\",\"connection\":\"Connection\",\"connect\":\"Connect\",\"disconnect\":\"Disconnect\",\"stop\":\"Stop HearBridge\",\"stopConfirm\":\"Stop HearBridge?\",\"unreachable\":\"Not reachable - is HearBridge running?\",\"queue\":\"queue\",\"footer\":\"Closing this page leaves HearBridge running. Use Stop before loading the ELF again.\",\"devices\":\"Devices\",\"scanning\":\"Scanning\",\"waiting-selection\":\"Choose your headphones\",\"pairing\":\"Pairing\",\"choose\":\"Choose\",\"noDevices\":\"No audio devices found yet.\",\"pairHint\":\"Press Scan again to refresh the list.\",\"error\":\"Error\",\"connected\":\"Connected\",\"scan\":\"Scan for devices\",\"reconnect\":\"Reconnect\",\"saved\":\"Saved headphones\",\"noSaved\":\"No saved headphones yet.\",\"found\":\"Found nearby\",\"forget\":\"Forget\",\"forgetConfirm\":\"Forget this device?\",\"current\":\"In use\",\"connectTo\":\"Connect\",\"scanHint\":\"Put the headphones in pairing mode and press Scan. The scan takes about 20 seconds.\",\"signal\":\"Signal\",\"perPkt\":\"frames/packet\",\"notConnected\":\"Not connected\",\"disconnected\":\"Not connected\"},\"ar\":{\"language\":\"اللغة\",\"status\":\"الحالة\",\"starting\":\"جارٍ البدء\",\"connecting\":\"جارٍ الاتصال\",\"streaming\":\"يتم البث\",\"reconnecting\":\"إعادة الاتصال\",\"paused\":\"غير متصل\",\"device\":\"الجهاز\",\"packets\":\"الحزم / إطارات SBC\",\"format\":\"التنسيق\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"غير متصل\",\"avrcpConn\":\"متصل\",\"avrcpAbs\":\"مستوى صوت مطلق\",\"notif\":\"إشعارات\",\"capPeak\":\"ذروة الالتقاط\",\"outPeak\":\"ذروة الإخراج\",\"volume\":\"مستوى الصوت\",\"boost\":\"تعزيز (كسب برمجي)\",\"headset\":\"صوت السماعة (AVRCP)\",\"mute\":\"كتم\",\"unmute\":\"إلغاء الكتم\",\"tone\":\"نغمة اختبار\",\"toneOn\":\"النغمة تعمل\",\"connection\":\"الاتصال\",\"connect\":\"اتصال\",\"disconnect\":\"قطع الاتصال\",\"stop\":\"إيقاف HearBridge\",\"stopConfirm\":\"إيقاف HearBridge؟\",\"unreachable\":\"تعذّر الوصول - هل HearBridge يعمل؟\",\"queue\":\"قائمة الانتظار\",\"footer\":\"إغلاق هذه الصفحة يُبقي HearBridge قيد التشغيل. استخدم «إيقاف» قبل تحميل ملف ELF مرة أخرى.\",\"devices\":\"الأجهزة\",\"scanning\":\"جارٍ البحث\",\"waiting-selection\":\"اختر سماعاتك\",\"pairing\":\"جارٍ الإقران\",\"choose\":\"اختيار\",\"noDevices\":\"لم يُعثر على أجهزة صوت بعد.\",\"pairHint\":\"اضغط «البحث» مرة أخرى لتحديث القائمة.\",\"error\":\"خطأ\",\"connected\":\"متصل\",\"scan\":\"البحث عن أجهزة\",\"reconnect\":\"إعادة الاتصال\",\"saved\":\"السماعات المحفوظة\",\"noSaved\":\"لا توجد سماعات محفوظة بعد.\",\"found\":\"أجهزة قريبة\",\"forget\":\"نسيان\",\"forgetConfirm\":\"هل تريد نسيان هذا الجهاز؟\",\"current\":\"قيد الاستخدام\",\"connectTo\":\"اتصال\",\"scanHint\":\"ضع السماعات في وضع الإقران واضغط «البحث». يستغرق البحث نحو 20 ثانية.\",\"signal\":\"الإشارة\",\"perPkt\":\"إطار/حزمة\",\"notConnected\":\"غير متصل\",\"disconnected\":\"غير متصل\"},\"es\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitiendo\",\"reconnecting\":\"Reconectando\",\"paused\":\"No conectado\",\"device\":\"Dispositivo\",\"packets\":\"Paquetes / tramas SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"no conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volumen absoluto\",\"notif\":\"notificaciones\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de salida\",\"volume\":\"Volumen\",\"boost\":\"Refuerzo (ganancia por software)\",\"headset\":\"Volumen de los auriculares (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Activar sonido\",\"tone\":\"Tono de prueba\",\"toneOn\":\"Tono activo\",\"connection\":\"Conexión\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Detener HearBridge\",\"stopConfirm\":\"¿Detener HearBridge?\",\"unreachable\":\"Sin respuesta: ¿está HearBridge en ejecución?\",\"queue\":\"cola\",\"footer\":\"Cerrar esta página deja HearBridge en marcha. Usa Detener antes de volver a cargar el ELF.\",\"devices\":\"Dispositivos\",\"scanning\":\"Buscando\",\"waiting-selection\":\"Elige tus auriculares\",\"pairing\":\"Emparejando\",\"choose\":\"Elegir\",\"noDevices\":\"Aún no se encontraron dispositivos de audio.\",\"pairHint\":\"Pulsa Buscar de nuevo para actualizar la lista.\",\"error\":\"Error\",\"connected\":\"Conectado\",\"scan\":\"Buscar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Auriculares guardados\",\"noSaved\":\"Aún no hay auriculares guardados.\",\"found\":\"Encontrados cerca\",\"forget\":\"Olvidar\",\"forgetConfirm\":\"¿Olvidar este dispositivo?\",\"current\":\"En uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Pon los auriculares en modo de emparejamiento y pulsa Buscar. La búsqueda dura unos 20 segundos.\",\"signal\":\"Señal\",\"perPkt\":\"tramas/paquete\",\"notConnected\":\"No conectado\",\"disconnected\":\"No conectado\"},\"fr\":{\"language\":\"Langue\",\"status\":\"État\",\"starting\":\"Démarrage\",\"connecting\":\"Connexion\",\"streaming\":\"Diffusion\",\"reconnecting\":\"Reconnexion\",\"paused\":\"Non connecté\",\"device\":\"Appareil\",\"packets\":\"Paquets / trames SBC\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connecté\",\"avrcpConn\":\"connecté\",\"avrcpAbs\":\"volume absolu\",\"notif\":\"notifications\",\"capPeak\":\"Crête de capture\",\"outPeak\":\"Crête de sortie\",\"volume\":\"Volume\",\"boost\":\"Amplification (gain logiciel)\",\"headset\":\"Volume du casque (AVRCP)\",\"mute\":\"Couper le son\",\"unmute\":\"Rétablir le son\",\"tone\":\"Son de test\",\"toneOn\":\"Son actif\",\"connection\":\"Connexion\",\"connect\":\"Connecter\",\"disconnect\":\"Déconnecter\",\"stop\":\"Arrêter HearBridge\",\"stopConfirm\":\"Arrêter HearBridge ?\",\"unreachable\":\"Injoignable : HearBridge est-il lancé ?\",\"queue\":\"file\",\"footer\":\"Fermer cette page laisse HearBridge actif. Utilisez Arrêter avant de recharger l'ELF.\",\"devices\":\"Appareils\",\"scanning\":\"Recherche\",\"waiting-selection\":\"Choisissez votre casque\",\"pairing\":\"Appairage\",\"choose\":\"Choisir\",\"noDevices\":\"Aucun appareil audio trouvé pour l'instant.\",\"pairHint\":\"Appuyez à nouveau sur Rechercher pour actualiser la liste.\",\"error\":\"Erreur\",\"connected\":\"Connecté\",\"scan\":\"Rechercher des appareils\",\"reconnect\":\"Reconnecter\",\"saved\":\"Casques enregistrés\",\"noSaved\":\"Aucun casque enregistré pour l'instant.\",\"found\":\"Trouvés à proximité\",\"forget\":\"Oublier\",\"forgetConfirm\":\"Oublier cet appareil ?\",\"current\":\"Utilisé\",\"connectTo\":\"Connecter\",\"scanHint\":\"Mettez le casque en mode appairage et appuyez sur Rechercher. La recherche dure environ 20 secondes.\",\"signal\":\"Signal\",\"perPkt\":\"trames/paquet\",\"notConnected\":\"Non connecté\",\"disconnected\":\"Non connecté\"},\"de\":{\"language\":\"Sprache\",\"status\":\"Status\",\"starting\":\"Startet\",\"connecting\":\"Verbinde\",\"streaming\":\"Überträgt\",\"reconnecting\":\"Verbinde neu\",\"paused\":\"Nicht verbunden\",\"device\":\"Gerät\",\"packets\":\"Pakete / SBC-Frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"nicht verbunden\",\"avrcpConn\":\"verbunden\",\"avrcpAbs\":\"absolute Lautstärke\",\"notif\":\"Benachrichtigungen\",\"capPeak\":\"Aufnahme-Spitze\",\"outPeak\":\"Ausgabe-Spitze\",\"volume\":\"Lautstärke\",\"boost\":\"Verstärkung (Software)\",\"headset\":\"Kopfhörer-Lautstärke (AVRCP)\",\"mute\":\"Stumm\",\"unmute\":\"Ton an\",\"tone\":\"Testton\",\"toneOn\":\"Ton läuft\",\"connection\":\"Verbindung\",\"connect\":\"Verbinden\",\"disconnect\":\"Trennen\",\"stop\":\"HearBridge beenden\",\"stopConfirm\":\"HearBridge beenden?\",\"unreachable\":\"Nicht erreichbar – läuft HearBridge?\",\"queue\":\"Warteschlange\",\"footer\":\"Diese Seite zu schließen lässt HearBridge weiterlaufen. Vor dem erneuten Laden der ELF „Beenden“ verwenden.\",\"devices\":\"Geräte\",\"scanning\":\"Suche\",\"waiting-selection\":\"Kopfhörer auswählen\",\"pairing\":\"Kopplung\",\"choose\":\"Auswählen\",\"noDevices\":\"Noch keine Audiogeräte gefunden.\",\"pairHint\":\"Drücke erneut Suchen, um die Liste zu aktualisieren.\",\"error\":\"Fehler\",\"connected\":\"Verbunden\",\"scan\":\"Nach Geräten suchen\",\"reconnect\":\"Neu verbinden\",\"saved\":\"Gespeicherte Kopfhörer\",\"noSaved\":\"Noch keine gespeicherten Kopfhörer.\",\"found\":\"In der Nähe gefunden\",\"forget\":\"Entfernen\",\"forgetConfirm\":\"Dieses Gerät entfernen?\",\"current\":\"In Verwendung\",\"connectTo\":\"Verbinden\",\"scanHint\":\"Versetze die Kopfhörer in den Kopplungsmodus und drücke Suchen. Die Suche dauert etwa 20 Sekunden.\",\"signal\":\"Signal\",\"perPkt\":\"Frames/Paket\",\"notConnected\":\"Nicht verbunden\",\"disconnected\":\"Nicht verbunden\"},\"pt\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitindo\",\"reconnecting\":\"Reconectando\",\"paused\":\"Não conectado\",\"device\":\"Dispositivo\",\"packets\":\"Pacotes / quadros SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"não conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volume absoluto\",\"notif\":\"notificações\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de saída\",\"volume\":\"Volume\",\"boost\":\"Reforço (ganho por software)\",\"headset\":\"Volume do fone (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Reativar som\",\"tone\":\"Tom de teste\",\"toneOn\":\"Tom ligado\",\"connection\":\"Conexão\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Parar o HearBridge\",\"stopConfirm\":\"Parar o HearBridge?\",\"unreachable\":\"Sem resposta: o HearBridge está em execução?\",\"queue\":\"fila\",\"footer\":\"Fechar esta página mantém o HearBridge em execução. Use Parar antes de carregar o ELF novamente.\",\"devices\":\"Dispositivos\",\"scanning\":\"Procurando\",\"waiting-selection\":\"Escolha seus fones\",\"pairing\":\"Pareando\",\"choose\":\"Escolher\",\"noDevices\":\"Nenhum dispositivo de áudio encontrado ainda.\",\"pairHint\":\"Toque em Procurar novamente para atualizar a lista.\",\"error\":\"Erro\",\"connected\":\"Conectado\",\"scan\":\"Procurar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Fones salvos\",\"noSaved\":\"Ainda não há fones salvos.\",\"found\":\"Encontrados por perto\",\"forget\":\"Esquecer\",\"forgetConfirm\":\"Esquecer este dispositivo?\",\"current\":\"Em uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Coloque os fones no modo de pareamento e toque em Procurar. A busca leva cerca de 20 segundos.\",\"signal\":\"Sinal\",\"perPkt\":\"quadros/pacote\",\"notConnected\":\"Não conectado\",\"disconnected\":\"Não conectado\"},\"ru\":{\"language\":\"Язык\",\"status\":\"Состояние\",\"starting\":\"Запуск\",\"connecting\":\"Подключение\",\"streaming\":\"Передача\",\"reconnecting\":\"Переподключение\",\"paused\":\"Не подключено\",\"device\":\"Устройство\",\"packets\":\"Пакеты / кадры SBC\",\"format\":\"Формат\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"не подключено\",\"avrcpConn\":\"подключено\",\"avrcpAbs\":\"абсолютная громкость\",\"notif\":\"уведомления\",\"capPeak\":\"Пик захвата\",\"outPeak\":\"Пик вывода\",\"volume\":\"Громкость\",\"boost\":\"Усиление (программное)\",\"headset\":\"Громкость наушников (AVRCP)\",\"mute\":\"Без звука\",\"unmute\":\"Включить звук\",\"tone\":\"Тестовый тон\",\"toneOn\":\"Тон включён\",\"connection\":\"Подключение\",\"connect\":\"Подключить\",\"disconnect\":\"Отключить\",\"stop\":\"Остановить HearBridge\",\"stopConfirm\":\"Остановить HearBridge?\",\"unreachable\":\"Нет ответа — HearBridge запущен?\",\"queue\":\"очередь\",\"footer\":\"Если закрыть страницу, HearBridge продолжит работу. Перед повторной загрузкой ELF нажмите «Остановить».\",\"devices\":\"Устройства\",\"scanning\":\"Поиск\",\"waiting-selection\":\"Выберите наушники\",\"pairing\":\"Сопряжение\",\"choose\":\"Выбрать\",\"noDevices\":\"Аудиоустройства пока не найдены.\",\"pairHint\":\"Нажмите «Искать» ещё раз, чтобы обновить список.\",\"error\":\"Ошибка\",\"connected\":\"Подключено\",\"scan\":\"Искать устройства\",\"reconnect\":\"Переподключить\",\"saved\":\"Сохранённые наушники\",\"noSaved\":\"Сохранённых наушников пока нет.\",\"found\":\"Найдены поблизости\",\"forget\":\"Забыть\",\"forgetConfirm\":\"Забыть это устройство?\",\"current\":\"Используется\",\"connectTo\":\"Подключить\",\"scanHint\":\"Переведите наушники в режим сопряжения и нажмите «Искать». Поиск занимает около 20 секунд.\",\"signal\":\"Сигнал\",\"perPkt\":\"кадров/пакет\",\"notConnected\":\"Не подключено\",\"disconnected\":\"Не подключено\"},\"ja\":{\"language\":\"言語\",\"status\":\"状態\",\"starting\":\"起動中\",\"connecting\":\"接続中\",\"streaming\":\"ストリーミング中\",\"reconnecting\":\"再接続中\",\"paused\":\"未接続\",\"device\":\"デバイス\",\"packets\":\"パケット / SBCフレーム\",\"format\":\"形式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未接続\",\"avrcpConn\":\"接続済み\",\"avrcpAbs\":\"絶対音量\",\"notif\":\"通知\",\"capPeak\":\"キャプチャのピーク\",\"outPeak\":\"出力のピーク\",\"volume\":\"音量\",\"boost\":\"ブースト（ソフトウェアゲイン）\",\"headset\":\"ヘッドホンの音量（AVRCP）\",\"mute\":\"ミュート\",\"unmute\":\"ミュート解除\",\"tone\":\"テストトーン\",\"toneOn\":\"トーン再生中\",\"connection\":\"接続\",\"connect\":\"接続\",\"disconnect\":\"切断\",\"stop\":\"HearBridge を停止\",\"stopConfirm\":\"HearBridge を停止しますか？\",\"unreachable\":\"応答なし - HearBridge は動作中ですか？\",\"queue\":\"キュー\",\"footer\":\"このページを閉じても HearBridge は動作を続けます。ELF を再読み込みする前に「停止」を使ってください。\",\"devices\":\"デバイス\",\"scanning\":\"検索中\",\"waiting-selection\":\"ヘッドホンを選択\",\"pairing\":\"ペアリング中\",\"choose\":\"選択\",\"noDevices\":\"オーディオデバイスはまだ見つかっていません。\",\"pairHint\":\"リストを更新するには、もう一度「検索」を押してください。\",\"error\":\"エラー\",\"connected\":\"接続済み\",\"scan\":\"デバイスを検索\",\"reconnect\":\"再接続\",\"saved\":\"保存したヘッドホン\",\"noSaved\":\"保存したヘッドホンはまだありません。\",\"found\":\"近くで見つかったデバイス\",\"forget\":\"削除\",\"forgetConfirm\":\"このデバイスを削除しますか？\",\"current\":\"使用中\",\"connectTo\":\"接続\",\"scanHint\":\"ヘッドホンをペアリングモードにして「検索」を押してください。検索には約20秒かかります。\",\"signal\":\"信号\",\"perPkt\":\"フレーム/パケット\",\"notConnected\":\"未接続\",\"disconnected\":\"未接続\"},\"zh\":{\"language\":\"语言\",\"status\":\"状态\",\"starting\":\"正在启动\",\"connecting\":\"正在连接\",\"streaming\":\"正在传输\",\"reconnecting\":\"正在重新连接\",\"paused\":\"未连接\",\"device\":\"设备\",\"packets\":\"数据包 / SBC 帧\",\"format\":\"格式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未连接\",\"avrcpConn\":\"已连接\",\"avrcpAbs\":\"绝对音量\",\"notif\":\"通知\",\"capPeak\":\"采集峰值\",\"outPeak\":\"输出峰值\",\"volume\":\"音量\",\"boost\":\"增益（软件放大）\",\"headset\":\"耳机音量（AVRCP）\",\"mute\":\"静音\",\"unmute\":\"取消静音\",\"tone\":\"测试音\",\"toneOn\":\"测试音开启\",\"connection\":\"连接\",\"connect\":\"连接\",\"disconnect\":\"断开\",\"stop\":\"停止 HearBridge\",\"stopConfirm\":\"停止 HearBridge？\",\"unreachable\":\"无法访问——HearBridge 是否在运行？\",\"queue\":\"队列\",\"footer\":\"关闭此页面后 HearBridge 仍会运行。再次加载 ELF 前请先点“停止”。\",\"devices\":\"设备\",\"scanning\":\"正在搜索\",\"waiting-selection\":\"选择你的耳机\",\"pairing\":\"正在配对\",\"choose\":\"选择\",\"noDevices\":\"尚未找到音频设备。\",\"pairHint\":\"再次按“搜索”即可刷新列表。\",\"error\":\"错误\",\"connected\":\"已连接\",\"scan\":\"搜索设备\",\"reconnect\":\"重新连接\",\"saved\":\"已保存的耳机\",\"noSaved\":\"还没有已保存的耳机。\",\"found\":\"附近找到的设备\",\"forget\":\"忘记\",\"forgetConfirm\":\"忘记此设备？\",\"current\":\"使用中\",\"connectTo\":\"连接\",\"scanHint\":\"让耳机进入配对模式，然后按“搜索”。搜索大约需要 20 秒。\",\"signal\":\"信号\",\"perPkt\":\"帧/包\",\"notConnected\":\"未连接\",\"disconnected\":\"未连接\"},\"it\":{\"language\":\"Lingua\",\"status\":\"Stato\",\"starting\":\"Avvio\",\"connecting\":\"Connessione\",\"streaming\":\"In streaming\",\"reconnecting\":\"Riconnessione\",\"paused\":\"Non connesso\",\"device\":\"Dispositivo\",\"packets\":\"Pacchetti / frame SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connesso\",\"avrcpConn\":\"connesso\",\"avrcpAbs\":\"volume assoluto\",\"notif\":\"notifiche\",\"capPeak\":\"Picco di cattura\",\"outPeak\":\"Picco di uscita\",\"volume\":\"Volume\",\"boost\":\"Amplificazione (guadagno software)\",\"headset\":\"Volume cuffie (AVRCP)\",\"mute\":\"Muto\",\"unmute\":\"Riattiva audio\",\"tone\":\"Tono di prova\",\"toneOn\":\"Tono attivo\",\"connection\":\"Connessione\",\"connect\":\"Connetti\",\"disconnect\":\"Disconnetti\",\"stop\":\"Arresta HearBridge\",\"stopConfirm\":\"Arrestare HearBridge?\",\"unreachable\":\"Non raggiungibile: HearBridge è in esecuzione?\",\"queue\":\"coda\",\"footer\":\"Chiudere questa pagina lascia HearBridge attivo. Usa Arresta prima di ricaricare l'ELF.\",\"devices\":\"Dispositivi\",\"scanning\":\"Ricerca\",\"waiting-selection\":\"Scegli le cuffie\",\"pairing\":\"Abbinamento\",\"choose\":\"Scegli\",\"noDevices\":\"Nessun dispositivo audio trovato finora.\",\"pairHint\":\"Premi di nuovo Cerca per aggiornare l'elenco.\",\"error\":\"Errore\",\"connected\":\"Connesso\",\"scan\":\"Cerca dispositivi\",\"reconnect\":\"Riconnetti\",\"saved\":\"Cuffie salvate\",\"noSaved\":\"Nessuna cuffia salvata.\",\"found\":\"Trovati nelle vicinanze\",\"forget\":\"Dimentica\",\"forgetConfirm\":\"Dimenticare questo dispositivo?\",\"current\":\"In uso\",\"connectTo\":\"Connetti\",\"scanHint\":\"Metti le cuffie in modalità di abbinamento e premi Cerca. La ricerca dura circa 20 secondi.\",\"signal\":\"Segnale\",\"perPkt\":\"frame/pacchetto\",\"notConnected\":\"Non connesso\",\"disconnected\":\"Non connesso\"},\"he\":{\"language\":\"שפה\",\"status\":\"מצב\",\"starting\":\"מתחיל\",\"connecting\":\"מתחבר\",\"streaming\":\"משדר\",\"reconnecting\":\"מתחבר מחדש\",\"paused\":\"לא מחובר\",\"device\":\"מכשיר\",\"packets\":\"חבילות / מסגרות SBC\",\"format\":\"פורמט\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"לא מחובר\",\"avrcpConn\":\"מחובר\",\"avrcpAbs\":\"עוצמה מוחלטת\",\"notif\":\"התראות\",\"capPeak\":\"שיא לכידה\",\"outPeak\":\"שיא יציאה\",\"volume\":\"עוצמת שמע\",\"boost\":\"הגברה (תוכנה)\",\"headset\":\"עוצמת האוזניות (AVRCP)\",\"mute\":\"השתק\",\"unmute\":\"בטל השתקה\",\"tone\":\"צליל בדיקה\",\"toneOn\":\"צליל פועל\",\"connection\":\"חיבור\",\"connect\":\"התחבר\",\"disconnect\":\"התנתק\",\"stop\":\"עצור את HearBridge\",\"stopConfirm\":\"לעצור את HearBridge?\",\"unreachable\":\"אין תגובה - האם HearBridge פועל?\",\"queue\":\"תור\",\"footer\":\"סגירת הדף משאירה את HearBridge פועל. לחצו על עצירה לפני טעינת ה-ELF מחדש.\",\"devices\":\"מכשירים\",\"scanning\":\"סורק\",\"waiting-selection\":\"בחרו את האוזניות\",\"pairing\":\"מבצע צימוד\",\"choose\":\"בחר\",\"noDevices\":\"עדיין לא נמצאו מכשירי שמע.\",\"pairHint\":\"לחצו שוב על חיפוש כדי לרענן את הרשימה.\",\"error\":\"שגיאה\",\"connected\":\"מחובר\",\"scan\":\"חיפוש מכשירים\",\"reconnect\":\"התחברות מחדש\",\"saved\":\"אוזניות שמורות\",\"noSaved\":\"אין עדיין אוזניות שמורות.\",\"found\":\"נמצאו בקרבת מקום\",\"forget\":\"שכח\",\"forgetConfirm\":\"לשכוח את המכשיר הזה?\",\"current\":\"בשימוש\",\"connectTo\":\"התחבר\",\"scanHint\":\"העבירו את האוזניות למצב צימוד ולחצו על חיפוש. החיפוש נמשך כ-20 שניות.\",\"signal\":\"אות\",\"perPkt\":\"מסגרות/מנה\",\"notConnected\":\"לא מחובר\",\"disconnected\":\"לא מחובר\"}}};\n"
    "var S=null,busyG=0,busyH=0,LANG='en';\n"
    "function $(i){return document.getElementById(i)}\n"
    "function t(k){var d=I18N.strings[LANG]||I18N.strings.en;return d[k]||I18N.strings.en[k]||k}\n"
    "function info(c){for(var i=0;i<I18N.langs.length;i++)if(I18N.langs[i].code==c)return I18N.langs[i];return I18N.langs[0]}\n"
    "function setLang(c){var L=info(c);LANG=L.code;try{localStorage.setItem('hb_lang',LANG)}catch(e){}\n"
    "document.documentElement.lang=LANG;document.documentElement.dir=L.rtl?'rtl':'ltr';\n"
    "var n=document.querySelectorAll('[data-i18n]');for(var i=0;i<n.length;i++)n[i].textContent=t(n[i].getAttribute('data-i18n'));\n"
    "var o=$('langlist').getElementsByTagName('button');for(var i2=0;i2<o.length;i2++)o[i2].className='langopt'+(o[i2].getAttribute('data-code')==LANG?' on':'');$('langlist').className='';if(S)draw()}\n"
    "function buildLangs(){var h='',i,L;for(i=0;i<I18N.langs.length;i++){L=I18N.langs[i];\n"
    "h+='<button type=\"button\" class=\"langopt\" role=\"menuitem\" data-code=\"'+L.code+'\"'+(L.rtl?' dir=\"rtl\"':'')+'><span>'+L.name+'</span></button>'}\n"
    "$('langlist').innerHTML=h;var b=$('langlist').getElementsByTagName('button');\n"
    "for(i=0;i<b.length;i++)b[i].onclick=function(){setLang(this.getAttribute('data-code'))};\n"
    "$('langbtn').onclick=function(){$('langlist').className=$('langlist').className?'':'show'}}\n"
    "function req(p,cb){var x=new XMLHttpRequest();x.open('GET',p,true);x.timeout=4000;\n"
    "x.onload=function(){if(x.status==200){try{S=JSON.parse(x.responseText);draw()}catch(e){}}if(cb)cb()};\n"
    "x.onerror=x.ontimeout=function(){$('msg').textContent=t('unreachable');$('live').className='live bad';if(cb)cb()};\n"
    "x.send()}\n"
    "var devT=0;\n"
    "function esc(x){return String(x).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}\n"
    "var ICON={\n"
    "head:'<path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/>',\n"
    "spk:'<path d=\"M3 9h4l6-5v16l-6-5H3z\" fill=\"currentColor\"/><path d=\"M16 8a5 5 0 0 1 0 8M18.5 5a9 9 0 0 1 0 14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "tv:'<rect x=\"2\" y=\"4\" width=\"20\" height=\"13\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><path d=\"M8 21h8\" stroke=\"currentColor\" stroke-width=\"2.2\"/>',\n"
    "car:'<path d=\"M3 15l2-6h14l2 6v4H3z\" fill=\"currentColor\"/><circle cx=\"7\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/><circle cx=\"17\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/>',\n"
    "mic:'<rect x=\"9\" y=\"2\" width=\"6\" height=\"12\" rx=\"3\" fill=\"currentColor\"/><path d=\"M5 11a7 7 0 0 0 14 0M12 18v4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "note:'<path d=\"M9 17V5l11-2v12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><circle cx=\"6.5\" cy=\"17.5\" r=\"3\" fill=\"currentColor\"/><circle cx=\"17.5\" cy=\"15.5\" r=\"3\" fill=\"currentColor\"/>'};\n"
    "var KIND={headphones:'head',headset:'head',speaker:'spk',portable:'spk',hifi:'spk',car:'car',handsfree:'mic',tv:'tv',av:'tv',audio:'note'};\n"
    "function icon(k){return '<svg viewBox=\"0 0 24 24\" width=\"34\" height=\"34\" aria-hidden=\"true\">'+ICON[KIND[k]||'note']+'</svg>'}\n"
    "function kindOf(cod){var c=parseInt(cod,16)||0,maj=(c>>8)&31,min=(c>>2)&63;if(maj!=4)return 'audio';\n"
    "return {6:'headphones',1:'headset',5:'speaker',7:'portable',10:'hifi',8:'car',2:'handsfree',9:'tv',14:'tv',15:'tv'}[min]||'av'}\n"
    "function bars(r){if(r==null)return '';var n=r>-60?4:r>-70?3:r>-80?2:1,h='<span class=\"bars\" title=\"'+r+' dBm\">';\n"
    "for(var i=1;i<=4;i++)h+='<i class=\"'+(i<=n?'on':'')+'\" style=\"height:'+(i*4)+'px\"></i>';return h+'</span>'}\n"
    "function getj(p,cb){var x=new XMLHttpRequest();x.open('GET',p,true);x.timeout=4000;x.onload=function(){try{cb(JSON.parse(x.responseText))}catch(e){}};x.send()}\n"
    "function row(icon,name,meta,btns){return '<div class=\"dl\"><span class=\"ico\">'+icon+'</span><span class=\"nm\"><b>'+esc(name)+'</b><span class=\"k\" dir=\"ltr\">'+meta+'</span></span><span class=\"acts\">'+btns+'</span></div>'}\n"
    "function wire(id){var b=$(id).getElementsByTagName('button');for(var i=0;i<b.length;i++)b[i].onclick=function(){\n"
    "var a=this.getAttribute('data-addr'),f=this.getAttribute('data-forget');\n"
    "if(this.getAttribute('data-disc')){req('/api/disconnect');return}\n"
    "if(f){if(confirm(t('forgetConfirm')))req('/api/forget?addr='+a,saved);return}\n"
    "req('/api/select?addr='+a);this.textContent=t('connecting')+'…'}}\n"
    "var SAVL=null;\n"
    "function stOf(){return S?(S.paused?'paused':S.state):''}\n"
    "function linked(){var st=stOf();return st=='streaming'||st=='connected'}\n"
    "function badge(cur){var st=stOf();\n"
    "if(!cur)return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(linked())return '<span class=\"badge\">'+esc(t('connected'))+'</span>';\n"
    "if(st=='paused')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='disconnected')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='connecting'||st=='pairing')return '<span class=\"badge warn\">'+esc(t('connecting'))+'</span>';\n"
    "return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>'}\n"
    "function drawSaved(){if(!SAVL)return;var h='',i,d,on=linked(),st=stOf(),busy=st=='connecting'||st=='pairing';\n"
    "for(i=0;i<SAVL.length;i++){d=SAVL[i];\n"
    "h+=row(icon(d.kind),d.name||d.addr,esc(d.addr)+badge(d.current),\n"
    "(d.current&&on?'<button type=\"button\" data-disc=\"1\">'+esc(t('disconnect'))+'</button>'\n"
    ":d.current&&busy?'':'<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('connect'))+'</button>')\n"
    "+'<button type=\"button\" class=\"red\" data-forget=\"1\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('forget'))+'</button>')}\n"
    "var k=h+'|'+LANG;if(k==drawSaved.last)return;drawSaved.last=k;\n"
    "$('savedlist').innerHTML=h||'<p class=\"k\">'+esc(t('noSaved'))+'</p>';wire('savedlist')}\n"
    "function saved(){getj('/api/saved',function(j){var i;SAVL=j.devices;SAV={};for(i=0;i<SAVL.length;i++)SAV[SAVL[i].addr]=1;drawSaved()})}\n"
    "var SAV={},SHOW={headphones:1,headset:1,speaker:1,portable:1,hifi:1,handsfree:1},HEAD={headphones:1,headset:1};\n"
    "function devices(){getj('/api/devices',function(j){var h='',i,d,k;\n"
    "for(i=0;i<j.devices.length;i++){d=j.devices[i];if(SAV[d.addr])continue;k=d.kind||kindOf(d.cod);if(!SHOW[k]||(!d.name&&!HEAD[k]))continue;\n"
    "h+=row(icon(k),d.name||d.addr,esc(d.addr)+bars(d.rssi),'<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('connectTo'))+'</button>')}\n"
    "$('devlist').innerHTML=h||'<p class=\"k\">'+esc(t('noDevices'))+'</p>';wire('devlist')})}\n"
    "function pct(v){return Math.round(v)+'%'}\n"
    "function draw(){\n"
    "$('msg').textContent='';\n"
    "$('ver').textContent=S.version;\n"
    "var st=S.paused?'paused':S.state;\n"
    "$('state').textContent={reconnecting:1,disconnected:1,paused:1,error:1,idle:1,'waiting-selection':1}[st]?t('notConnected')+(st=='error'&&S.detail?' ('+S.detail.replace(/^error\\s*/,'')+')':''):(t(st)==st?st:t(st));\n"
    "$('live').className='live '+(st=='streaming'||st=='connected'?'ok':(st=='paused'||st=='disconnected'||st=='error'?'bad':'wait'));\n"
    "var on=!!S.connected,link=on||((st=='connecting'||st=='pairing')&&S.device);\n"
    "$('dev').textContent=link?(S.device||'-'):t('notConnected');$('stats').style.display=on?'':'none';\n"
    "if(!on){S.pkts=S.frames=S.backlog=S.sample_rate=0;S.peak=S.out_peak=0;S.avrcp={}}\n"
    "$('scanning').style.display=st=='scanning'?'':'none';\n"
    "if(Date.now()-devT>3000){devT=Date.now();devices();saved()}\n"
    "drawSaved();\n"
    "$('pk').textContent=S.pkts+' / '+S.frames+(S.backlog?' ('+t('queue')+' '+S.backlog+')':'');\n"
    "\n"
    "$('fmt').textContent=S.sample_rate?('SBC '+S.sample_rate+' Hz, bitpool '+S.bitpool+(S.bitpool_max>S.bitpool_min?' ('+S.bitpool_min+'–'+S.bitpool_max+')':'')+', '+S.per_packet+' '+t('perPkt')):'-';\n"
    "$('av').textContent=!S.avrcp.connected?t('avrcpNone'):(S.avrcp.absolute_volume?t('avrcpAbs'):t('avrcpConn'))+(S.avrcp.notifications?', '+t('notif'):'');\n"
    "$('pkv').textContent=S.peak.toFixed(3);$('m1').style.width=Math.min(100,S.peak*100)+'%';\n"
    "$('opv').textContent=S.out_peak.toFixed(3);$('m2').style.width=Math.min(100,S.out_peak*100)+'%';\n"
    "if(!busyG)$('gain').value=S.gain_pct;$('gv').textContent=pct(S.gain_pct);\n"
    "if(!busyH&&S.headset_volume>=0)$('hs').value=S.headset_volume;\n"
    "$('hv').textContent=S.headset_volume<0?'-':pct(S.headset_volume*100/127);\n"
    "\n"
    "$('mute').className=S.muted?'ember':'';$('mute').textContent=t(S.muted?'unmute':'mute');\n"
    "$('tone').className=S.tone?'act':'';$('tone').textContent=t(S.tone?'toneOn':'tone')}\n"
    "$('gain').oninput=function(){busyG=1;$('gv').textContent=pct(this.value)};\n"
    "$('gain').onchange=function(){req('/api/volume?pct='+this.value,function(){busyG=0})};\n"
    "$('hs').oninput=function(){busyH=1;$('hv').textContent=pct(this.value*100/127)};\n"
    "$('hs').onchange=function(){req('/api/headset?vol='+this.value,function(){busyH=0})};\n"
    "$('mute').onclick=function(){req('/api/mute?on='+(S&&S.muted?0:1))};\n"
    "$('tone').onclick=function(){req('/api/tone?on='+(S&&S.tone?0:1))};\n"
    "$('scan').onclick=function(){req('/api/scan');$('scanning').style.display=''};\n"
    "$('stop').onclick=function(){if(confirm(t('stopConfirm')))req('/api/stop')};\n"
    "buildLangs();\n"
    "(function(){var c=null,m=/[?&]lang=([a-z]{2})/.exec(location.search);if(m)c=m[1];else try{c=localStorage.getItem('hb_lang')}catch(e){}\n"
    "if(!c){var n=(navigator.language||'en').slice(0,2).toLowerCase();c=info(n).code==n?n:'en'}setLang(c)})();\n"
    "req('/api/status');setInterval(function(){req('/api/status')},1000);\n"
    "</script></body></html>\n";

#endif
