/* Generated from src/web/index.html + i18n.json by scripts/gen_webpage.py. */
#ifndef HEARBRIDGE_WEBPAGE_H
#define HEARBRIDGE_WEBPAGE_H

static const char HB_WEBPAGE[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<meta name=\"color-scheme\" content=\"dark\">\n"
    "<title>HearBridge PS5</title>\n"
    "<style>\n"
    ":root{--ink:#f4efe6;--ink2:#cfc9be;--mute:#9a948a;--void:#0c0b0f;--deck:#15131a;--card:#1f1b26;--edge:#2c2833;--edge2:#3a3543;\n"
    "--lime:#c8ff3d;--ember:#ff6a2b;--cyan:#3dd8ff;--violet:#b18cff;--blue:#5aa2ff;--teal:#8fc2bb;--warn:#ffb23d;--bad:#ff3d5a;--sk:-12deg;\n"
    "--s1:.25rem;--s2:.5rem;--s3:.75rem;--s4:1rem;--s5:1.25rem;--gap:var(--s4)}\n"
    "*{box-sizing:border-box}\n"
    "html{background:var(--void);font-size:15px}\n"
    "body{margin:0;color:var(--ink);font:1rem/1.35 \"Bahnschrift\",\"DIN Alternate\",\"Segoe UI\",system-ui,sans-serif;\n"
    "background:repeating-linear-gradient(135deg,rgba(255,255,255,.016) 0 2px,transparent 2px 14px),\n"
    "radial-gradient(60vw 50vh at 100% 0,rgba(255,106,43,.13),transparent 60%),\n"
    "radial-gradient(50vw 50vh at 0 100%,rgba(200,255,61,.06),transparent 60%),var(--void);background-attachment:fixed}\n"
    "[dir=rtl]{--sk:12deg}\n"
    ".wrap{display:flex;flex-direction:column;padding:var(--s3) var(--s5)}\n"
    "/* header */\n"
    ".bar{display:flex;align-items:center;justify-content:space-between;padding:0 0 var(--s3);margin-bottom:var(--gap);border-bottom:2px solid var(--edge)}\n"
    ".brand{display:flex;align-items:center;min-width:0}\n"
    ".logo{flex:0 0 auto;width:2.6rem;height:2.6rem;margin-inline-end:var(--s3);display:flex;align-items:center;justify-content:center;color:var(--void);\n"
    "background:var(--lime);transform:skewX(var(--sk));box-shadow:0 0 1.2rem rgba(200,255,61,.25)}\n"
    ".logo svg{width:1.6rem;height:1.6rem;transform:skewX(calc(var(--sk)*-1))}\n"
    ".brand h1{margin:0;font-size:1.55rem;font-weight:900;letter-spacing:.22em;text-transform:uppercase;line-height:1.05;white-space:nowrap}\n"
    ".brand h1 b{color:var(--lime)}\n"
    ".meta{display:flex;align-items:center;margin-top:.2rem}\n"
    ".ver{color:var(--void);background:var(--ember);font-size:.72rem;font-weight:800;padding:0 .5em;margin-inline-end:.6em;letter-spacing:.06em;transform:skewX(var(--sk))}\n"
    ".by{color:var(--lime);font-size:.95rem;font-weight:800;letter-spacing:.08em;direction:ltr;unicode-bidi:isolate;white-space:nowrap;text-shadow:0 0 .6rem rgba(200,255,61,.35)}\n"
    ".diag{color:var(--mute);font-size:.7rem;margin-inline-start:.8em;direction:ltr;unicode-bidi:isolate;white-space:nowrap;text-decoration:underline;opacity:.75}\n"
    ".diag:hover,.diag:focus{color:var(--ember);opacity:1}\n"
    ".live{display:flex;align-items:center;padding:.45rem 1.1rem;background:var(--deck);border:2px solid var(--edge);font-size:.9rem;font-weight:800;\n"
    "text-transform:uppercase;letter-spacing:.1em;white-space:nowrap;transform:skewX(var(--sk))}\n"
    ".live i,.live span{transform:skewX(calc(var(--sk)*-1))}\n"
    ".live i{width:.7rem;height:.7rem;margin-inline-end:.65rem;background:var(--mute);transform:rotate(45deg)}\n"
    ".live.ok{border-color:rgba(200,255,61,.45)}.live.ok i{background:var(--lime);box-shadow:0 0 .6rem var(--lime)}\n"
    ".live.wait{border-color:rgba(255,178,61,.45)}.live.wait i{background:var(--warn);animation:blink 1s infinite}\n"
    ".live.bad{border-color:rgba(255,61,90,.5)}.live.bad i{background:var(--bad)}\n"
    "@keyframes blink{50%{opacity:.25}}\n"
    "/* toast for errors: never pushes the layout */\n"
    ".msg{position:fixed;z-index:80;top:4.2rem;left:50%;transform:translateX(-50%);max-width:90vw;padding:.5rem 1.2rem;background:var(--bad);color:var(--void);font-weight:800;box-shadow:0 .6rem 2rem rgba(0,0,0,.6)}\n"
    ".msg:empty{display:none}\n"
    "/* dashboard: phone = one column (devices, volume, status, connection) */\n"
    ".grid{display:grid;grid-template-columns:minmax(0,1fr);grid-gap:var(--gap);\n"
    "grid-template-areas:\"dev\" \"vol\" \"eq\" \"st\" \"conn\"}\n"
    ".side{grid-area:dev;display:flex;flex-direction:column;min-width:0;min-height:0;gap:var(--gap)}\n"
    ".vol{grid-area:vol}.status{grid-area:st}.conn{grid-area:conn}.eqp{grid-area:eq}\n"
    ".panel{position:relative;display:flex;flex-direction:column;min-width:0;min-height:0;padding:var(--s3) var(--s5) var(--s4);\n"
    "background:linear-gradient(180deg,rgba(255,255,255,.03),rgba(255,255,255,0) 6rem),var(--deck);\n"
    "border:1px solid var(--edge);border-inline-start:4px solid var(--acc,var(--ember));\n"
    "clip-path:polygon(0 0,calc(100% - 1.1rem) 0,100% 1.1rem,100% 100%,0 100%)}\n"
    "[dir=rtl] .panel{clip-path:polygon(1.1rem 0,100% 0,100% 100%,0 100%,0 1.1rem)}\n"
    "/* one accent per panel (left border, title dot, title text); red stays for Stop only */\n"
    ".hero{--acc:var(--lime)}.status{--acc:var(--cyan)}.vol{--acc:var(--ember)}.eqp{--acc:var(--violet)}.conn{--acc:var(--blue)}.logp{--acc:var(--teal)}\n"
    "/* panel header: one style everywhere */\n"
    ".label{order:-3;display:flex;align-items:center;margin:0 0 var(--s3);font-size:.78rem;font-weight:800;letter-spacing:.22em;text-transform:uppercase;color:var(--acc,var(--ember));line-height:1.2}\n"
    ".label:before{content:\"\";flex:0 0 auto;width:.45rem;height:.45rem;margin-inline-end:var(--s2);background:currentColor;transform:rotate(45deg)}\n"
    ".label:after{content:\"\";flex:1;height:1px;margin-inline-start:var(--s3);background:linear-gradient(90deg,var(--edge2),transparent)}\n"
    "[dir=rtl] .label:after{background:linear-gradient(270deg,var(--edge2),transparent)}\n"
    ".k{color:var(--mute)}\n"
    ".v{font-weight:800;direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums}\n"
    "/* buttons: skewed plate drawn by ::before so focus glow is never clipped */\n"
    "button{position:relative;z-index:0;min-height:2.9rem;padding:.3rem 1.2rem;font:inherit;font-size:1rem;font-weight:800;letter-spacing:.04em;\n"
    "color:var(--ink);background:none;border:0;cursor:pointer;white-space:nowrap;outline:none}\n"
    "button:before{content:\"\";position:absolute;z-index:-1;top:0;bottom:0;left:.35em;right:.35em;background:var(--card);border:2px solid var(--edge2);\n"
    "transform:skewX(var(--sk));transition:box-shadow .12s,border-color .12s,background .12s}\n"
    "button:hover:before,button:focus:before{border-color:var(--lime);box-shadow:0 0 0 3px rgba(200,255,61,.35),0 0 1rem rgba(200,255,61,.35)}\n"
    "button:focus{transform:scale(1.04);z-index:2}\n"
    "button.act{color:var(--void)}button.act:before{background:var(--lime);border-color:var(--lime)}\n"
    "button.act:focus:before{border-color:#fff;box-shadow:0 0 0 3px #fff,0 0 1rem rgba(200,255,61,.7)}\n"
    "button.ember{color:var(--void)}button.ember:before{background:var(--ember);border-color:var(--ember)}\n"
    "button.red{color:var(--bad)}button.red:before{border-color:rgba(255,61,90,.7)}\n"
    "button.red:hover:before,button.red:focus:before{border-color:var(--bad);background:rgba(255,61,90,.12);box-shadow:0 0 0 3px rgba(255,61,90,.35),0 0 1.4rem rgba(255,61,90,.35)}\n"
    ".btns{display:grid;grid-template-columns:1fr 1fr;grid-gap:var(--s2)}\n"
    "button.xl{width:100%;min-height:3.4rem;font-size:1.25rem;letter-spacing:.06em}\n"
    "[dir=rtl] .label,[dir=rtl] .live,[dir=rtl] button,html[lang=ja] .label,html[lang=zh] .label{letter-spacing:0}\n"
    "/* language menu */\n"
    "#langbox{position:relative;z-index:40}\n"
    "#langbtn{min-height:2.5rem;font-size:.85rem;text-transform:uppercase}\n"
    "#langbtn:before{background:var(--deck)}\n"
    "#langlist{display:none;position:absolute;right:0;top:calc(100% + .5rem);z-index:60;width:28rem;max-width:calc(100vw - 2rem);padding:.6rem;\n"
    "grid-template-columns:1fr 1fr;grid-gap:.3rem;background:var(--deck);border:2px solid var(--lime);box-shadow:0 1.2rem 2.5rem rgba(0,0,0,.75)}\n"
    "[dir=rtl] #langlist{right:auto;left:0}\n"
    "#langlist.show{display:grid}\n"
    ".langopt{width:100%;min-height:2.6rem;font-size:.95rem;font-weight:700;text-align:start;letter-spacing:0}\n"
    ".langopt:before{left:0;right:0;transform:none;background:var(--void);border-color:var(--edge)}\n"
    ".langopt.on{color:var(--void)}.langopt.on:before{background:var(--lime);border-color:var(--lime)}\n"
    "/* devices */\n"
    ".hint{margin:var(--s2) 0 0;font-size:.85rem;line-height:1.3}\n"
    ".sub{display:flex;align-items:center;margin:var(--s4) 0 var(--s2);font-size:.74rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--ink2)}\n"
    ".sub .spin{margin-inline-start:var(--s2)}\n"
    "[dir=rtl] .sub{letter-spacing:0}\n"
    ".list{overflow-y:auto;overflow-x:hidden;padding:2px;margin:-2px;scrollbar-width:thin;scrollbar-color:#5a5466 rgba(255,255,255,.04)}\n"
    ".list::-webkit-scrollbar{width:6px}.list::-webkit-scrollbar-track{background:rgba(255,255,255,.04)}.list::-webkit-scrollbar-thumb{background:#5a5466}.list::-webkit-scrollbar-thumb:hover{background:var(--lime)}\n"
    ".list>p{margin:var(--s1) 0;padding:var(--s2) var(--s3);font-size:.85rem;border:1px dashed var(--edge2)}\n"
    "/* one device = one card: icon | name + details | signal | actions */\n"
    ".dl{display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;grid-gap:var(--s3);align-items:center;min-height:3.5rem;\n"
    "padding:var(--s2) var(--s2) var(--s2) var(--s3);margin-bottom:var(--s2);background:rgba(255,255,255,.025);\n"
    "border:1px solid var(--edge);border-inline-start:3px solid var(--edge2);transition:border-color .12s,background .12s}\n"
    "[dir=rtl] .dl{padding:var(--s2) var(--s3) var(--s2) var(--s2)}\n"
    ".dl:last-child{margin-bottom:0}\n"
    ".dl:focus-within{border-color:rgba(200,255,61,.55);background:rgba(200,255,61,.05)}\n"
    ".dl.on{border-color:rgba(200,255,61,.4);border-inline-start-color:var(--lime);background:linear-gradient(90deg,rgba(200,255,61,.12),rgba(200,255,61,.03))}\n"
    "[dir=rtl] .dl.on{background:linear-gradient(270deg,rgba(200,255,61,.12),rgba(200,255,61,.03))}\n"
    ".dl.busy{border-inline-start-color:var(--warn)}\n"
    ".dl .ico{display:flex;align-items:center;justify-content:center;width:2.4rem;height:2.4rem;color:var(--ink2);background:var(--void);border:1px solid var(--edge)}\n"
    ".dl .ico svg{width:1.45rem;height:1.45rem}\n"
    ".dl.on .ico{color:var(--void);background:var(--lime);border-color:var(--lime)}\n"
    ".dl .nm{min-width:0}\n"
    ".dl .nm b{display:block;font-size:1.05rem;line-height:1.2;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;direction:ltr;unicode-bidi:isolate}\n"
    "[dir=rtl] .dl .nm b{text-align:right}\n"
    ".dl .meta{display:flex;align-items:center;margin-top:.15rem;font-size:.76rem;white-space:nowrap;overflow:hidden}\n"
    ".addr{direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums;letter-spacing:.02em}\n"
    ".dl .meta .addr{min-width:0;overflow:hidden;text-overflow:ellipsis}\n"
    ".dl .acts{display:grid;grid-auto-flow:column;grid-gap:var(--s1)}\n"
    ".dl button{min-width:6.6rem;min-height:2.4rem;padding:.2rem .9rem;font-size:.9rem}\n"
    ".badge{flex:0 0 auto;display:inline-block;margin-inline-end:var(--s2);padding:0 .45em;font-size:.68rem;font-weight:900;line-height:1.45;background:var(--lime);color:var(--void)}\n"
    ".badge.warn{background:var(--warn);animation:blink 1.2s infinite}\n"
    ".badge.off{background:none;color:var(--mute);box-shadow:inset 0 0 0 1px var(--edge2)}\n"
    ".sig{display:flex;align-items:center}\n"
    ".bars{display:inline-flex;align-items:flex-end;height:1rem;direction:ltr}\n"
    ".bars i{width:.24rem;margin-inline-end:.14rem;background:var(--edge2)}.bars i:last-child{margin-inline-end:0}\n"
    ".bars i:nth-child(1){height:30%}.bars i:nth-child(2){height:55%}.bars i:nth-child(3){height:78%}.bars i:nth-child(4){height:100%}\n"
    ".bars i.on{background:var(--lime)}.bars.b1 i.on{background:var(--warn)}\n"
    "/* found-nearby connect = secondary (outline) so Scan and the saved list stay the primary actions */\n"
    "#devlist button.act{color:var(--lime)}#devlist button.act:before{background:rgba(200,255,61,.06);border-color:rgba(200,255,61,.6)}\n"
    "#devlist button.act:hover,#devlist button.act:focus{color:var(--void)}#devlist button.act:hover:before,#devlist button.act:focus:before{background:var(--lime)}\n"
    ".spin{display:inline-block;width:.8rem;height:.8rem;border:2px solid var(--lime);border-right-color:transparent;border-radius:50%;animation:rot 1s linear infinite}\n"
    "@keyframes rot{to{transform:rotate(360deg)}}\n"
    "/* volume */\n"
    ".ctl{padding:var(--s2) var(--s3) var(--s3);margin-bottom:var(--s2);background:rgba(0,0,0,.22);border:1px solid var(--edge)}\n"
    ".ctl:focus-within{border-color:var(--lime);box-shadow:0 0 0 3px rgba(200,255,61,.3),0 0 1.2rem rgba(200,255,61,.18)}\n"
    ".row{display:flex;justify-content:space-between;align-items:center}\n"
    ".row>span:first-child{min-width:0;margin-inline-end:var(--s3)}\n"
    ".cl{font-size:.92rem;font-weight:700;color:var(--ink2);line-height:1.2}\n"
    ".big{font-size:2.2rem;font-weight:900;line-height:1;color:var(--lime);direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums}\n"
    "input[type=range]{display:block;width:100%;height:1.6rem;margin:var(--s2) 0 0;background:none;accent-color:var(--lime);-webkit-appearance:none;appearance:none;overflow:hidden;outline:none;cursor:pointer}\n"
    "input[type=range]::-webkit-slider-runnable-track{height:1.6rem;background:repeating-linear-gradient(90deg,transparent 0 calc(10% - 2px),rgba(255,255,255,.08) calc(10% - 2px) 10%),var(--void)}\n"
    "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:.6rem;height:1.6rem;background:#fff;box-shadow:-100vw 0 0 100vw rgba(200,255,61,.85)}\n"
    "[dir=rtl] input[type=range]::-webkit-slider-thumb{box-shadow:100vw 0 0 100vw rgba(200,255,61,.85)}\n"
    "input[type=range]::-moz-range-track{height:1.6rem;background:var(--void)}\n"
    "input[type=range]::-moz-range-progress{height:1.6rem;background:var(--lime)}\n"
    "input[type=range]::-moz-range-thumb{width:.6rem;height:1.6rem;border:0;border-radius:0;background:#fff}\n"
    ".vol .btns{margin-top:var(--s1)}.devbtns{margin-top:var(--s2);grid-template-columns:1fr}.devbtns button{min-width:0}\n"
    "/* equalizer: colour per band, live response curve */\n"
    "body{--b0:#ff6a2b;--b1:#ffb23d;--b2:#c8ff3d;--b3:#3dd6ff;--b4:#b06bff}\n"
    ".eqhead{display:flex;align-items:center;justify-content:space-between;margin:0 0 var(--s2)}\n"
    ".eqhead button{min-height:2.3rem;min-width:6rem;font-size:.9rem}\n"
    ".curve{position:relative;height:5.2rem;margin:0 0 var(--s2);background:\n"
    "linear-gradient(0deg,transparent calc(50% - 1px),rgba(255,255,255,.18) calc(50% - 1px) 50%,transparent 50%),\n"
    "repeating-linear-gradient(90deg,transparent 0 calc(20% - 1px),rgba(255,255,255,.05) calc(20% - 1px) 20%),var(--void);border:1px solid var(--edge)}\n"
    ".curve svg{position:absolute;top:0;left:0;width:100%;height:100%}\n"
    ".eqp.off .curve,.eqp.off .bands{opacity:.4;filter:saturate(.3)}\n"
    ".bands{display:grid;grid-gap:.35rem}\n"
    ".band{display:grid;grid-template-columns:5.6rem minmax(0,1fr) 3.4rem;grid-gap:var(--s2);align-items:center}\n"
    ".band .bn{font-size:.82rem;font-weight:800;color:var(--ink2);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    ".band .bn i{display:inline-block;width:.55rem;height:.55rem;margin-inline-end:.4rem;transform:rotate(45deg);background:var(--c)}\n"
    ".band .bv{font-weight:900;text-align:end;color:var(--c);direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums}\n"
    ".band input[type=range]{margin:0;height:1.3rem;accent-color:var(--c);direction:ltr}\n"
    ".band input[type=range]::-webkit-slider-runnable-track{height:1.3rem;background:var(--trk,var(--void))}\n"
    ".band input[type=range]::-webkit-slider-thumb{height:1.3rem;width:.55rem;background:var(--c);box-shadow:0 0 .6rem var(--c)}\n"
    ".band input[type=range]::-moz-range-track{height:1.3rem;background:var(--trk,var(--void))}\n"
    ".band input[type=range]::-moz-range-progress{background:none}\n"
    ".band input[type=range]::-moz-range-thumb{height:1.3rem;width:.55rem;background:var(--c)}\n"
    ".presets{display:flex;flex-wrap:wrap;margin:var(--s2) calc(var(--s1)*-1) 0}\n"
    ".presets button{min-height:2.2rem;padding:.1rem .8rem;font-size:.84rem;margin:var(--s1) 0}\n"
    ".presets button.act{color:var(--void)}.presets button.act:before{background:var(--b3);border-color:var(--b3)}\n"
    "/* codec picker: segmented row */\n"
    ".seg{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(0,1fr);grid-gap:var(--s1);margin:0 0 var(--s2)}\n"
    ".seg button{min-height:2.5rem;padding:.2rem .4rem;font-size:.88rem}\n"
    ".seg button[disabled],.seg button.no{color:var(--mute);opacity:.45;cursor:default;pointer-events:none}\n"
    ".cno{margin:0 0 var(--s2);color:var(--ink2)}.cno:empty{display:none}\n"
    ".apick{color:var(--lime);font-weight:800}\n"
    ".seg button{overflow:hidden;text-overflow:ellipsis}\n"
    ".seg button.cur:before{border-color:rgba(200,255,61,.75);box-shadow:inset 0 0 0 1px rgba(200,255,61,.35)}\n"
    ".evlog{margin:0;font-size:.78rem;line-height:1.4;color:var(--mute)}\n"
    ".evlog div{padding:.12rem 0;border-top:1px solid var(--edge)}\n"
    ".seg button[disabled]:before,.seg button.no:before{background:transparent;border-color:var(--edge);border-style:dashed}\n"
    "/* latency meter */\n"
    ".latm{margin:0 0 var(--s2);padding:var(--s2) var(--s3);background:var(--card);border:1px solid var(--edge)}\n"
    ".latm .big{font-size:1.9rem;white-space:nowrap;flex:0 0 auto}.latm .row .cl{min-width:0}\n"
    ".est{display:inline-block;margin-inline-start:.4rem;padding:0 .35rem;font-size:.66rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--void);background:var(--mute)}\n"
    ".lbar{display:flex;height:.7rem;margin:var(--s2) 0 var(--s1);background:var(--void);overflow:hidden;direction:ltr}\n"
    ".lbar i{display:block;height:100%;transition:width .4s}\n"
    ".lbar i+i{border-left:2px solid var(--void)}\n"
    ".lkeys{display:flex;flex-wrap:wrap;font-size:.74rem;color:var(--ink2)}\n"
    ".lkeys span{margin-inline-end:.9rem;white-space:nowrap}\n"
    ".lkeys b{display:inline-block;width:.55rem;height:.55rem;margin-inline-end:.3rem;transform:rotate(45deg)}\n"
    ".lkeys em{font-style:normal;font-weight:800;color:var(--ink);direction:ltr;unicode-bidi:isolate}\n"
    ".lt{display:grid;grid-template-columns:auto minmax(0,1fr) 4.2rem;grid-gap:var(--s3);align-items:center;margin-top:var(--s2)}\n"
    ".lt .v{text-align:end}\n"
    ".latm .lt input[type=range]{margin:0}\n"
    "/* connection */\n"
    ".conn .cbox{display:grid;grid-template-columns:auto minmax(0,1fr);grid-gap:var(--s4);align-items:center}\n"
    ".conn .note{margin:0;font-size:.8rem;line-height:1.3}\n"
    "#stop{min-width:13rem}\n"
    "/* status: name, compact key/value list, slim level meters */\n"
    ".now{order:-2;display:flex;align-items:center;min-width:0;margin-bottom:var(--s3)}\n"
    ".nowico{flex:0 0 auto;display:flex;align-items:center;justify-content:center;width:2.6rem;height:2.6rem;margin-inline-end:var(--s3);color:var(--void);background:var(--lime);transform:skewX(var(--sk))}\n"
    ".nowico svg{width:1.5rem;height:1.5rem;transform:skewX(calc(var(--sk)*-1))}\n"
    "#stats[style*=none]+.now .nowico{color:var(--mute);background:var(--card);box-shadow:inset 0 0 0 1px var(--edge2)}\n"
    ".dev{flex:1;min-width:0;margin:0;font-size:1.6rem;font-weight:900;line-height:1.15;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;direction:ltr;unicode-bidi:isolate}\n"
    "[dir=rtl] .dev{text-align:right}\n"
    ".idle{order:1;display:none;flex:1;min-height:0;align-items:center;justify-content:center;color:var(--edge)}\n"
    ".idle svg{width:auto;height:5rem}\n"
    "#stats[style*=none]~.idle{display:flex}\n"
    "#stats{display:flex;flex-direction:column;min-height:0}\n"
    ".kv{display:grid;grid-template-columns:auto minmax(0,1fr);margin:0;border-top:1px solid var(--edge)}\n"
    ".kv>*{display:flex;align-items:center;flex-wrap:wrap;min-height:2.3rem;padding:var(--s1) 0;margin:0;border-bottom:1px solid var(--edge)}\n"
    ".kv>.k{padding-inline-end:var(--s5);font-size:.8rem;font-weight:700;line-height:1.2}\n"
    ".kv>.v{font-size:1rem}\n"
    "[dir=rtl] .kv>.v{justify-content:flex-end}\n"
    ".chips{padding-bottom:0}\n"
    ".chip{display:inline-block;margin:.12rem 0;margin-inline-end:var(--s1);padding:.1rem .5rem;font-size:.84rem;font-weight:700;line-height:1.35;white-space:nowrap;\n"
    "color:var(--ink);background:var(--card);border:1px solid var(--edge2);unicode-bidi:isolate}\n"
    ".chip.n{direction:ltr;font-variant-numeric:tabular-nums}\n"
    ".chip.hi{color:var(--void);background:var(--lime);border-color:var(--lime);font-weight:900}\n"
    ".chip.off{color:var(--mute);background:none}\n"
    ".meters{display:grid;grid-template-columns:1fr 1fr;grid-gap:var(--s5);margin-top:var(--s3)}\n"
    ".mrow{display:flex;justify-content:space-between;align-items:baseline;font-size:.82rem}\n"
    ".mrow .k{font-weight:700}.mrow .v{font-size:1rem}\n"
    ".meter{position:relative;height:.55rem;margin-top:var(--s1);overflow:hidden;\n"
    "background:linear-gradient(90deg,rgba(255,255,255,.07) 0 85%,rgba(255,61,90,.3) 85%)}\n"
    "[dir=rtl] .meter{background:linear-gradient(270deg,rgba(255,255,255,.07) 0 85%,rgba(255,61,90,.3) 85%)}\n"
    ".meter div{height:100%;width:0;background:var(--lime);box-shadow:0 0 .5rem rgba(200,255,61,.45);transition:width .3s}\n"
    "[dir=rtl] .meter div{margin-left:auto}\n"
    ".meter:after{content:\"\";position:absolute;top:0;bottom:0;left:0;right:0;\n"
    "background:linear-gradient(90deg,transparent calc(25% - 1px),var(--deck) calc(25% - 1px) 25%,transparent 25% calc(50% - 1px),var(--deck) calc(50% - 1px) 50%,transparent 50% calc(75% - 1px),var(--deck) calc(75% - 1px) 75%,transparent 75%)}\n"
    "/* mid widths: two columns, page may scroll */\n"
    "@media(min-width:760px){\n"
    ".grid{grid-template-columns:minmax(0,1fr) minmax(0,1fr);grid-template-areas:\"dev st\" \"dev vol\" \"dev eq\" \"dev conn\";grid-template-rows:auto auto auto 1fr}\n"
    ".conn{align-self:start}\n"
    "}\n"
    "/* TV: one screen, no page scroll. Everything is rem, rem follows the viewport. */\n"
    "@media(min-width:1180px) and (min-height:600px){\n"
    "html{font-size:13px;font-size:clamp(12px,min(1.04vw,1.9vh),26px)}\n"
    ".wrap{height:100vh}\n"
    ".grid{flex:1;min-height:0;grid-template-columns:minmax(0,1.05fr) minmax(0,1fr) minmax(0,1fr);\n"
    "grid-template-areas:\"dev st eq\" \"dev vol conn\";grid-template-rows:minmax(0,1fr) auto}\n"
    "/* left column: devices as tall as their content (found list ~3 rows, scrolls), the log takes the rest */\n"
    ".side .hero{flex:0 1 auto}\n"
    ".side .logp{flex:1 1 0;min-height:13rem}\n"
    ".side .hero{min-height:0}\n"
    "#devlist .dl,#savedlist .dl{min-height:2.9rem;padding-top:.2rem;padding-bottom:.2rem}\n"
    ".side #savedlist{flex:0 0 auto;max-height:none}\n"
    ".side #scan{min-height:2.9rem}.side .devbtns button{min-height:2.5rem}\n"
    ".side .hint{margin-top:var(--s1);margin-bottom:var(--s1)}\n"
    "#devlist .dl button{min-height:2.2rem}\n"
    ".logp .evlog div{padding:.06rem 0}\n"
    ".logp .evlog{flex:1 1 0;min-height:0;overflow-y:auto}\n"
    ".eqp{min-height:0}\n"
    ".eqp .presets button{min-height:1.9rem;margin:.1rem 0;padding:.1rem .65rem}\n"
    ".conn{align-self:stretch}\n"
    "#savedlist{flex:0 1 auto;max-height:34%}\n"
    "/* one screen: the longer hints only show on phones and laptops */\n"
    "#codecnote,#latnote{display:none}\n"
    ".eqp .curve{flex:1 1 0;height:auto;min-height:1.4rem;max-height:6rem}.eqp .bands,.eqp .presets,.eqp .eqhead{flex:0 0 auto}\n"
    "#devlist{flex:0 1 auto;min-height:3.2rem;max-height:10rem}\n"
    "/* spare height goes to the status card (meters sit at its bottom, idle art fills it) */\n"
    ".status #stats{flex:1}.status .meters{margin-top:auto;padding-top:var(--s3)}\n"
    ".vol .ctl{margin-bottom:var(--s3)}\n"
    ".big{font-size:2.6rem}\n"
    ".vol input[type=range],.vol input[type=range]::-webkit-slider-runnable-track,.vol input[type=range]::-webkit-slider-thumb,.vol input[type=range]::-moz-range-track,.vol input[type=range]::-moz-range-progress,.vol input[type=range]::-moz-range-thumb{height:2rem}\n"
    ".vol .btns button{min-height:3rem}\n"
    ".idle svg{height:70%;max-height:9rem}\n"
    "}\n"
    "/* below TV width: saved-device actions go on their own line under the name */\n"
    "@media(max-width:1179px){\n"
    "#savedlist .dl{grid-template-columns:auto minmax(0,1fr);grid-row-gap:var(--s2)}#savedlist .ico{grid-row:1}#savedlist .nm{grid-column:2;grid-row:1}#savedlist .sig{display:none}#savedlist .acts{grid-column:1/-1;grid-row:2;grid-auto-columns:1fr}\n"
    "}\n"
    "@media(max-width:759px){\n"
    ".bar{flex-wrap:wrap}.brand{width:100%;margin-bottom:.7rem}\n"
    ".live{margin-inline-start:.3rem}\n"
    ".dl{grid-template-columns:auto minmax(0,1fr) auto;grid-row-gap:0}\n"
    ".dl .ico{grid-row:1/3}.dl .nm{grid-column:2;grid-row:1}.dl .sig{grid-column:2;grid-row:2;margin-top:.2rem}.dl .acts{grid-column:3;grid-row:1/3}\n"
    ".kv{grid-template-columns:minmax(0,1fr)}.kv>.k{min-height:0;padding:var(--s2) 0 0;border-bottom:0}.kv>.v,.kv>.chips{min-height:0;padding:var(--s1) 0 var(--s2)}\n"
    ".dl button{min-width:0}\n"
    ".meters{grid-template-columns:1fr;grid-gap:var(--s2)}\n"
    ".conn .cbox{grid-template-columns:1fr}\n"
    "#stop{width:100%;min-width:0}\n"
    ".msg{top:.6rem}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body><div class=\"wrap\">\n"
    "<header class=\"bar\">\n"
    "<div class=\"brand\"><span class=\"logo\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.4\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg></span>\n"
    "<div><h1>Hear<b>Bridge</b> PS5</h1><div class=\"meta\"><span class=\"ver\" id=\"ver\">-</span><span class=\"by\">Developed by X-F1REBALL-X</span><a class=\"diag\" href=\"/api/diag\" title=\"/api/diag\">diag.txt</a></div></div></div>\n"
    "<div class=\"live\" id=\"live\"><i></i><span id=\"state\">-</span></div>\n"
    "<div id=\"langbox\"><button type=\"button\" id=\"langbtn\" aria-haspopup=\"true\"><span data-i18n=\"language\">Language</span></button><div id=\"langlist\" role=\"menu\"></div></div>\n"
    "</header>\n"
    "<div class=\"msg\" id=\"msg\"></div>\n"
    "<main class=\"grid\">\n"
    "<div class=\"side\">\n"
    "<section class=\"panel hero\" id=\"devpanel\"><p class=\"label\" data-i18n=\"devices\">Devices</p>\n"
    "<button id=\"scan\" class=\"act xl\" data-i18n=\"scan\">Scan for devices</button>\n"
    "<div class=\"btns devbtns\"><button id=\"reconnect\" data-i18n=\"reconnect\">Reconnect</button></div>\n"
    "<p class=\"k hint\" data-i18n=\"scanHint\">Put the headphones in pairing mode, then press Scan.</p>\n"
    "<p class=\"sub\" data-i18n=\"saved\">Saved headphones</p><div id=\"savedlist\" class=\"list\"></div>\n"
    "<p class=\"sub\"><span data-i18n=\"found\">Found nearby</span><span id=\"scanning\" class=\"spin\" style=\"display:none\"></span></p><div id=\"devlist\" class=\"list\"></div>\n"
    "</section>\n"
    "<section class=\"panel logp\"><p class=\"label\" data-i18n=\"log\">Log</p>\n"
    "<div class=\"evlog\" id=\"evlog\"><div class=\"k\" data-i18n=\"logEmpty\">Nothing yet</div></div></section>\n"
    "</div>\n"
    "<section class=\"panel status\"><p class=\"label\" data-i18n=\"status\">Status</p>\n"
    "<div id=\"stats\" style=\"display:none\">\n"
    "<div class=\"kv\">\n"
    "<span class=\"k\" data-i18n=\"packets\">Packets / SBC frames</span><span class=\"v\" id=\"pk\">-</span>\n"
    "<span class=\"k\" data-i18n=\"avrcp\">AVRCP</span><span class=\"chips\" id=\"av\">-</span>\n"
    "<span class=\"k\" data-i18n=\"format\">Format</span><span class=\"chips\" id=\"fmt\">-</span>\n"
    "</div>\n"
    "<div class=\"meters\">\n"
    "<div><div class=\"mrow\"><span class=\"k\" data-i18n=\"capPeak\">Capture peak</span><span class=\"v\" id=\"pkv\">-</span></div><div class=\"meter\"><div id=\"m1\"></div></div></div>\n"
    "<div><div class=\"mrow\"><span class=\"k\" data-i18n=\"outPeak\">Output peak</span><span class=\"v\" id=\"opv\">-</span></div><div class=\"meter\"><div id=\"m2\"></div></div></div>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\"now\"><span class=\"nowico\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.4\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg></span><p class=\"dev\" id=\"dev\">-</p></div>\n"
    "<div class=\"idle\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg></div>\n"
    "</section>\n"
    "<section class=\"panel vol\"><p class=\"label\" data-i18n=\"volume\">Volume</p>\n"
    "<div class=\"ctl\"><div class=\"row\"><span class=\"cl\" data-i18n=\"boost\">Boost (software gain)</span><span class=\"big\" id=\"gv\">-</span></div>\n"
    "<input type=\"range\" id=\"gain\" min=\"0\" max=\"500\" step=\"10\"></div>\n"
    "<div class=\"ctl\"><div class=\"row\"><span class=\"cl\" data-i18n=\"headset\">Headset volume (AVRCP)</span><span class=\"big\" id=\"hv\">-</span></div>\n"
    "<input type=\"range\" id=\"hs\" min=\"0\" max=\"127\" step=\"1\"></div>\n"
    "<div class=\"btns\"><button id=\"mute\" data-i18n=\"mute\">Mute</button><button id=\"tone\" data-i18n=\"tone\">Test tone</button><button id=\"clean\" data-i18n=\"clean\">Clean sound</button></div>\n"
    "</section>\n"
    "<section class=\"panel eqp\" id=\"eqp\"><p class=\"label\" data-i18n=\"equalizer\">Equalizer</p>\n"
    "<div class=\"eqhead\"><span class=\"k note\" data-i18n=\"eqHint\">Saved for this headset.</span><button id=\"eqon\" data-i18n=\"eqOff\">Off</button></div>\n"
    "<div class=\"curve\"><svg viewBox=\"0 0 300 100\" preserveAspectRatio=\"none\" aria-hidden=\"true\"><defs><linearGradient id=\"eqg\" x1=\"0\" x2=\"1\" y1=\"0\" y2=\"0\">\n"
    "<stop offset=\"0\" stop-color=\"#ff6a2b\"/><stop offset=\".3\" stop-color=\"#ffb23d\"/><stop offset=\".5\" stop-color=\"#c8ff3d\"/><stop offset=\".72\" stop-color=\"#3dd6ff\"/><stop offset=\"1\" stop-color=\"#b06bff\"/></linearGradient></defs>\n"
    "<path id=\"eqfill\" fill=\"url(#eqg)\" fill-opacity=\".18\" d=\"\"/><path id=\"eqline\" fill=\"none\" stroke=\"url(#eqg)\" stroke-width=\"2.5\" vector-effect=\"non-scaling-stroke\" d=\"\"/></svg></div>\n"
    "<div class=\"bands\">\n"
    "<div class=\"band\" style=\"--c:var(--b0)\"><span class=\"bn\"><i></i><span data-i18n=\"eqBass\">Bass</span></span><input type=\"range\" id=\"eq0\" min=\"-12\" max=\"12\" step=\"1\"><span class=\"bv\" id=\"eqv0\">0</span></div>\n"
    "<div class=\"band\" style=\"--c:var(--b1)\"><span class=\"bn\"><i></i><span data-i18n=\"eqLowMid\">Low mid</span></span><input type=\"range\" id=\"eq1\" min=\"-12\" max=\"12\" step=\"1\"><span class=\"bv\" id=\"eqv1\">0</span></div>\n"
    "<div class=\"band\" style=\"--c:var(--b2)\"><span class=\"bn\"><i></i><span data-i18n=\"eqMid\">Mid</span></span><input type=\"range\" id=\"eq2\" min=\"-12\" max=\"12\" step=\"1\"><span class=\"bv\" id=\"eqv2\">0</span></div>\n"
    "<div class=\"band\" style=\"--c:var(--b3)\"><span class=\"bn\"><i></i><span data-i18n=\"eqPresence\">Presence</span></span><input type=\"range\" id=\"eq3\" min=\"-12\" max=\"12\" step=\"1\"><span class=\"bv\" id=\"eqv3\">0</span></div>\n"
    "<div class=\"band\" style=\"--c:var(--b4)\"><span class=\"bn\"><i></i><span data-i18n=\"eqTreble\">Treble</span></span><input type=\"range\" id=\"eq4\" min=\"-12\" max=\"12\" step=\"1\"><span class=\"bv\" id=\"eqv4\">0</span></div>\n"
    "</div>\n"
    "<div class=\"presets\"><button id=\"pr0\" data-i18n=\"prFlat\">Flat</button><button id=\"pr1\" data-i18n=\"prBassBoost\">Bass boost</button><button id=\"pr2\" data-i18n=\"prBassCut\">Bass cut</button><button id=\"pr3\" data-i18n=\"prTreble\">Treble boost</button><button id=\"pr4\" data-i18n=\"prVoice\">Voice / footsteps</button></div>\n"
    "</section>\n"
    "<section class=\"panel conn\"><p class=\"label\" data-i18n=\"connection\">Connection</p>\n"
    "<p class=\"sub\" data-i18n=\"codec\">Codec</p>\n"
    "<div class=\"seg\" id=\"codecs\"><button id=\"cd0\" data-i18n=\"codecAuto\">Auto</button><button id=\"cd1\">SBC</button><button id=\"cd2\">SBC HQ</button><button id=\"cd3\">SBC-XQ</button></div>\n"
    "<p class=\"k note cno\" id=\"codecno\"></p>\n"
    "<p class=\"k note cno\" id=\"xqnote\"></p>\n"
    "<p class=\"k note\" id=\"codecnote\" data-i18n=\"codecHint\">Auto is plain SBC. SBC HQ and SBC-XQ only if you pick them, and only when this headset supports them.</p>\n"
    "<p class=\"sub\" data-i18n=\"latency\">Latency</p>\n"
    "<div class=\"latm\"><div class=\"row\"><span class=\"cl\"><span data-i18n=\"latEst\">Delay to your ears</span><span class=\"est\" data-i18n=\"estimate\">estimate</span></span><span class=\"big\" id=\"latv\">-</span></div>\n"
    "<div class=\"lbar\" id=\"lbar\"><i id=\"lb0\" style=\"background:var(--b0)\"></i><i id=\"lb1\" style=\"background:var(--b2)\"></i><i id=\"lb2\" style=\"background:var(--b3)\"></i><i id=\"lb3\" style=\"background:var(--b4)\"></i></div>\n"
    "<div class=\"lkeys\" id=\"lkeys\"></div>\n"
    "<div class=\"lt\"><span class=\"cl\" data-i18n=\"latTarget\">Buffer target</span><input type=\"range\" id=\"lat\" min=\"60\" max=\"200\" step=\"1\"><span class=\"v\" id=\"latt\">-</span></div></div>\n"
    "<p class=\"k note\" id=\"latnote\" data-i18n=\"latHint\">Lower: less delay. Higher: fewer dropouts when the radio is busy. Saved for this headset.</p>\n"
    "<div class=\"cbox\"><button id=\"stop\" class=\"red\" data-i18n=\"stop\">Stop HearBridge</button>\n"
    "<p class=\"k note\" data-i18n=\"footer\">Closing this page leaves HearBridge running.</p></div>\n"
    "</section>\n"
    "</main>\n"
    "</div>\n"
    "<script>\n"
    "var I18N={\"langs\":[{\"code\":\"en\",\"name\":\"English\",\"rtl\":false},{\"code\":\"ar\",\"name\":\"العربية\",\"rtl\":true},{\"code\":\"es\",\"name\":\"Español\",\"rtl\":false},{\"code\":\"fr\",\"name\":\"Français\",\"rtl\":false},{\"code\":\"de\",\"name\":\"Deutsch\",\"rtl\":false},{\"code\":\"pt\",\"name\":\"Português\",\"rtl\":false},{\"code\":\"ru\",\"name\":\"Русский\",\"rtl\":false},{\"code\":\"ja\",\"name\":\"日本語\",\"rtl\":false},{\"code\":\"zh\",\"name\":\"中文\",\"rtl\":false},{\"code\":\"it\",\"name\":\"Italiano\",\"rtl\":false},{\"code\":\"he\",\"name\":\"עברית\",\"rtl\":true}],\"strings\":{\"en\":{\"language\":\"Language\",\"status\":\"Status\",\"starting\":\"Starting\",\"connecting\":\"Connecting\",\"streaming\":\"Streaming\",\"reconnecting\":\"Reconnecting\",\"paused\":\"Not connected\",\"device\":\"Device\",\"packets\":\"Packets / SBC frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"not connected\",\"avrcpConn\":\"connected\",\"avrcpAbs\":\"absolute volume\",\"notif\":\"notifications\",\"capPeak\":\"Capture peak\",\"outPeak\":\"Output peak\",\"volume\":\"Volume\",\"boost\":\"Boost (software gain)\",\"headset\":\"Headset volume (AVRCP)\",\"mute\":\"Mute\",\"unmute\":\"Unmute\",\"tone\":\"Test tone\",\"toneOn\":\"Tone on\",\"clean\":\"Clean sound\",\"recent\":\"Recent\",\"log\":\"Log\",\"logEmpty\":\"Nothing yet\",\"why_away\":\"headset went away\",\"connection\":\"Connection\",\"connect\":\"Connect\",\"disconnect\":\"Disconnect\",\"stop\":\"Stop HearBridge\",\"stopConfirm\":\"Stop HearBridge?\",\"unreachable\":\"Not reachable - is HearBridge running?\",\"queue\":\"queue\",\"footer\":\"Closing this page leaves HearBridge running.\",\"devices\":\"Devices\",\"scanning\":\"Scanning\",\"waiting-selection\":\"Choose your headphones\",\"pairing\":\"Pairing\",\"choose\":\"Choose\",\"noDevices\":\"No audio devices found yet.\",\"pairHint\":\"Press Scan again to refresh the list.\",\"error\":\"Error\",\"connected\":\"Connected\",\"scan\":\"Scan for devices\",\"reconnect\":\"Reconnect\",\"saved\":\"Saved headphones\",\"noSaved\":\"No saved headphones yet.\",\"found\":\"Found nearby\",\"forget\":\"Forget\",\"forgetConfirm\":\"Forget this device?\",\"current\":\"In use\",\"connectTo\":\"Connect\",\"scanHint\":\"Put the headphones in pairing mode and press Scan. The scan takes about 20 seconds.\",\"signal\":\"Signal\",\"perPkt\":\"frames/packet\",\"notConnected\":\"Not connected\",\"disconnected\":\"Not connected\",\"latHint\":\"Lower: less delay. Higher: fewer dropouts when the radio is busy. Saved for this headset.\",\"reload\":\"HearBridge was restarted. Reload this page.\",\"unsupportedFmt\":\"device needs 48 kHz stereo, not supported\",\"volOnHeadset\":\"Volume on headset\",\"volSoftware\":\"Software volume\",\"codec\":\"Codec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto picked %s\",\"codecHint\":\"Auto is plain SBC. SBC HQ and SBC-XQ only if you pick them, and only when this headset supports them.\",\"codecNo\":\"Not supported by this headset\",\"equalizer\":\"Equalizer\",\"eqHint\":\"Saved for this headset.\",\"eqOn\":\"On\",\"eqOff\":\"Off\",\"eqBass\":\"Bass\",\"eqLowMid\":\"Low mid\",\"eqMid\":\"Mid\",\"eqPresence\":\"Presence\",\"eqTreble\":\"Treble\",\"prFlat\":\"Flat\",\"prBassBoost\":\"Bass boost\",\"prBassCut\":\"Bass cut\",\"prTreble\":\"Treble boost\",\"prVoice\":\"Voice / footsteps\",\"latency\":\"Latency\",\"latEst\":\"Delay to your ears\",\"estimate\":\"estimate\",\"latTarget\":\"Buffer target\",\"latPipe\":\"PS5 + encoder\",\"latQueue\":\"Queue\",\"latRadio\":\"Radio\",\"latSink\":\"Headset\",\"latSinkTyp\":\"Headset (typical)\",\"codecWait\":\"SBC HQ and SBC-XQ show up once a headset that supports them is connected.\",\"xqLow\":\"SBC-XQ is staying at a low bitpool on this link. Plain SBC will sound better.\",\"why_timeout\":\"timed out\",\"why_dropped\":\"headset dropped the link\",\"why_closed\":\"headset closed the audio\",\"why_quiet\":\"no audio coming back\",\"why_held\":\"headset still busy — try again in a few seconds\",\"why_failed\":\"could not connect\",\"why_off\":\"disconnected on this page\"},\"ar\":{\"language\":\"اللغة\",\"status\":\"الحالة\",\"starting\":\"جارٍ البدء\",\"connecting\":\"جارٍ الاتصال\",\"streaming\":\"يتم البث\",\"reconnecting\":\"إعادة الاتصال\",\"paused\":\"غير متصل\",\"device\":\"الجهاز\",\"packets\":\"الحزم / إطارات SBC\",\"format\":\"التنسيق\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"غير متصل\",\"avrcpConn\":\"متصل\",\"avrcpAbs\":\"مستوى صوت مطلق\",\"notif\":\"إشعارات\",\"capPeak\":\"ذروة الالتقاط\",\"outPeak\":\"ذروة الإخراج\",\"volume\":\"مستوى الصوت\",\"boost\":\"تعزيز (كسب برمجي)\",\"headset\":\"صوت السماعة (AVRCP)\",\"mute\":\"كتم\",\"unmute\":\"إلغاء الكتم\",\"tone\":\"نغمة اختبار\",\"toneOn\":\"النغمة تعمل\",\"clean\":\"صوت نظيف\",\"recent\":\"الأخير\",\"log\":\"السجل\",\"logEmpty\":\"لا شيء بعد\",\"why_away\":\"السماعة ابتعدت\",\"connection\":\"الاتصال\",\"connect\":\"اتصال\",\"disconnect\":\"قطع الاتصال\",\"stop\":\"إيقاف HearBridge\",\"stopConfirm\":\"إيقاف HearBridge؟\",\"unreachable\":\"تعذّر الوصول - هل HearBridge يعمل؟\",\"queue\":\"قائمة الانتظار\",\"footer\":\"إغلاق هذه الصفحة يُبقي HearBridge قيد التشغيل.\",\"devices\":\"الأجهزة\",\"scanning\":\"جارٍ البحث\",\"waiting-selection\":\"اختر سماعاتك\",\"pairing\":\"جارٍ الإقران\",\"choose\":\"اختيار\",\"noDevices\":\"لم يُعثر على أجهزة صوت بعد.\",\"pairHint\":\"اضغط «البحث» مرة أخرى لتحديث القائمة.\",\"error\":\"خطأ\",\"connected\":\"متصل\",\"scan\":\"البحث عن أجهزة\",\"reconnect\":\"إعادة الاتصال\",\"saved\":\"السماعات المحفوظة\",\"noSaved\":\"لا توجد سماعات محفوظة بعد.\",\"found\":\"أجهزة قريبة\",\"forget\":\"نسيان\",\"forgetConfirm\":\"هل تريد نسيان هذا الجهاز؟\",\"current\":\"قيد الاستخدام\",\"connectTo\":\"اتصال\",\"scanHint\":\"ضع السماعات في وضع الإقران واضغط «البحث». يستغرق البحث نحو 20 ثانية.\",\"signal\":\"الإشارة\",\"perPkt\":\"إطار/حزمة\",\"notConnected\":\"غير متصل\",\"disconnected\":\"غير متصل\",\"latHint\":\"أقل: تأخير أقل. أعلى: انقطاعات أقل عندما يكون الراديو مشغولاً. يُحفظ لهذه السماعة.\",\"reload\":\"تمت إعادة تشغيل HearBridge. أعد تحميل هذه الصفحة.\",\"unsupportedFmt\":\"الجهاز لا يدعم 48 كيلوهرتز ستيريو، غير مدعوم\",\"volOnHeadset\":\"الصوت من السماعة\",\"volSoftware\":\"صوت برمجي\",\"codec\":\"الترميز\",\"codecAuto\":\"تلقائي\",\"autoPicked\":\"اختار التلقائي %s\",\"codecHint\":\"الوضع التلقائي هو SBC العادي. SBC HQ وSBC-XQ فقط إذا اخترتهما، وفقط عندما تدعمهما السماعة.\",\"codecNo\":\"غير مدعوم في هذه السماعة\",\"equalizer\":\"المعادل الصوتي\",\"eqHint\":\"يُحفظ لهذه السماعة.\",\"eqOn\":\"تشغيل\",\"eqOff\":\"إيقاف\",\"eqBass\":\"الجهير\",\"eqLowMid\":\"متوسط منخفض\",\"eqMid\":\"المتوسط\",\"eqPresence\":\"الحضور\",\"eqTreble\":\"الحاد\",\"prFlat\":\"مسطح\",\"prBassBoost\":\"تعزيز الجهير\",\"prBassCut\":\"تقليل الجهير\",\"prTreble\":\"تعزيز الحاد\",\"prVoice\":\"الأصوات / الخطوات\",\"latency\":\"زمن الاستجابة\",\"latEst\":\"التأخير حتى أذنيك\",\"estimate\":\"تقدير\",\"latTarget\":\"هدف التخزين المؤقت\",\"latPipe\":\"PS5 + المُرمِّز\",\"latQueue\":\"الطابور\",\"latRadio\":\"الراديو\",\"latSink\":\"السماعة\",\"latSinkTyp\":\"السماعة (نموذجي)\",\"codecWait\":\"يظهر SBC HQ وSBC-XQ عند توصيل سماعة تدعمهما.\",\"xqLow\":\"SBC-XQ عالق عند معدل بت منخفض على هذا الرابط. صوت SBC العادي سيكون أفضل.\",\"why_timeout\":\"انتهت المهلة\",\"why_dropped\":\"السماعة قطعت الاتصال\",\"why_closed\":\"السماعة أغلقت الصوت\",\"why_quiet\":\"لا يرجع صوت\",\"why_held\":\"السماعة ما زالت مشغولة — حاول بعد ثوانٍ\",\"why_failed\":\"تعذر الاتصال\",\"why_off\":\"قُطع من هذه الصفحة\"},\"es\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitiendo\",\"reconnecting\":\"Reconectando\",\"paused\":\"No conectado\",\"device\":\"Dispositivo\",\"packets\":\"Paquetes / tramas SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"no conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volumen absoluto\",\"notif\":\"notificaciones\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de salida\",\"volume\":\"Volumen\",\"boost\":\"Refuerzo (ganancia por software)\",\"headset\":\"Volumen de los auriculares (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Activar sonido\",\"tone\":\"Tono de prueba\",\"toneOn\":\"Tono activo\",\"clean\":\"Sonido limpio\",\"recent\":\"Reciente\",\"log\":\"Registro\",\"logEmpty\":\"Nada todavía\",\"why_away\":\"los auriculares se fueron\",\"connection\":\"Conexión\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Detener HearBridge\",\"stopConfirm\":\"¿Detener HearBridge?\",\"unreachable\":\"Sin respuesta: ¿está HearBridge en ejecución?\",\"queue\":\"cola\",\"footer\":\"Cerrar esta página deja HearBridge en marcha.\",\"devices\":\"Dispositivos\",\"scanning\":\"Buscando\",\"waiting-selection\":\"Elige tus auriculares\",\"pairing\":\"Emparejando\",\"choose\":\"Elegir\",\"noDevices\":\"Aún no se encontraron dispositivos de audio.\",\"pairHint\":\"Pulsa Buscar de nuevo para actualizar la lista.\",\"error\":\"Error\",\"connected\":\"Conectado\",\"scan\":\"Buscar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Auriculares guardados\",\"noSaved\":\"Aún no hay auriculares guardados.\",\"found\":\"Encontrados cerca\",\"forget\":\"Olvidar\",\"forgetConfirm\":\"¿Olvidar este dispositivo?\",\"current\":\"En uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Pon los auriculares en modo de emparejamiento y pulsa Buscar. La búsqueda dura unos 20 segundos.\",\"signal\":\"Señal\",\"perPkt\":\"tramas/paquete\",\"notConnected\":\"No conectado\",\"disconnected\":\"No conectado\",\"latHint\":\"Menos: menos retardo. Más: menos cortes cuando la radio está ocupada. Se guarda para estos auriculares.\",\"reload\":\"HearBridge se ha reiniciado. Recarga esta página.\",\"unsupportedFmt\":\"el dispositivo no admite 48 kHz estéreo, no compatible\",\"volOnHeadset\":\"Volumen en los auriculares\",\"volSoftware\":\"Volumen por software\",\"codec\":\"Códec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto eligió %s\",\"codecHint\":\"Auto es SBC normal. SBC HQ y SBC-XQ solo si los eliges, y solo si estos auriculares los admiten.\",\"codecNo\":\"No compatible con estos auriculares\",\"equalizer\":\"Ecualizador\",\"eqHint\":\"Se guarda para estos auriculares.\",\"eqOn\":\"Activado\",\"eqOff\":\"Desactivado\",\"eqBass\":\"Graves\",\"eqLowMid\":\"Medios bajos\",\"eqMid\":\"Medios\",\"eqPresence\":\"Presencia\",\"eqTreble\":\"Agudos\",\"prFlat\":\"Plano\",\"prBassBoost\":\"Más graves\",\"prBassCut\":\"Menos graves\",\"prTreble\":\"Más agudos\",\"prVoice\":\"Voces / pasos\",\"latency\":\"Latencia\",\"latEst\":\"Retardo hasta tus oídos\",\"estimate\":\"estimación\",\"latTarget\":\"Búfer objetivo\",\"latPipe\":\"PS5 + codificador\",\"latQueue\":\"Cola\",\"latRadio\":\"Radio\",\"latSink\":\"Auriculares\",\"latSinkTyp\":\"Auriculares (típico)\",\"codecWait\":\"SBC HQ y SBC-XQ aparecen al conectar unos auriculares que los admitan.\",\"xqLow\":\"SBC-XQ se queda en un bitpool bajo en este enlace. El SBC normal sonará mejor.\",\"why_timeout\":\"tiempo agotado\",\"why_dropped\":\"los auriculares cortaron el enlace\",\"why_closed\":\"los auriculares cerraron el audio\",\"why_quiet\":\"no vuelve el audio\",\"why_held\":\"auriculares aún ocupados — inténtalo en unos segundos\",\"why_failed\":\"no se pudo conectar\",\"why_off\":\"desconectado desde esta página\"},\"fr\":{\"language\":\"Langue\",\"status\":\"État\",\"starting\":\"Démarrage\",\"connecting\":\"Connexion\",\"streaming\":\"Diffusion\",\"reconnecting\":\"Reconnexion\",\"paused\":\"Non connecté\",\"device\":\"Appareil\",\"packets\":\"Paquets / trames SBC\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connecté\",\"avrcpConn\":\"connecté\",\"avrcpAbs\":\"volume absolu\",\"notif\":\"notifications\",\"capPeak\":\"Crête de capture\",\"outPeak\":\"Crête de sortie\",\"volume\":\"Volume\",\"boost\":\"Amplification (gain logiciel)\",\"headset\":\"Volume du casque (AVRCP)\",\"mute\":\"Couper le son\",\"unmute\":\"Rétablir le son\",\"tone\":\"Son de test\",\"toneOn\":\"Son actif\",\"clean\":\"Son net\",\"recent\":\"Récent\",\"log\":\"Journal\",\"logEmpty\":\"Rien pour l'instant\",\"why_away\":\"le casque s'est éloigné\",\"connection\":\"Connexion\",\"connect\":\"Connecter\",\"disconnect\":\"Déconnecter\",\"stop\":\"Arrêter HearBridge\",\"stopConfirm\":\"Arrêter HearBridge ?\",\"unreachable\":\"Injoignable : HearBridge est-il lancé ?\",\"queue\":\"file\",\"footer\":\"Fermer cette page laisse HearBridge actif.\",\"devices\":\"Appareils\",\"scanning\":\"Recherche\",\"waiting-selection\":\"Choisissez votre casque\",\"pairing\":\"Appairage\",\"choose\":\"Choisir\",\"noDevices\":\"Aucun appareil audio trouvé pour l'instant.\",\"pairHint\":\"Appuyez à nouveau sur Rechercher pour actualiser la liste.\",\"error\":\"Erreur\",\"connected\":\"Connecté\",\"scan\":\"Rechercher des appareils\",\"reconnect\":\"Reconnecter\",\"saved\":\"Casques enregistrés\",\"noSaved\":\"Aucun casque enregistré pour l'instant.\",\"found\":\"Trouvés à proximité\",\"forget\":\"Oublier\",\"forgetConfirm\":\"Oublier cet appareil ?\",\"current\":\"Utilisé\",\"connectTo\":\"Connecter\",\"scanHint\":\"Mettez le casque en mode appairage et appuyez sur Rechercher. La recherche dure environ 20 secondes.\",\"signal\":\"Signal\",\"perPkt\":\"trames/paquet\",\"notConnected\":\"Non connecté\",\"disconnected\":\"Non connecté\",\"latHint\":\"Plus bas : moins de délai. Plus haut : moins de coupures quand la radio est chargée. Enregistré pour ce casque.\",\"reload\":\"HearBridge a redémarré. Rechargez cette page.\",\"unsupportedFmt\":\"l'appareil n'accepte pas le 48 kHz stéréo, non pris en charge\",\"volOnHeadset\":\"Volume sur le casque\",\"volSoftware\":\"Volume logiciel\",\"codec\":\"Codec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto a choisi %s\",\"codecHint\":\"Auto, c'est le SBC simple. SBC HQ et SBC-XQ seulement si vous les choisissez, et seulement si ce casque les accepte.\",\"codecNo\":\"Non pris en charge par ce casque\",\"equalizer\":\"Égaliseur\",\"eqHint\":\"Enregistré pour ce casque.\",\"eqOn\":\"Activé\",\"eqOff\":\"Désactivé\",\"eqBass\":\"Basses\",\"eqLowMid\":\"Bas-médiums\",\"eqMid\":\"Médiums\",\"eqPresence\":\"Présence\",\"eqTreble\":\"Aigus\",\"prFlat\":\"Plat\",\"prBassBoost\":\"Basses +\",\"prBassCut\":\"Basses −\",\"prTreble\":\"Aigus +\",\"prVoice\":\"Voix / pas\",\"latency\":\"Latence\",\"latEst\":\"Délai jusqu'à vos oreilles\",\"estimate\":\"estimation\",\"latTarget\":\"Tampon visé\",\"latPipe\":\"PS5 + encodeur\",\"latQueue\":\"File\",\"latRadio\":\"Radio\",\"latSink\":\"Casque\",\"latSinkTyp\":\"Casque (typique)\",\"codecWait\":\"SBC HQ et SBC-XQ apparaissent quand un casque qui les accepte est connecté.\",\"xqLow\":\"SBC-XQ reste sur un bitpool bas sur cette liaison. Le SBC simple sonnera mieux.\",\"why_timeout\":\"délai dépassé\",\"why_dropped\":\"le casque a coupé le lien\",\"why_closed\":\"le casque a fermé l'audio\",\"why_quiet\":\"plus d'audio en retour\",\"why_held\":\"casque encore occupé — réessayez dans quelques secondes\",\"why_failed\":\"connexion impossible\",\"why_off\":\"déconnecté depuis cette page\"},\"de\":{\"language\":\"Sprache\",\"status\":\"Status\",\"starting\":\"Startet\",\"connecting\":\"Verbinde\",\"streaming\":\"Überträgt\",\"reconnecting\":\"Verbinde neu\",\"paused\":\"Nicht verbunden\",\"device\":\"Gerät\",\"packets\":\"Pakete / SBC-Frames\",\"format\":\"Format\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"nicht verbunden\",\"avrcpConn\":\"verbunden\",\"avrcpAbs\":\"absolute Lautstärke\",\"notif\":\"Benachrichtigungen\",\"capPeak\":\"Aufnahme-Spitze\",\"outPeak\":\"Ausgabe-Spitze\",\"volume\":\"Lautstärke\",\"boost\":\"Verstärkung (Software)\",\"headset\":\"Kopfhörer-Lautstärke (AVRCP)\",\"mute\":\"Stumm\",\"unmute\":\"Ton an\",\"tone\":\"Testton\",\"toneOn\":\"Ton läuft\",\"clean\":\"Klarer Klang\",\"recent\":\"Zuletzt\",\"log\":\"Protokoll\",\"logEmpty\":\"Noch nichts\",\"why_away\":\"Headset ist weg\",\"connection\":\"Verbindung\",\"connect\":\"Verbinden\",\"disconnect\":\"Trennen\",\"stop\":\"HearBridge beenden\",\"stopConfirm\":\"HearBridge beenden?\",\"unreachable\":\"Nicht erreichbar – läuft HearBridge?\",\"queue\":\"Warteschlange\",\"footer\":\"Diese Seite zu schließen lässt HearBridge weiterlaufen.\",\"devices\":\"Geräte\",\"scanning\":\"Suche\",\"waiting-selection\":\"Kopfhörer auswählen\",\"pairing\":\"Kopplung\",\"choose\":\"Auswählen\",\"noDevices\":\"Noch keine Audiogeräte gefunden.\",\"pairHint\":\"Drücke erneut Suchen, um die Liste zu aktualisieren.\",\"error\":\"Fehler\",\"connected\":\"Verbunden\",\"scan\":\"Nach Geräten suchen\",\"reconnect\":\"Neu verbinden\",\"saved\":\"Gespeicherte Kopfhörer\",\"noSaved\":\"Noch keine gespeicherten Kopfhörer.\",\"found\":\"In der Nähe gefunden\",\"forget\":\"Entfernen\",\"forgetConfirm\":\"Dieses Gerät entfernen?\",\"current\":\"In Verwendung\",\"connectTo\":\"Verbinden\",\"scanHint\":\"Versetze die Kopfhörer in den Kopplungsmodus und drücke Suchen. Die Suche dauert etwa 20 Sekunden.\",\"signal\":\"Signal\",\"perPkt\":\"Frames/Paket\",\"notConnected\":\"Nicht verbunden\",\"disconnected\":\"Nicht verbunden\",\"latHint\":\"Niedriger: weniger Verzögerung. Höher: weniger Aussetzer bei ausgelastetem Funk. Wird für dieses Headset gespeichert.\",\"reload\":\"HearBridge wurde neu gestartet. Seite neu laden.\",\"unsupportedFmt\":\"Gerät unterstützt kein 48 kHz Stereo, nicht unterstützt\",\"volOnHeadset\":\"Lautstärke am Headset\",\"volSoftware\":\"Software-Lautstärke\",\"codec\":\"Codec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto hat %s gewählt\",\"codecHint\":\"Auto ist normales SBC. SBC HQ und SBC-XQ nur, wenn du sie wählst, und nur wenn dieses Headset sie kann.\",\"codecNo\":\"Von diesem Headset nicht unterstützt\",\"equalizer\":\"Equalizer\",\"eqHint\":\"Für dieses Headset gespeichert.\",\"eqOn\":\"An\",\"eqOff\":\"Aus\",\"eqBass\":\"Bass\",\"eqLowMid\":\"Tiefe Mitten\",\"eqMid\":\"Mitten\",\"eqPresence\":\"Präsenz\",\"eqTreble\":\"Höhen\",\"prFlat\":\"Linear\",\"prBassBoost\":\"Bass-Boost\",\"prBassCut\":\"Weniger Bass\",\"prTreble\":\"Höhen-Boost\",\"prVoice\":\"Stimmen / Schritte\",\"latency\":\"Latenz\",\"latEst\":\"Verzögerung bis zum Ohr\",\"estimate\":\"Schätzung\",\"latTarget\":\"Pufferziel\",\"latPipe\":\"PS5 + Encoder\",\"latQueue\":\"Warteschlange\",\"latRadio\":\"Funk\",\"latSink\":\"Headset\",\"latSinkTyp\":\"Headset (typisch)\",\"codecWait\":\"SBC HQ und SBC-XQ erscheinen, sobald ein Headset verbunden ist, das sie unterstützt.\",\"xqLow\":\"SBC-XQ bleibt auf diesem Link bei einem niedrigen Bitpool. Normales SBC klingt besser.\",\"why_timeout\":\"Zeit abgelaufen\",\"why_dropped\":\"Headset hat die Verbindung getrennt\",\"why_closed\":\"Headset hat den Ton geschlossen\",\"why_quiet\":\"kein Ton kommt zurück\",\"why_held\":\"Headset noch belegt — in ein paar Sekunden erneut versuchen\",\"why_failed\":\"Verbindung fehlgeschlagen\",\"why_off\":\"hier auf der Seite getrennt\"},\"pt\":{\"language\":\"Idioma\",\"status\":\"Estado\",\"starting\":\"Iniciando\",\"connecting\":\"Conectando\",\"streaming\":\"Transmitindo\",\"reconnecting\":\"Reconectando\",\"paused\":\"Não conectado\",\"device\":\"Dispositivo\",\"packets\":\"Pacotes / quadros SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"não conectado\",\"avrcpConn\":\"conectado\",\"avrcpAbs\":\"volume absoluto\",\"notif\":\"notificações\",\"capPeak\":\"Pico de captura\",\"outPeak\":\"Pico de saída\",\"volume\":\"Volume\",\"boost\":\"Reforço (ganho por software)\",\"headset\":\"Volume do fone (AVRCP)\",\"mute\":\"Silenciar\",\"unmute\":\"Reativar som\",\"tone\":\"Tom de teste\",\"toneOn\":\"Tom ligado\",\"clean\":\"Som limpo\",\"recent\":\"Recente\",\"log\":\"Registo\",\"logEmpty\":\"Ainda nada\",\"why_away\":\"o fone foi embora\",\"connection\":\"Conexão\",\"connect\":\"Conectar\",\"disconnect\":\"Desconectar\",\"stop\":\"Parar o HearBridge\",\"stopConfirm\":\"Parar o HearBridge?\",\"unreachable\":\"Sem resposta: o HearBridge está em execução?\",\"queue\":\"fila\",\"footer\":\"Fechar esta página mantém o HearBridge em execução.\",\"devices\":\"Dispositivos\",\"scanning\":\"Procurando\",\"waiting-selection\":\"Escolha seus fones\",\"pairing\":\"Pareando\",\"choose\":\"Escolher\",\"noDevices\":\"Nenhum dispositivo de áudio encontrado ainda.\",\"pairHint\":\"Toque em Procurar novamente para atualizar a lista.\",\"error\":\"Erro\",\"connected\":\"Conectado\",\"scan\":\"Procurar dispositivos\",\"reconnect\":\"Reconectar\",\"saved\":\"Fones salvos\",\"noSaved\":\"Ainda não há fones salvos.\",\"found\":\"Encontrados por perto\",\"forget\":\"Esquecer\",\"forgetConfirm\":\"Esquecer este dispositivo?\",\"current\":\"Em uso\",\"connectTo\":\"Conectar\",\"scanHint\":\"Coloque os fones no modo de pareamento e toque em Procurar. A busca leva cerca de 20 segundos.\",\"signal\":\"Sinal\",\"perPkt\":\"quadros/pacote\",\"notConnected\":\"Não conectado\",\"disconnected\":\"Não conectado\",\"latHint\":\"Menor: menos atraso. Maior: menos cortes quando o rádio está ocupado. Salvo para este headset.\",\"reload\":\"O HearBridge foi reiniciado. Recarregue esta página.\",\"unsupportedFmt\":\"o dispositivo não aceita 48 kHz estéreo, não suportado\",\"volOnHeadset\":\"Volume no headset\",\"volSoftware\":\"Volume por software\",\"codec\":\"Codec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto escolheu %s\",\"codecHint\":\"Auto é SBC normal. SBC HQ e SBC-XQ só se você escolher, e só quando este headset aceitar.\",\"codecNo\":\"Não suportado por este headset\",\"equalizer\":\"Equalizador\",\"eqHint\":\"Salvo para este headset.\",\"eqOn\":\"Ligado\",\"eqOff\":\"Desligado\",\"eqBass\":\"Graves\",\"eqLowMid\":\"Médios graves\",\"eqMid\":\"Médios\",\"eqPresence\":\"Presença\",\"eqTreble\":\"Agudos\",\"prFlat\":\"Plano\",\"prBassBoost\":\"Mais graves\",\"prBassCut\":\"Menos graves\",\"prTreble\":\"Mais agudos\",\"prVoice\":\"Vozes / passos\",\"latency\":\"Latência\",\"latEst\":\"Atraso até os seus ouvidos\",\"estimate\":\"estimativa\",\"latTarget\":\"Buffer alvo\",\"latPipe\":\"PS5 + codificador\",\"latQueue\":\"Fila\",\"latRadio\":\"Rádio\",\"latSink\":\"Headset\",\"latSinkTyp\":\"Headset (típico)\",\"codecWait\":\"SBC HQ e SBC-XQ aparecem quando um headset compatível estiver conectado.\",\"xqLow\":\"O SBC-XQ fica num bitpool baixo nesta ligação. O SBC normal vai soar melhor.\",\"why_timeout\":\"tempo esgotado\",\"why_dropped\":\"o fone largou a ligação\",\"why_closed\":\"o fone fechou o áudio\",\"why_quiet\":\"o áudio não volta\",\"why_held\":\"fone ainda ocupado — tente de novo em alguns segundos\",\"why_failed\":\"não foi possível ligar\",\"why_off\":\"desligado nesta página\"},\"ru\":{\"language\":\"Язык\",\"status\":\"Состояние\",\"starting\":\"Запуск\",\"connecting\":\"Подключение\",\"streaming\":\"Передача\",\"reconnecting\":\"Переподключение\",\"paused\":\"Не подключено\",\"device\":\"Устройство\",\"packets\":\"Пакеты / кадры SBC\",\"format\":\"Формат\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"не подключено\",\"avrcpConn\":\"подключено\",\"avrcpAbs\":\"абсолютная громкость\",\"notif\":\"уведомления\",\"capPeak\":\"Пик захвата\",\"outPeak\":\"Пик вывода\",\"volume\":\"Громкость\",\"boost\":\"Усиление (программное)\",\"headset\":\"Громкость наушников (AVRCP)\",\"mute\":\"Без звука\",\"unmute\":\"Включить звук\",\"tone\":\"Тестовый тон\",\"toneOn\":\"Тон включён\",\"clean\":\"Чистый звук\",\"recent\":\"Недавнее\",\"log\":\"Журнал\",\"logEmpty\":\"Пока пусто\",\"why_away\":\"гарнитура пропала\",\"connection\":\"Подключение\",\"connect\":\"Подключить\",\"disconnect\":\"Отключить\",\"stop\":\"Остановить HearBridge\",\"stopConfirm\":\"Остановить HearBridge?\",\"unreachable\":\"Нет ответа — HearBridge запущен?\",\"queue\":\"очередь\",\"footer\":\"Если закрыть страницу, HearBridge продолжит работу.\",\"devices\":\"Устройства\",\"scanning\":\"Поиск\",\"waiting-selection\":\"Выберите наушники\",\"pairing\":\"Сопряжение\",\"choose\":\"Выбрать\",\"noDevices\":\"Аудиоустройства пока не найдены.\",\"pairHint\":\"Нажмите «Искать» ещё раз, чтобы обновить список.\",\"error\":\"Ошибка\",\"connected\":\"Подключено\",\"scan\":\"Искать устройства\",\"reconnect\":\"Переподключить\",\"saved\":\"Сохранённые наушники\",\"noSaved\":\"Сохранённых наушников пока нет.\",\"found\":\"Найдены поблизости\",\"forget\":\"Забыть\",\"forgetConfirm\":\"Забыть это устройство?\",\"current\":\"Используется\",\"connectTo\":\"Подключить\",\"scanHint\":\"Переведите наушники в режим сопряжения и нажмите «Искать». Поиск занимает около 20 секунд.\",\"signal\":\"Сигнал\",\"perPkt\":\"кадров/пакет\",\"notConnected\":\"Не подключено\",\"disconnected\":\"Не подключено\",\"latHint\":\"Меньше: ниже задержка. Больше: меньше пропаданий при загруженном радиоканале. Сохраняется для этой гарнитуры.\",\"reload\":\"HearBridge перезапущен. Перезагрузите эту страницу.\",\"unsupportedFmt\":\"устройство не поддерживает 48 кГц стерео\",\"volOnHeadset\":\"Громкость на гарнитуре\",\"volSoftware\":\"Программная громкость\",\"codec\":\"Кодек\",\"codecAuto\":\"Авто\",\"autoPicked\":\"Авто выбрал %s\",\"codecHint\":\"Авто — это обычный SBC. SBC HQ и SBC-XQ только если выбрать их вручную, и только если гарнитура их поддерживает.\",\"codecNo\":\"Эта гарнитура не поддерживает\",\"equalizer\":\"Эквалайзер\",\"eqHint\":\"Сохраняется для этой гарнитуры.\",\"eqOn\":\"Вкл\",\"eqOff\":\"Выкл\",\"eqBass\":\"Басы\",\"eqLowMid\":\"Нижняя середина\",\"eqMid\":\"Середина\",\"eqPresence\":\"Присутствие\",\"eqTreble\":\"Высокие\",\"prFlat\":\"Ровно\",\"prBassBoost\":\"Больше басов\",\"prBassCut\":\"Меньше басов\",\"prTreble\":\"Больше высоких\",\"prVoice\":\"Голоса / шаги\",\"latency\":\"Задержка\",\"latEst\":\"Задержка до ушей\",\"estimate\":\"оценка\",\"latTarget\":\"Целевой буфер\",\"latPipe\":\"PS5 + кодер\",\"latQueue\":\"Очередь\",\"latRadio\":\"Радио\",\"latSink\":\"Гарнитура\",\"latSinkTyp\":\"Гарнитура (типично)\",\"codecWait\":\"SBC HQ и SBC-XQ появятся, когда подключится гарнитура с их поддержкой.\",\"xqLow\":\"SBC-XQ держится на низком битпуле на этом канале. Обычный SBC будет звучать лучше.\",\"why_timeout\":\"время вышло\",\"why_dropped\":\"гарнитура сбросила связь\",\"why_closed\":\"гарнитура закрыла звук\",\"why_quiet\":\"звук не возвращается\",\"why_held\":\"наушники ещё заняты — попробуйте через несколько секунд\",\"why_failed\":\"не удалось подключиться\",\"why_off\":\"отключено на этой странице\"},\"ja\":{\"language\":\"言語\",\"status\":\"状態\",\"starting\":\"起動中\",\"connecting\":\"接続中\",\"streaming\":\"ストリーミング中\",\"reconnecting\":\"再接続中\",\"paused\":\"未接続\",\"device\":\"デバイス\",\"packets\":\"パケット / SBCフレーム\",\"format\":\"形式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未接続\",\"avrcpConn\":\"接続済み\",\"avrcpAbs\":\"絶対音量\",\"notif\":\"通知\",\"capPeak\":\"キャプチャのピーク\",\"outPeak\":\"出力のピーク\",\"volume\":\"音量\",\"boost\":\"ブースト（ソフトウェアゲイン）\",\"headset\":\"ヘッドホンの音量（AVRCP）\",\"mute\":\"ミュート\",\"unmute\":\"ミュート解除\",\"tone\":\"テストトーン\",\"toneOn\":\"トーン再生中\",\"clean\":\"クリアな音\",\"recent\":\"履歴\",\"log\":\"ログ\",\"logEmpty\":\"まだ何もありません\",\"why_away\":\"ヘッドセットがいなくなりました\",\"connection\":\"接続\",\"connect\":\"接続\",\"disconnect\":\"切断\",\"stop\":\"HearBridge を停止\",\"stopConfirm\":\"HearBridge を停止しますか？\",\"unreachable\":\"応答なし - HearBridge は動作中ですか？\",\"queue\":\"キュー\",\"footer\":\"このページを閉じても HearBridge は動作を続けます。\",\"devices\":\"デバイス\",\"scanning\":\"検索中\",\"waiting-selection\":\"ヘッドホンを選択\",\"pairing\":\"ペアリング中\",\"choose\":\"選択\",\"noDevices\":\"オーディオデバイスはまだ見つかっていません。\",\"pairHint\":\"リストを更新するには、もう一度「検索」を押してください。\",\"error\":\"エラー\",\"connected\":\"接続済み\",\"scan\":\"デバイスを検索\",\"reconnect\":\"再接続\",\"saved\":\"保存したヘッドホン\",\"noSaved\":\"保存したヘッドホンはまだありません。\",\"found\":\"近くで見つかったデバイス\",\"forget\":\"削除\",\"forgetConfirm\":\"このデバイスを削除しますか？\",\"current\":\"使用中\",\"connectTo\":\"接続\",\"scanHint\":\"ヘッドホンをペアリングモードにして「検索」を押してください。検索には約20秒かかります。\",\"signal\":\"信号\",\"perPkt\":\"フレーム/パケット\",\"notConnected\":\"未接続\",\"disconnected\":\"未接続\",\"latHint\":\"低くすると遅延が減り、高くすると無線混雑時の途切れが減ります。このヘッドセットに保存されます。\",\"reload\":\"HearBridge が再起動されました。このページを再読み込みしてください。\",\"unsupportedFmt\":\"48 kHz ステレオ非対応のデバイスです\",\"volOnHeadset\":\"音量はヘッドセット側\",\"volSoftware\":\"ソフトウェア音量\",\"codec\":\"コーデック\",\"codecAuto\":\"自動\",\"autoPicked\":\"自動で %s を選択\",\"codecHint\":\"自動は通常のSBCです。SBC HQとSBC-XQは自分で選んだときだけで、このヘッドセットが対応している場合だけです。\",\"codecNo\":\"このヘッドセットは非対応\",\"equalizer\":\"イコライザー\",\"eqHint\":\"このヘッドセット用に保存されます。\",\"eqOn\":\"オン\",\"eqOff\":\"オフ\",\"eqBass\":\"低音\",\"eqLowMid\":\"中低音\",\"eqMid\":\"中音\",\"eqPresence\":\"プレゼンス\",\"eqTreble\":\"高音\",\"prFlat\":\"フラット\",\"prBassBoost\":\"低音強調\",\"prBassCut\":\"低音カット\",\"prTreble\":\"高音強調\",\"prVoice\":\"声 / 足音\",\"latency\":\"遅延\",\"latEst\":\"耳に届くまでの遅延\",\"estimate\":\"推定\",\"latTarget\":\"バッファ目標\",\"latPipe\":\"PS5 + エンコーダー\",\"latQueue\":\"キュー\",\"latRadio\":\"無線\",\"latSink\":\"ヘッドセット\",\"latSinkTyp\":\"ヘッドセット (標準)\",\"codecWait\":\"SBC HQ と SBC-XQ は対応ヘッドセットの接続時に表示されます。\",\"xqLow\":\"この接続では SBC-XQ のビットプールが低いままです。通常の SBC の方がきれいに聞こえます。\",\"why_timeout\":\"時間切れ\",\"why_dropped\":\"ヘッドセットが切断しました\",\"why_closed\":\"ヘッドセットが音声を閉じました\",\"why_quiet\":\"音声が戻ってきません\",\"why_held\":\"ヘッドセットがまだ使用中です — 数秒後にもう一度\",\"why_failed\":\"接続できませんでした\",\"why_off\":\"このページで切断しました\"},\"zh\":{\"language\":\"语言\",\"status\":\"状态\",\"starting\":\"正在启动\",\"connecting\":\"正在连接\",\"streaming\":\"正在传输\",\"reconnecting\":\"正在重新连接\",\"paused\":\"未连接\",\"device\":\"设备\",\"packets\":\"数据包 / SBC 帧\",\"format\":\"格式\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"未连接\",\"avrcpConn\":\"已连接\",\"avrcpAbs\":\"绝对音量\",\"notif\":\"通知\",\"capPeak\":\"采集峰值\",\"outPeak\":\"输出峰值\",\"volume\":\"音量\",\"boost\":\"增益（软件放大）\",\"headset\":\"耳机音量（AVRCP）\",\"mute\":\"静音\",\"unmute\":\"取消静音\",\"tone\":\"测试音\",\"toneOn\":\"测试音开启\",\"clean\":\"纯净声音\",\"recent\":\"最近\",\"log\":\"日志\",\"logEmpty\":\"还没有记录\",\"why_away\":\"耳机离开了\",\"connection\":\"连接\",\"connect\":\"连接\",\"disconnect\":\"断开\",\"stop\":\"停止 HearBridge\",\"stopConfirm\":\"停止 HearBridge？\",\"unreachable\":\"无法访问——HearBridge 是否在运行？\",\"queue\":\"队列\",\"footer\":\"关闭此页面后 HearBridge 仍会运行。\",\"devices\":\"设备\",\"scanning\":\"正在搜索\",\"waiting-selection\":\"选择你的耳机\",\"pairing\":\"正在配对\",\"choose\":\"选择\",\"noDevices\":\"尚未找到音频设备。\",\"pairHint\":\"再次按“搜索”即可刷新列表。\",\"error\":\"错误\",\"connected\":\"已连接\",\"scan\":\"搜索设备\",\"reconnect\":\"重新连接\",\"saved\":\"已保存的耳机\",\"noSaved\":\"还没有已保存的耳机。\",\"found\":\"附近找到的设备\",\"forget\":\"忘记\",\"forgetConfirm\":\"忘记此设备？\",\"current\":\"使用中\",\"connectTo\":\"连接\",\"scanHint\":\"让耳机进入配对模式，然后按“搜索”。搜索大约需要 20 秒。\",\"signal\":\"信号\",\"perPkt\":\"帧/包\",\"notConnected\":\"未连接\",\"disconnected\":\"未连接\",\"latHint\":\"越低延迟越小，越高无线繁忙时断音越少。为此耳机保存。\",\"reload\":\"HearBridge 已重新启动。请重新加载此页面。\",\"unsupportedFmt\":\"设备不支持 48 kHz 立体声\",\"volOnHeadset\":\"音量由耳机控制\",\"volSoftware\":\"软件音量\",\"codec\":\"编解码器\",\"codecAuto\":\"自动\",\"autoPicked\":\"自动选择了 %s\",\"codecHint\":\"自动就是普通 SBC。SBC HQ 和 SBC-XQ 只有手动选择时才会用，而且耳机必须支持。\",\"codecNo\":\"此耳机不支持\",\"equalizer\":\"均衡器\",\"eqHint\":\"为此耳机保存。\",\"eqOn\":\"开\",\"eqOff\":\"关\",\"eqBass\":\"低音\",\"eqLowMid\":\"中低音\",\"eqMid\":\"中音\",\"eqPresence\":\"临场感\",\"eqTreble\":\"高音\",\"prFlat\":\"平直\",\"prBassBoost\":\"低音增强\",\"prBassCut\":\"低音削减\",\"prTreble\":\"高音增强\",\"prVoice\":\"人声 / 脚步声\",\"latency\":\"延迟\",\"latEst\":\"到耳朵的延迟\",\"estimate\":\"估计\",\"latTarget\":\"缓冲目标\",\"latPipe\":\"PS5 + 编码器\",\"latQueue\":\"队列\",\"latRadio\":\"无线\",\"latSink\":\"耳机\",\"latSinkTyp\":\"耳机（典型）\",\"codecWait\":\"连接支持的耳机后才会显示 SBC HQ 和 SBC-XQ。\",\"xqLow\":\"这条链路上 SBC-XQ 的比特池一直很低。普通 SBC 会更好听。\",\"why_timeout\":\"超时\",\"why_dropped\":\"耳机断开了连接\",\"why_closed\":\"耳机关掉了音频\",\"why_quiet\":\"没有音频回来\",\"why_held\":\"耳机仍在忙 — 请几秒后重试\",\"why_failed\":\"连接失败\",\"why_off\":\"在此页面断开\"},\"it\":{\"language\":\"Lingua\",\"status\":\"Stato\",\"starting\":\"Avvio\",\"connecting\":\"Connessione\",\"streaming\":\"In streaming\",\"reconnecting\":\"Riconnessione\",\"paused\":\"Non connesso\",\"device\":\"Dispositivo\",\"packets\":\"Pacchetti / frame SBC\",\"format\":\"Formato\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"non connesso\",\"avrcpConn\":\"connesso\",\"avrcpAbs\":\"volume assoluto\",\"notif\":\"notifiche\",\"capPeak\":\"Picco di cattura\",\"outPeak\":\"Picco di uscita\",\"volume\":\"Volume\",\"boost\":\"Amplificazione (guadagno software)\",\"headset\":\"Volume cuffie (AVRCP)\",\"mute\":\"Muto\",\"unmute\":\"Riattiva audio\",\"tone\":\"Tono di prova\",\"toneOn\":\"Tono attivo\",\"clean\":\"Suono pulito\",\"recent\":\"Recenti\",\"log\":\"Registro\",\"logEmpty\":\"Ancora niente\",\"why_away\":\"le cuffie si sono allontanate\",\"connection\":\"Connessione\",\"connect\":\"Connetti\",\"disconnect\":\"Disconnetti\",\"stop\":\"Arresta HearBridge\",\"stopConfirm\":\"Arrestare HearBridge?\",\"unreachable\":\"Non raggiungibile: HearBridge è in esecuzione?\",\"queue\":\"coda\",\"footer\":\"Chiudere questa pagina lascia HearBridge attivo.\",\"devices\":\"Dispositivi\",\"scanning\":\"Ricerca\",\"waiting-selection\":\"Scegli le cuffie\",\"pairing\":\"Abbinamento\",\"choose\":\"Scegli\",\"noDevices\":\"Nessun dispositivo audio trovato finora.\",\"pairHint\":\"Premi di nuovo Cerca per aggiornare l'elenco.\",\"error\":\"Errore\",\"connected\":\"Connesso\",\"scan\":\"Cerca dispositivi\",\"reconnect\":\"Riconnetti\",\"saved\":\"Cuffie salvate\",\"noSaved\":\"Nessuna cuffia salvata.\",\"found\":\"Trovati nelle vicinanze\",\"forget\":\"Dimentica\",\"forgetConfirm\":\"Dimenticare questo dispositivo?\",\"current\":\"In uso\",\"connectTo\":\"Connetti\",\"scanHint\":\"Metti le cuffie in modalità di abbinamento e premi Cerca. La ricerca dura circa 20 secondi.\",\"signal\":\"Segnale\",\"perPkt\":\"frame/pacchetto\",\"notConnected\":\"Non connesso\",\"disconnected\":\"Non connesso\",\"latHint\":\"Più basso: meno ritardo. Più alto: meno interruzioni quando la radio è occupata. Salvato per queste cuffie.\",\"reload\":\"HearBridge è stato riavviato. Ricarica questa pagina.\",\"unsupportedFmt\":\"il dispositivo non accetta 48 kHz stereo, non supportato\",\"volOnHeadset\":\"Volume sulle cuffie\",\"volSoftware\":\"Volume software\",\"codec\":\"Codec\",\"codecAuto\":\"Auto\",\"autoPicked\":\"Auto ha scelto %s\",\"codecHint\":\"Auto è SBC normale. SBC HQ e SBC-XQ solo se li scegli, e solo se queste cuffie li supportano.\",\"codecNo\":\"Non supportato da queste cuffie\",\"equalizer\":\"Equalizzatore\",\"eqHint\":\"Salvato per queste cuffie.\",\"eqOn\":\"Attivo\",\"eqOff\":\"Disattivo\",\"eqBass\":\"Bassi\",\"eqLowMid\":\"Medio-bassi\",\"eqMid\":\"Medi\",\"eqPresence\":\"Presenza\",\"eqTreble\":\"Alti\",\"prFlat\":\"Piatto\",\"prBassBoost\":\"Più bassi\",\"prBassCut\":\"Meno bassi\",\"prTreble\":\"Più alti\",\"prVoice\":\"Voci / passi\",\"latency\":\"Latenza\",\"latEst\":\"Ritardo fino alle orecchie\",\"estimate\":\"stima\",\"latTarget\":\"Buffer obiettivo\",\"latPipe\":\"PS5 + encoder\",\"latQueue\":\"Coda\",\"latRadio\":\"Radio\",\"latSink\":\"Cuffie\",\"latSinkTyp\":\"Cuffie (tipico)\",\"codecWait\":\"SBC HQ e SBC-XQ compaiono quando sono collegate cuffie che li supportano.\",\"xqLow\":\"SBC-XQ resta su un bitpool basso su questo collegamento. L'SBC normale suonerà meglio.\",\"why_timeout\":\"tempo scaduto\",\"why_dropped\":\"le cuffie hanno chiuso il collegamento\",\"why_closed\":\"le cuffie hanno chiuso l'audio\",\"why_quiet\":\"l'audio non torna\",\"why_held\":\"cuffie ancora occupate — riprova tra qualche secondo\",\"why_failed\":\"connessione non riuscita\",\"why_off\":\"disconnesso da questa pagina\"},\"he\":{\"language\":\"שפה\",\"status\":\"מצב\",\"starting\":\"מתחיל\",\"connecting\":\"מתחבר\",\"streaming\":\"משדר\",\"reconnecting\":\"מתחבר מחדש\",\"paused\":\"לא מחובר\",\"device\":\"מכשיר\",\"packets\":\"חבילות / מסגרות SBC\",\"format\":\"פורמט\",\"avrcp\":\"AVRCP\",\"avrcpNone\":\"לא מחובר\",\"avrcpConn\":\"מחובר\",\"avrcpAbs\":\"עוצמה מוחלטת\",\"notif\":\"התראות\",\"capPeak\":\"שיא לכידה\",\"outPeak\":\"שיא יציאה\",\"volume\":\"עוצמת שמע\",\"boost\":\"הגברה (תוכנה)\",\"headset\":\"עוצמת האוזניות (AVRCP)\",\"mute\":\"השתק\",\"unmute\":\"בטל השתקה\",\"tone\":\"צליל בדיקה\",\"toneOn\":\"צליל פועל\",\"clean\":\"צליל נקי\",\"recent\":\"אחרונים\",\"log\":\"יומן\",\"logEmpty\":\"עדיין אין כלום\",\"why_away\":\"האוזניות התרחקו\",\"connection\":\"חיבור\",\"connect\":\"התחבר\",\"disconnect\":\"התנתק\",\"stop\":\"עצור את HearBridge\",\"stopConfirm\":\"לעצור את HearBridge?\",\"unreachable\":\"אין תגובה - האם HearBridge פועל?\",\"queue\":\"תור\",\"footer\":\"סגירת הדף משאירה את HearBridge פועל.\",\"devices\":\"מכשירים\",\"scanning\":\"סורק\",\"waiting-selection\":\"בחרו את האוזניות\",\"pairing\":\"מבצע צימוד\",\"choose\":\"בחר\",\"noDevices\":\"עדיין לא נמצאו מכשירי שמע.\",\"pairHint\":\"לחצו שוב על חיפוש כדי לרענן את הרשימה.\",\"error\":\"שגיאה\",\"connected\":\"מחובר\",\"scan\":\"חיפוש מכשירים\",\"reconnect\":\"התחברות מחדש\",\"saved\":\"אוזניות שמורות\",\"noSaved\":\"אין עדיין אוזניות שמורות.\",\"found\":\"נמצאו בקרבת מקום\",\"forget\":\"שכח\",\"forgetConfirm\":\"לשכוח את המכשיר הזה?\",\"current\":\"בשימוש\",\"connectTo\":\"התחבר\",\"scanHint\":\"העבירו את האוזניות למצב צימוד ולחצו על חיפוש. החיפוש נמשך כ-20 שניות.\",\"signal\":\"אות\",\"perPkt\":\"מסגרות/מנה\",\"notConnected\":\"לא מחובר\",\"disconnected\":\"לא מחובר\",\"latHint\":\"נמוך: פחות השהיה. גבוה: פחות ניתוקים כשהרדיו עמוס. נשמר לאוזניות האלה.\",\"reload\":\"HearBridge הופעל מחדש. טענו מחדש את הדף.\",\"unsupportedFmt\":\"המכשיר לא תומך ב-48 kHz סטריאו, לא נתמך\",\"volOnHeadset\":\"עוצמה באוזניות\",\"volSoftware\":\"עוצמה בתוכנה\",\"codec\":\"קודק\",\"codecAuto\":\"אוטומטי\",\"autoPicked\":\"אוטומטי בחר %s\",\"codecHint\":\"אוטומטי זה SBC רגיל. SBC HQ ו-SBC-XQ רק אם בוחרים אותם, ורק אם האוזניות האלה תומכות בהם.\",\"codecNo\":\"לא נתמך באוזניות האלה\",\"equalizer\":\"אקולייזר\",\"eqHint\":\"נשמר עבור האוזניות האלה.\",\"eqOn\":\"פועל\",\"eqOff\":\"כבוי\",\"eqBass\":\"בס\",\"eqLowMid\":\"אמצע נמוך\",\"eqMid\":\"אמצע\",\"eqPresence\":\"נוכחות\",\"eqTreble\":\"טרבל\",\"prFlat\":\"שטוח\",\"prBassBoost\":\"הגברת בס\",\"prBassCut\":\"הפחתת בס\",\"prTreble\":\"הגברת טרבל\",\"prVoice\":\"קולות / צעדים\",\"latency\":\"השהיה\",\"latEst\":\"השהיה עד האוזניים\",\"estimate\":\"הערכה\",\"latTarget\":\"יעד חוצץ\",\"latPipe\":\"PS5 + מקודד\",\"latQueue\":\"תור\",\"latRadio\":\"רדיו\",\"latSink\":\"אוזניות\",\"latSinkTyp\":\"אוזניות (טיפוסי)\",\"codecWait\":\"SBC HQ ו-SBC-XQ יופיעו כשיחוברו אוזניות שתומכות בהם.\",\"xqLow\":\"SBC-XQ נשאר על ביטפול נמוך בקישור הזה. SBC רגיל יישמע טוב יותר.\",\"why_timeout\":\"הזמן נגמר\",\"why_dropped\":\"האוזניות ניתקו את הקישור\",\"why_closed\":\"האוזניות סגרו את השמע\",\"why_quiet\":\"אין שמע בחזרה\",\"why_held\":\"האוזניות עדיין תפוסות — נסה שוב בעוד כמה שניות\",\"why_failed\":\"לא ניתן להתחבר\",\"why_off\":\"נותק מהעמוד הזה\"}}};\n"
    "var S=null,busyG=0,busyH=0,LANG='en',TOKEN='HBTOKENxxxxxxxxxxxxxxxxxxxxxxxxx';\n"
    "function $(i){return document.getElementById(i)}\n"
    "function t(k){var d=I18N.strings[LANG]||I18N.strings.en;return d[k]||I18N.strings.en[k]||k}\n"
    "function info(c){for(var i=0;i<I18N.langs.length;i++)if(I18N.langs[i].code==c)return I18N.langs[i];return I18N.langs[0]}\n"
    "function setLang(c){var L=info(c);LANG=L.code;try{localStorage.setItem('hb_lang',LANG)}catch(e){}\n"
    "document.documentElement.lang=LANG;document.documentElement.dir=L.rtl?'rtl':'ltr';\n"
    "var n=document.querySelectorAll('[data-i18n]');for(var i=0;i<n.length;i++)n[i].textContent=t(n[i].getAttribute('data-i18n'));\n"
    "var o=$('langlist').getElementsByTagName('button');for(var i2=0;i2<o.length;i2++)o[i2].className='langopt'+(o[i2].getAttribute('data-code')==LANG?' on':'');$('langlist').className='';if(S)draw()}\n"
    "function buildLangs(){var h='',i,L;for(i=0;i<I18N.langs.length;i++){L=I18N.langs[i];\n"
    "h+='<button type=\"button\" class=\"langopt\" role=\"menuitem\" data-code=\"'+L.code+'\"'+(L.rtl?' dir=\"rtl\"':'')+'><span>'+L.name+'</span></button>'}\n"
    "$('langlist').innerHTML=h;var b=$('langlist').getElementsByTagName('button');\n"
    "for(i=0;i<b.length;i++)b[i].onclick=function(){setLang(this.getAttribute('data-code'))};\n"
    "$('langbtn').onclick=function(){$('langlist').className=$('langlist').className?'':'show'}}\n"
    "function xhr(m,p,cb){var x=new XMLHttpRequest();x.open(m,p,true);x.timeout=4000;if(m=='POST')x.setRequestHeader('X-HB-Token',TOKEN);\n"
    "x.onload=function(){if(x.status==200){try{S=JSON.parse(x.responseText);draw()}catch(e){}}else if(x.status==403)$('msg').textContent=t('reload');if(cb)cb()};\n"
    "x.onerror=x.ontimeout=function(){$('msg').textContent=t('unreachable');$('live').className='live bad';if(cb)cb()};\n"
    "x.send()}\n"
    "function req(p,cb){xhr('GET',p,cb)}\n"
    "function act(p,cb){xhr('POST',p,cb)}\n"
    "var devT=0,scanLive=0;\n"
    "function esc(x){return String(x).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}\n"
    "var ICON={\n"
    "head:'<path d=\"M5 15v-3a7 7 0 0 1 14 0v3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><rect x=\"3\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"7\" rx=\"2\" fill=\"currentColor\"/>',\n"
    "spk:'<path d=\"M3 9h4l6-5v16l-6-5H3z\" fill=\"currentColor\"/><path d=\"M16 8a5 5 0 0 1 0 8M18.5 5a9 9 0 0 1 0 14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "tv:'<rect x=\"2\" y=\"4\" width=\"20\" height=\"13\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><path d=\"M8 21h8\" stroke=\"currentColor\" stroke-width=\"2.2\"/>',\n"
    "car:'<path d=\"M3 15l2-6h14l2 6v4H3z\" fill=\"currentColor\"/><circle cx=\"7\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/><circle cx=\"17\" cy=\"19\" r=\"2\" fill=\"#0c0b0f\"/>',\n"
    "mic:'<rect x=\"9\" y=\"2\" width=\"6\" height=\"12\" rx=\"3\" fill=\"currentColor\"/><path d=\"M5 11a7 7 0 0 0 14 0M12 18v4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>',\n"
    "note:'<path d=\"M9 17V5l11-2v12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\"/><circle cx=\"6.5\" cy=\"17.5\" r=\"3\" fill=\"currentColor\"/><circle cx=\"17.5\" cy=\"15.5\" r=\"3\" fill=\"currentColor\"/>'};\n"
    "var KIND={headphones:'head',headset:'head',speaker:'spk',portable:'spk',hifi:'spk',car:'car',handsfree:'mic',tv:'tv',av:'tv',audio:'note'};\n"
    "function icon(k){return '<svg viewBox=\"0 0 24 24\" width=\"34\" height=\"34\" aria-hidden=\"true\">'+ICON[KIND[k]||'note']+'</svg>'}\n"
    "function kindOf(cod){var c=parseInt(cod,16)||0,maj=(c>>8)&31,min=(c>>2)&63;if(maj!=4)return 'audio';\n"
    "return {6:'headphones',1:'headset',5:'speaker',7:'portable',10:'hifi',8:'car',2:'handsfree',9:'tv',14:'tv',15:'tv'}[min]||'av'}\n"
    "function bars(r){if(r==null)return '';var n=r>-60?4:r>-70?3:r>-80?2:1,h='<span class=\"bars b'+n+'\" title=\"'+esc(t('signal'))+': '+r+' dBm\">';\n"
    "for(var i=1;i<=4;i++)h+='<i'+(i<=n?' class=\"on\"':'')+'></i>';return h+'</span>'}\n"
    "function getj(p,cb){var x=new XMLHttpRequest();x.open('GET',p,true);x.timeout=4000;x.onload=function(){try{cb(JSON.parse(x.responseText))}catch(e){}};x.send()}\n"
    "function row(icon,name,meta,btns,cls,sig){return '<div class=\"dl'+(cls?' '+cls:'')+'\"><span class=\"ico\">'+icon+'</span><span class=\"nm\"><b>'+esc(name)+'</b><span class=\"k meta\">'+meta+'</span></span><span class=\"sig\">'+(sig||'')+'</span><span class=\"acts\">'+btns+'</span></div>'}\n"
    "function wire(id){wireEl($(id))}\n"
    "function wireEl(el){var b=el.getElementsByTagName('button');for(var i=0;i<b.length;i++)b[i].onclick=function(){\n"
    "var a=this.getAttribute('data-addr'),f=this.getAttribute('data-forget'),r=this.parentNode&&this.parentNode.parentNode;\n"
    "if(this.getAttribute('data-disc')){act('/api/disconnect');return}\n"
    "if(f){if(confirm(t('forgetConfirm')))act('/api/forget?addr='+a,saved);return}\n"
    "act('/api/select?addr='+a);this.textContent=t('connecting')+'…';\n"
    "/* the label comes back from the list after a few seconds if nothing changed */\n"
    "if(r)setTimeout(function(){r.hbHtml=''},5000)}}\n"
    "/* Lists are patched in place, keyed by address: an unchanged row keeps its\n"
    "   DOM (so a hovered/focused button stays put, no blink every poll); only a\n"
    "   changed row is swapped, and the signal bars are updated on their own. */\n"
    "function patchList(id,rows,empty){var box=$(id),i,r,el,nx,keep={},cur=box.firstChild;\n"
    "if(!rows.length){if(box.hbHtml!==empty){box.hbHtml=empty;box.innerHTML=empty}return}\n"
    "if(box.hbHtml!=null&&box.hbHtml!==''){box.innerHTML='';cur=null}box.hbHtml='';\n"
    "for(i=0;i<rows.length;i++)keep[rows[i].k]=1;\n"
    "for(el=box.firstChild;el;el=nx){nx=el.nextSibling;if(!el.hbKey||!keep[el.hbKey])box.removeChild(el)}\n"
    "cur=box.firstChild;\n"
    "for(i=0;i<rows.length;i++){r=rows[i];el=null;\n"
    "for(nx=box.firstChild;nx;nx=nx.nextSibling)if(nx.hbKey===r.k){el=nx;break}\n"
    "if(el&&el.hbHtml!==r.h){var tmp=document.createElement('div');tmp.innerHTML=r.h;var ne=tmp.firstChild;\n"
    "ne.hbKey=r.k;ne.hbHtml=r.h;wireEl(ne);box.replaceChild(ne,el);el=ne}\n"
    "if(!el){var tmp2=document.createElement('div');tmp2.innerHTML=r.h;el=tmp2.firstChild;el.hbKey=r.k;el.hbHtml=r.h;wireEl(el)}\n"
    "if(el!==cur)box.insertBefore(el,cur);cur=el.nextSibling;\n"
    "var sg=el.querySelector('.sig');if(sg&&sg.hbHtml!==(r.s||'')){sg.hbHtml=r.s||'';sg.innerHTML=r.s||''}}}\n"
    "var SAVL=null;\n"
    "function stOf(){return S?(S.paused?'paused':S.state):''}\n"
    "function linked(){var st=stOf();return st=='streaming'||st=='connected'}\n"
    "function badge(cur){var st=stOf();\n"
    "if(!cur)return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(linked())return '<span class=\"badge\">'+esc(t('connected'))+'</span>';\n"
    "if(st=='paused')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='disconnected')return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>';\n"
    "if(st=='connecting'||st=='pairing')return '<span class=\"badge warn\">'+esc(t('connecting'))+'</span>';\n"
    "return '<span class=\"badge off\">'+esc(t('notConnected'))+'</span>'}\n"
    "function drawSaved(){if(!SAVL)return;var rows=[],i,d,on=linked(),st=stOf(),busy=st=='connecting'||st=='pairing';\n"
    "for(i=0;i<SAVL.length;i++){d=SAVL[i];\n"
    "rows.push({k:d.addr,h:row(icon(d.kind),d.name||d.addr,badge(d.current)+'<span class=\"addr\">'+esc(d.addr)+'</span>',\n"
    "(d.current&&on?'<button type=\"button\" data-disc=\"1\">'+esc(t('disconnect'))+'</button>'\n"
    ":d.current&&busy?'':'<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('reconnect'))+'</button>')\n"
    "+'<button type=\"button\" class=\"red\" data-forget=\"1\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('forget'))+'</button>',\n"
    "d.current&&on?'on':d.current&&busy?'busy':'')})}\n"
    "patchList('savedlist',rows,'<p class=\"k\">'+esc(t('noSaved'))+'</p>')}\n"
    "function saved(){getj('/api/saved',function(j){var i;SAVL=j.devices;SAV={};for(i=0;i<SAVL.length;i++)SAV[SAVL[i].addr]=1;drawSaved()})}\n"
    "var SAV={},SHOW={headphones:1,headset:1,speaker:1,portable:1,hifi:1,handsfree:1},HEAD={headphones:1,headset:1};\n"
    "function devices(){getj('/api/devices',function(j){var rows=[],i,d,k;\n"
    "for(i=0;i<j.devices.length;i++){d=j.devices[i];if(SAV[d.addr])continue;k=d.kind||kindOf(d.cod);if(!SHOW[k]||(!d.name&&!HEAD[k]))continue;\n"
    "rows.push({k:d.addr,h:row(icon(k),d.name||d.addr,'<span class=\"addr\">'+esc(d.addr)+'</span>','<button type=\"button\" class=\"act\" data-addr=\"'+esc(d.addr)+'\">'+esc(t('connectTo'))+'</button>',''),s:bars(d.rssi)})}\n"
    "patchList('devlist',rows,'<p class=\"k\">'+esc(t('noDevices'))+'</p>')})}\n"
    "function pct(v){return Math.round(v)+'%'}\n"
    "function chips(a){var h='',i;for(i=0;i<a.length;i++)h+='<span class=\"chip'+(a[i][1]?' '+a[i][1]:'')+'\">'+esc(a[i][0])+'</span>';return h}\n"
    "function setHtml(id,h){var e=$(id);if(e.hbHtml!==h){e.hbHtml=h;e.innerHTML=h}}\n"
    "function draw(){\n"
    "$('msg').textContent='';\n"
    "$('ver').textContent=S.version;\n"
    "var st=S.paused?'paused':S.state;\n"
    "var det=st=='error'&&S.detail?S.detail.replace(/^error\\s*/,''):'';if(/^unsupported-format/.test(det))det=t('unsupportedFmt');\n"
    "var whyTxt=S.why&&t('why_'+S.why)!=='why_'+S.why?t('why_'+S.why):'';\n"
    "if(whyTxt)det=whyTxt;\n"
    "$('state').textContent={reconnecting:1,disconnected:1,paused:1,error:1,idle:1,'waiting-selection':1}[st]?t('notConnected')+(det?' ('+det+')':''):(t(st)==st?st:t(st));\n"
    "$('live').className='live '+(st=='streaming'||st=='connected'?'ok':(st=='paused'||st=='disconnected'||st=='error'?'bad':'wait'));\n"
    "var on=!!S.connected,link=on||((st=='connecting'||st=='pairing')&&S.device);\n"
    "$('dev').textContent=link?(S.device||'-'):t('notConnected');$('stats').style.display=on?'':'none';\n"
    "if(!on){S.pkts=S.frames=S.backlog=S.sample_rate=0;S.peak=S.out_peak=0;S.avrcp={}}\n"
    "if(st=='scanning')scanLive=Date.now()+12000;\n"
    "if(scanLive&&(st=='waiting-selection'||st=='streaming'||st=='connected'||st=='connecting'||st=='error'||st=='paused'))scanLive=0;\n"
    "$('scanning').style.display=(st=='scanning'||(scanLive&&Date.now()<scanLive))?'':'none';\n"
    "if(Date.now()-devT>3000){devT=Date.now();devices();saved()}\n"
    "drawSaved();\n"
    "$('pk').textContent=S.pkts+' / '+S.frames+(S.backlog?' ('+t('queue')+' '+S.backlog+')':'');\n"
    "\n"
    "setHtml('fmt',S.sample_rate?chips([[S.codec||'SBC','hi n'],[S.sample_rate+' Hz','n'],['bitpool '+S.bitpool+(S.bitpool_max>S.bitpool_min?' ('+S.bitpool_min+'–'+S.bitpool_max+')':''),'n'],[S.per_packet+' '+t('perPkt')]]):'-');\n"
    "var av=S.avrcp||{},avUp=av.connected||av.absolute_volume||av.notifications||av.sink_volume;\n"
    "setHtml('av',!avUp?chips([[t('avrcpNone'),'off']]):chips([[av.absolute_volume?t('avrcpAbs'):t('avrcpConn')]].concat(av.notifications?[[t('notif')]]:[]).concat([[t(av.sink_volume?'volOnHeadset':'volSoftware'),av.sink_volume?'hi':'']])));\n"
    "setHtml('xqnote',S.xq_low?esc(t('xqLow')):'');\n"
    "var ev=S.events||[],eh='';\n"
    "if(!ev.length)eh='<div class=\"k\">'+esc(t('logEmpty'))+'</div>';\n"
    "else for(var ei=0;ei<ev.length;ei++)eh+='<div>'+esc(ev[ei])+'</div>';\n"
    "/* newest at the bottom; follow it unless the user scrolled up to read */\n"
    "var lg=$('evlog'),atEnd=lg.scrollTop+lg.clientHeight>=lg.scrollHeight-6;\n"
    "setHtml('evlog',eh);if(atEnd)lg.scrollTop=lg.scrollHeight;\n"
    "$('pkv').textContent=S.peak.toFixed(3);$('m1').style.width=Math.min(100,S.peak*100)+'%';\n"
    "$('opv').textContent=S.out_peak.toFixed(3);$('m2').style.width=Math.min(100,S.out_peak*100)+'%';\n"
    "if(!busyG)$('gain').value=S.gain_pct;$('gv').textContent=pct(S.gain_pct);\n"
    "if(!busyH&&S.headset_volume>=0)$('hs').value=S.headset_volume;\n"
    "$('hv').textContent=S.headset_volume<0?'-':pct(S.headset_volume*100/127);\n"
    "\n"
    "$('mute').className=S.muted?'ember':'';$('mute').textContent=t(S.muted?'unmute':'mute');\n"
    "$('tone').className=S.tone?'act':'';$('tone').textContent=t(S.tone?'toneOn':'tone');\n"
    "/* only what this headset's capabilities allow can be picked (the server refuses the rest too) */\n"
    "var CN=['','SBC','SBC HQ','SBC-XQ'],nos=[];\n"
    "/* Auto: show what it is actually streaming (button label, hint line, outline on that codec) */\n"
    "var auto=!(S.codec_pref|0),live=auto&&S.sample_rate>0&&S.codec?CN.indexOf(S.codec):-1;\n"
    "$('cd0').textContent=t('codecAuto')+(live>0?' · '+CN[live]:'');\n"
    "/* long languages (he, ar) on small screens: shrink the Auto label until it fits, never clip */\n"
    "var c0=$('cd0'),fs=['','.78rem','.7rem','.62rem'];for(var fi=0;fi<fs.length;fi++){c0.style.fontSize=fs[fi];if(c0.scrollWidth<=c0.clientWidth)break}\n"
    "for(var ci=0;ci<4;ci++){var cb=$('cd'+ci),ok=ci<2||!!(S.codec_avail&(1<<ci));cb.disabled=!ok;\n"
    "cb.className=!ok?'no':(S.codec_pref|0)==ci?'act':ci==live?'cur':'';if(!ok)nos.push(CN[ci])}\n"
    "var ap=live>0?'<span class=\"apick\">'+esc(t('autoPicked').replace('%s',CN[live]))+'</span>':'',\n"
    "cn=!nos.length?'':S.codec_avail?esc(t('codecNo')+': '+nos.join(', ')):esc(t('codecWait'));\n"
    "setHtml('codecno',ap&&cn?ap+' · '+cn:ap||cn)\n"
    "drawEq();drawLat()}\n"
    "/* latency: estimate from the stream loop (see hb_latency_estimate) */\n"
    "var busyL=0,latT=0,latAck=-1,latTouch=0,LATCOL=['var(--b0)','var(--b2)','var(--b3)','var(--b4)'];\n"
    "function pushLat(v){v=parseInt(v,10);if(!(v>=60&&v<=200)||v===latAck)return;latAck=v;latTouch=0;busyL=1;\n"
    "$('latt').textContent=v+' ms';act('/api/latency?ms='+v,function(){busyL=0})}\n"
    "function drawLat(){var L=S.latency;if(!L)return;\n"
    "var ms=L.target_ms;if(ms>200)ms=200;if(ms<60)ms=60;\n"
    "var cur=parseInt($('lat').value,10);\n"
    "if(latTouch&&cur>=60&&cur<=200&&cur!==ms)pushLat(cur);\n"
    "else if(!busyL){$('lat').value=ms;latAck=ms}\n"
    "$('latt').textContent=(latTouch||busyL?$('lat').value:ms)+' ms';\n"
    "var on=S.connected&&L.estimate_ms>0;$('latv').textContent=on?'≈ '+L.estimate_ms+' ms':'-';\n"
    "var parts=[L.capture_ms+L.packet_ms,L.queue_ms,L.radio_ms,L.sink_ms],names=['latPipe','latQueue','latRadio',L.sink_reported?'latSink':'latSinkTyp'],tot=0,i,h='';\n"
    "for(i=0;i<4;i++)tot+=parts[i];\n"
    "for(i=0;i<4;i++){$('lb'+i).style.width=(on&&tot?parts[i]*100/tot:0)+'%';\n"
    "h+='<span><b style=\"background:'+LATCOL[i]+'\"></b>'+esc(t(names[i]))+' <em>'+(on?parts[i]:'-')+' ms</em></span>'}\n"
    "setHtml('lkeys',h)}\n"
    "/* equalizer: same RBJ filters as src/a2dp/eq.c, drawn as a curve */\n"
    "var EQHZ=[80,250,1000,3500,10000],EQQ=[.707,1,1,1,.707],EQCOL=['#ff6a2b','#ffb23d','#c8ff3d','#3dd6ff','#b06bff'],\n"
    "PRESETS=[[0,0,0,0,0],[6,3,0,0,0],[-6,-3,0,0,0],[0,0,0,3,6],[-3,-1,2,5,2]],EQ=null,busyE=0,eqT=0;\n"
    "function biq(b,g){var A=Math.pow(10,g/40),w=2*Math.PI*EQHZ[b]/48000,c=Math.cos(w),s=Math.sin(w),q=EQQ[b],r;\n"
    "if(b==0||b==4){var sa=2*Math.sqrt(A)*s/(2*q);r=b==0?[A*((A+1)-(A-1)*c+sa),2*A*((A-1)-(A+1)*c),A*((A+1)-(A-1)*c-sa),(A+1)+(A-1)*c+sa,-2*((A-1)+(A+1)*c),(A+1)+(A-1)*c-sa]\n"
    ":[A*((A+1)+(A-1)*c+sa),-2*A*((A-1)+(A+1)*c),A*((A+1)+(A-1)*c-sa),(A+1)-(A-1)*c+sa,2*((A-1)-(A+1)*c),(A+1)-(A-1)*c-sa]}\n"
    "else{var al=s/(2*q);r=[1+al*A,-2*c,1-al*A,1+al/A,-2*c,1-al/A]}return r}\n"
    "function eqResp(db,hz){var w=2*Math.PI*hz/48000,t=0,b;for(b=0;b<5;b++){if(!db[b])continue;var k=biq(b,db[b]),\n"
    "nr=k[0]+k[1]*Math.cos(w)+k[2]*Math.cos(2*w),ni=-(k[1]*Math.sin(w)+k[2]*Math.sin(2*w)),dr=k[3]+k[4]*Math.cos(w)+k[5]*Math.cos(2*w),di=-(k[4]*Math.sin(w)+k[5]*Math.sin(2*w));\n"
    "t+=10*Math.log((nr*nr+ni*ni)/(dr*dr+di*di))/Math.LN10}return t}\n"
    "function eqVals(){var v=[],i;for(i=0;i<5;i++)v.push(parseInt($('eq'+i).value,10)||0);return v}\n"
    "function eqPaint(db,on){var d='',i,x,y,n=60;for(i=0;i<=n;i++){x=i*300/n;var hz=20*Math.pow(1000,i/n);\n"
    "y=50-eqResp(db,hz)*50/14;if(y<1)y=1;if(y>99)y=99;d+=(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}\n"
    "$('eqline').setAttribute('d',d);$('eqfill').setAttribute('d',d+'L300 50L0 50Z');\n"
    "for(i=0;i<5;i++){var v=db[i],p=(v+12)/24*100,lo=Math.min(50,p),hi=Math.max(50,p);\n"
    "$('eqv'+i).textContent=(v>0?'+':'')+v+' dB';\n"
    "$('eq'+i).style.setProperty('--trk','linear-gradient(90deg,#0c0b0f '+lo+'%,'+EQCOL[i]+'aa '+lo+'%,'+EQCOL[i]+'aa '+hi+'%,#0c0b0f '+hi+'%)')}\n"
    "for(i=0;i<PRESETS.length;i++)$('pr'+i).className=PRESETS[i].join()==db.join()?'act':'';\n"
    "$('eqp').className='panel eqp'+(on?'':' off');$('eqon').className=on?'act':'';$('eqon').textContent=t(on?'eqOn':'eqOff')}\n"
    "function drawEq(){if(!S.eq)return;if(!busyE&&Date.now()-eqT>1500){var i;for(i=0;i<5;i++)$('eq'+i).value=S.eq.db[i];EQ=S.eq}\n"
    "eqPaint(busyE?eqVals():S.eq.db,S.eq.on)}\n"
    "function eqSend(db,on){var q='/api/eq?on='+(on?1:0),i;for(i=0;i<5;i++)q+='&b'+i+'='+db[i];eqT=Date.now();act(q,function(){busyE=0})}\n"
    "for(var ei=0;ei<5;ei++){$('eq'+ei).oninput=function(){busyE=1;eqPaint(eqVals(),S&&S.eq&&S.eq.on)};\n"
    "$('eq'+ei).onchange=function(){eqSend(eqVals(),1)}}\n"
    "for(var pi=0;pi<5;pi++)$('pr'+pi).onclick=(function(p){return function(){var i;for(i=0;i<5;i++)$('eq'+i).value=PRESETS[p][i];\n"
    "busyE=1;eqPaint(PRESETS[p],1);eqSend(PRESETS[p],1)}})(pi);\n"
    "$('eqon').onclick=function(){var on=!(S&&S.eq&&S.eq.on);eqSend(eqVals(),on)};\n"
    "$('gain').oninput=function(){busyG=1;$('gv').textContent=pct(this.value)};\n"
    "$('gain').onchange=function(){act('/api/volume?pct='+this.value,function(){busyG=0})};\n"
    "/* headset volume: send on release (any of these events; the PS5 browser may skip change),\n"
    "   and never keep the slider frozen: after 1.5 s without input it follows the headset again */\n"
    "var hsT=0,hsSent=-1;\n"
    "function hsPush(){var v=parseInt($('hs').value,10);if(v!==hsSent){hsSent=v;act('/api/headset?vol='+v,function(){busyH=0})}else busyH=0}\n"
    "$('hs').oninput=function(){busyH=1;hsT=Date.now();$('hv').textContent=pct(this.value*100/127)};\n"
    "$('hs').onchange=$('hs').onmouseup=$('hs').ontouchend=$('hs').onpointerup=hsPush;\n"
    "setInterval(function(){if(busyH&&Date.now()-hsT>1500)hsPush()},300);\n"
    "$('mute').onclick=function(){act('/api/mute?on='+(S&&S.muted?0:1))};\n"
    "$('tone').onclick=function(){act('/api/tone?on='+(S&&S.tone?0:1))};\n"
    "$('clean').onclick=function(){act('/api/clean')};\n"
    "function markLat(){latTouch=1;$('latt').textContent=$('lat').value+' ms';pushLat($('lat').value)}\n"
    "$('lat').oninput=markLat;$('lat').onchange=markLat;\n"
    "$('lat').onmouseup=markLat;$('lat').ontouchend=markLat;$('lat').onpointerup=markLat;\n"
    "for(var cj=0;cj<4;cj++)$('cd'+cj).onclick=(function(m){return function(){if(!this.disabled)act('/api/codec?mode='+m)}})(cj);\n"
    "function armScan(){scanLive=Date.now()+12000;$('scanning').style.display='';devices()}\n"
    "$('scan').onclick=function(){act('/api/scan');armScan()};\n"
    "$('reconnect').onclick=function(){act('/api/reconnect')};\n"
    "$('stop').onclick=function(){if(confirm(t('stopConfirm')))act('/api/stop')};\n"
    "buildLangs();\n"
    "(function(){var c=null,m=/[?&]lang=([a-z]{2})/.exec(location.search);if(m)c=m[1];else try{c=localStorage.getItem('hb_lang')}catch(e){}\n"
    "if(!c){var n=(navigator.language||'en').slice(0,2).toLowerCase();c=info(n).code==n?n:'en'}setLang(c)})();\n"
    "req('/api/status');act('/api/scan');armScan();setInterval(function(){req('/api/status')},1000);\n"
    "setInterval(function(){if(scanLive&&Date.now()<scanLive)devices()},300);\n"
    "setInterval(function(){var v=parseInt($('lat').value,10);if(latAck>=0&&v!==latAck){latTouch=1;pushLat(v)}},200);\n"
    "hbTest={req:req};\n"
    "</script></body></html>\n";

#endif
